<script setup>
import { computed, ref, watch } from 'vue'
const props=defineProps({source:Object,workspace:Object})
const emit=defineEmits(['refresh','message'])
const count=ref(3),duration=ref(90),style=ref('BALANCED'),busy=ref(false),episodes=ref([])
const plans=computed(()=>(props.workspace?.['adaptation-plans']||[]).filter(item=>item.novelId===props.source?.id).sort((a,b)=>b.version-a.version))
const current=computed(()=>plans.value[0])
async function json(path,options={}){const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});const body=await response.json();if(!response.ok)throw new Error(body.message||'操作失败');return body}
async function load(){if(!current.value){episodes.value=[];return}try{episodes.value=(await json(`/adaptation-plans/${current.value.id}/episodes`)).map(item=>({...item,sourceChapterText:(item.sourceChapterIds||[]).join(', '),sourceChunkText:(item.sourceChunkIds||[]).join(', ')}))}catch(error){emit('message',error.message,true)}}
watch(()=>current.value?.id,load,{immediate:true})
async function create(){busy.value=true;try{await json(`/novels/${props.source.id}/adaptation-plans`,{method:'POST',body:JSON.stringify({projectId:props.source.projectId,targetEpisodeCount:Number(count.value),targetEpisodeDuration:Number(duration.value),adaptationStyle:style.value,createdBy:'USER'})});emit('message','改编计划已生成，请逐集审查');emit('refresh')}catch(error){emit('message',error.message,true)}finally{busy.value=false}}
async function save(episode){busy.value=true;try{const ids=value=>value.split(',').map(item=>item.trim()).filter(Boolean);await json(`/adaptation-plans/${current.value.id}/episodes/${episode.episodeNo}`,{method:'PATCH',body:JSON.stringify({revision:current.value.revision,episodePlanRevision:episode.revision,sourceChapterIds:ids(episode.sourceChapterText),sourceChunkIds:ids(episode.sourceChunkText),episodeGoal:episode.episodeGoal,openingHook:episode.openingHook,centralConflict:episode.centralConflict,climax:episode.climax,endingHook:episode.endingHook,createdBy:'USER'})});emit('message',`第 ${episode.episodeNo} 集已建立新计划版本，仅复核相邻集`);emit('refresh')}catch(error){emit('message',error.message,true)}finally{busy.value=false}}
async function confirm(){busy.value=true;try{await json(`/adaptation-plans/${current.value.id}/confirm`,{method:'POST',body:JSON.stringify({revision:current.value.revision})});emit('message','改编计划已确认，可以进入分集剧本');emit('refresh')}catch(error){emit('message',error.message,true)}finally{busy.value=false}}
async function generateScript(episode){busy.value=true;try{const version=await json(`/adaptation-plans/${current.value.id}/episodes/${episode.episodeNo}/script`,{method:'POST',body:'{}'});emit('message',`第 ${episode.episodeNo} 集待审剧本 v${version.version} 已进入剧本工作台`);emit('refresh')}catch(error){emit('message',error.message,true)}finally{busy.value=false}}
</script>
<template><section class="panel"><span class="eyebrow">分集改编</span><h3>可审查的改编计划</h3><p>章节与集数可以多对多映射。每集锁定来源、知识边界和未来保留事实。</p><div class="button-row"><label>目标集数 <input v-model.number="count" type="number" min="1"/></label><label>单集秒数 <input v-model.number="duration" type="number" min="10"/></label><label>改编方式 <select v-model="style"><option>FAITHFUL</option><option>BALANCED</option><option>SHORT_DRAMA</option></select></label><button class="primary" :disabled="busy" @click="create">生成计划</button></div><div v-if="current"><p><b>v{{current.version}}</b> · {{current.status}} · 覆盖 {{Math.round((current.coverage?.coverageRatio||0)*100)}}%</p><p v-if="current.continuityIssues?.length" class="error">有 {{current.continuityIssues.length}} 个相邻集状态冲突，修正后才能确认。</p><article v-for="episode in episodes" :key="episode.id" class="panel"><h4>第 {{episode.episodeNo}} 集</h4><label>来源章节 ID（逗号分隔）<textarea v-model="episode.sourceChapterText"/></label><label>来源片段 ID（逗号分隔）<textarea v-model="episode.sourceChunkText"/></label><label>本集目标<textarea v-model="episode.episodeGoal"/></label><label>开场钩子<textarea v-model="episode.openingHook"/></label><label>核心冲突<textarea v-model="episode.centralConflict"/></label><label>高潮<textarea v-model="episode.climax"/></label><label>结尾钩子<textarea v-model="episode.endingHook"/></label><div class="button-row"><button :disabled="busy||current.status==='CONFIRMED'" @click="save(episode)">保存为新版本</button><button v-if="current.status==='CONFIRMED'" class="primary" :disabled="busy" @click="generateScript(episode)">生成待审剧本</button></div></article><button class="primary" :disabled="busy||current.status==='CONFIRMED'||current.continuityIssues?.length" @click="confirm">确认改编计划</button></div></section></template>
