<script setup>
import { computed, onMounted, ref, watch } from 'vue'
const props=defineProps({source:Object,workspace:Object})
const emit=defineEmits(['refresh','message'])
const estimate=ref(null),progress=ref(null),profile=ref('STANDARD'),busy=ref(false)
const reviews=computed(()=> (props.workspace?.['entity-candidates']||[]).filter(item=>item.novelId===props.source?.id&&item.status==='ENTITY_REVIEW_REQUIRED'))
const runs=computed(()=> (props.workspace?.['novel-intelligence-runs']||[]).filter(item=>item.novelId===props.source?.id&&item.type==='ANALYSIS').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))),latestRun=computed(()=>runs.value[0])
const graph=computed(()=> (props.workspace?.['novel-story-graphs']||[]).filter(item=>item.novelId===props.source?.id).at(-1))
const related=key=>(props.workspace?.[key]||[]).filter(item=>item.novelId===props.source?.id)
async function api(path,options={}){const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options}),body=await response.json();if(!response.ok)throw new Error(body.message||'操作失败');return body}
async function load(){if(!props.source)return;try{estimate.value=await api(`/novels/${props.source.id}/analysis/estimate?profile=${profile.value}`);progress.value=await api(`/novels/${props.source.id}/analysis/progress`)}catch(error){emit('message',error.message,true)}}
function budget(){return {maxRequests:estimate.value?.estimatedTotalRequests||1,maxInputTokens:(estimate.value?.estimatedInputTokens||1)*2,maxOutputTokens:estimate.value?.estimatedOutputTokens||1,maxEstimatedCost:estimate.value?.approxCost||0}}
async function start(resume=false){if(!resume&&!confirm(`将按 ${profile.value} 档位执行约 ${estimate.value?.estimatedTotalRequests||0} 次分层文本分析。确认预算并开始？`))return;busy.value=true;try{progress.value=await api(`/novels/${props.source.id}/analysis${resume?'/resume':''}`,{method:'POST',body:JSON.stringify({confirmed:true,liveConfirmed:true,profile:profile.value,budget:budget()})});emit('message',progress.value.status==='SUCCEEDED'?'小说分析已完成':'分析保留了失败块，可单独继续');emit('refresh')}catch(error){emit('message',error.message,true)}finally{busy.value=false}}
async function confirmEntity(item){try{await api(`/novels/${props.source.id}/entity-candidates/${item.id}/confirm`,{method:'POST',body:'{}'});emit('message','实体已人工确认');emit('refresh')}catch(error){emit('message',error.message,true)}}
watch(()=>props.source?.id,load);watch(profile,load);onMounted(load)
</script>
<template><section class="panel" v-if="source"><div class="timeline-head"><h3>小说分析</h3><span class="pill">{{latestRun?.status||progress?.globalGraph||'NOT_STARTED'}}</span></div><div v-if="estimate"><p>{{estimate.chunks}} 个语义块 · {{estimate.chapters}} 章 · {{estimate.arcs}} 个故事弧</p><p>预计 {{estimate.estimatedTotalRequests}} 次：Chunk {{estimate.chunkRequests}} + Chapter {{estimate.chapterRequests}} + Arc {{estimate.arcRequests}} + Global Graph {{estimate.globalGraphRequests}}</p><p>约 {{estimate.estimatedInputTokens}} 输入 tokens / {{estimate.estimatedOutputTokens}} 输出 tokens · {{estimate.pricingStatus==='UNPRICED'?'费用待服务商结算':'估算 '+estimate.approxCost+' '+estimate.currency}}</p></div><label>分析档位<select v-model="profile"><option value="FAST">快速：摘要与主要实体</option><option value="STANDARD">标准：事实、知识和关系</option><option value="DEEP">深入：时间线、伏笔与人物弧</option></select></label><div class="button-row"><button class="primary" :disabled="busy" @click="start(false)">确认预算并开始分析</button><button :disabled="busy||!progress?.failedChunks" @click="start(true)">只继续失败块</button></div><div v-if="latestRun"><p>当前阶段：{{latestRun.phase||latestRun.status}} · {{latestRun.completedUnits||0}} / {{latestRun.totalUnits||0}}</p><p>已用请求 {{latestRun.usedRequests}} / {{latestRun.maxRequests}} · 输入 {{latestRun.usedInputTokens}} / {{latestRun.maxInputTokens}} · 输出 {{latestRun.usedOutputTokens}} / {{latestRun.maxOutputTokens}}</p></div><div v-if="progress"><p>章节解析 {{progress.parsedChapters}} / {{progress.totalChapters}}</p><p>语义分块 {{progress.semanticChunks}} / {{progress.totalChunks}}</p><p>Chunk 分析 {{progress.succeededChunks}} / {{progress.totalChunks}} <span v-if="progress.failedChunks">· 失败 {{progress.failedChunks}}</span></p><p>Chapter 汇总 {{progress.chapterSummaries}} / {{progress.totalChapters}} · Story Arc {{progress.storyArcs}}</p></div><div v-if="graph"><h4>分析结果</h4><p>主线：{{graph.mainPlot||'待审查'}}</p><p>主要人物 {{related('characters').length}} · 人物关系 {{related('relationships').length}} · 地点 {{related('locations').length}} · 道具 {{related('props').length}} · 重要事实 {{related('story-facts').length}}</p><p>支线 {{graph.subPlots?.length||0}} · 故事弧 {{graph.storyArcs?.length||0}} · 伏笔 {{graph.foreshadowing?.length||0}} · 回收 {{graph.payoffs?.length||0}} · 人物弧光 {{graph.characterArcs?.length||0}}</p></div><div v-if="reviews.length"><h4>需要人工确认的实体</h4><div class="job" v-for="item in reviews" :key="item.id"><b>{{item.entityKind}} · {{item.canonicalName}}</b><span>置信度 {{Math.round(item.confidence*100)}}%</span><button class="tiny" @click="confirmEntity(item)">确认归并</button></div></div></section></template>
