<script setup>
import { computed, onMounted, ref, watch } from 'vue'
const props=defineProps({source:Object,workspace:Object})
const emit=defineEmits(['refresh','message'])
const estimate=ref(null),progress=ref(null),profile=ref('STANDARD'),busy=ref(false)
const reviews=computed(()=> (props.workspace?.['entity-candidates']||[]).filter(item=>item.novelId===props.source?.id&&item.status==='ENTITY_REVIEW_REQUIRED'))
async function api(path,options={}){const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options}),body=await response.json();if(!response.ok)throw new Error(body.message||'操作失败');return body}
async function load(){if(!props.source)return;try{estimate.value=await api(`/novels/${props.source.id}/analysis/estimate`);progress.value=await api(`/novels/${props.source.id}/analysis/progress`)}catch(error){emit('message',error.message,true)}}
async function start(resume=false){if(!resume&&!confirm(`将按 ${profile.value} 档位分析 ${estimate.value?.chunks||0} 个语义块。确认开始？`))return;busy.value=true;try{progress.value=await api(`/novels/${props.source.id}/analysis${resume?'/resume':''}`,{method:'POST',body:JSON.stringify({confirmed:true,profile:profile.value})});emit('message',progress.value.status==='SUCCEEDED'?'小说分析已完成':'分析保留了失败块，可单独继续');emit('refresh')}catch(error){emit('message',error.message,true)}finally{busy.value=false}}
async function confirmEntity(item){try{await api(`/novels/${props.source.id}/entity-candidates/${item.id}/confirm`,{method:'POST',body:'{}'});emit('message','实体已人工确认');emit('refresh')}catch(error){emit('message',error.message,true)}}
watch(()=>props.source?.id,load);onMounted(load)
</script>
<template><section class="panel" v-if="source"><div class="timeline-head"><h3>小说分析</h3><span class="pill">{{progress?.globalGraph||'NOT_STARTED'}}</span></div><p v-if="estimate">{{estimate.chunks}} 个语义块 · 约 {{estimate.estimatedInputTokens}} 输入 tokens · 估算 {{estimate.approxCost}} {{estimate.currency}}</p><label>分析档位<select v-model="profile"><option value="FAST">快速：摘要与主要实体</option><option value="STANDARD">标准：事实、知识和关系</option><option value="DEEP">深入：时间线、伏笔与人物弧</option></select></label><div class="button-row"><button class="primary" :disabled="busy" @click="start(false)">明确开始分析</button><button :disabled="busy||!progress?.failedChunks" @click="start(true)">只继续失败块</button></div><div v-if="progress"><p>章节解析 {{progress.parsedChapters}} / {{progress.totalChapters}}</p><p>语义分块 {{progress.semanticChunks}} / {{progress.totalChunks}}</p><p>Chunk 分析 {{progress.succeededChunks}} / {{progress.totalChunks}} <span v-if="progress.failedChunks">· 失败 {{progress.failedChunks}}</span></p><p>Chapter 汇总 {{progress.chapterSummaries}} / {{progress.totalChapters}} · Story Arc {{progress.storyArcs}}</p></div><div v-if="reviews.length"><h4>需要人工确认的实体</h4><div class="job" v-for="item in reviews" :key="item.id"><b>{{item.entityKind}} · {{item.canonicalName}}</b><span>置信度 {{Math.round(item.confidence*100)}}%</span><button class="tiny" @click="confirmEntity(item)">确认归并</button></div></div></section></template>
