<script setup>
import { computed, ref } from 'vue'
import NovelChapters from './NovelChapters.vue'
import NovelAnalysis from './NovelAnalysis.vue'
import { StreamingSha256 } from '../sha256.js'
const props=defineProps({project:Object,workspace:Object})
const emit=defineEmits(['refresh','message'])
const file=ref(null),session=ref(null),busy=ref(false),paused=ref(false),progress=ref(0)
const sources=computed(()=>props.workspace?.['novel-sources']||[]),source=computed(()=>sources.value.at(-1)),chapters=computed(()=>source.value?(props.workspace?.['novel-chapters']||[]).filter(item=>item.novelId===source.value.id):[])
const partSize=4*1024*1024
async function json(path,options={}){const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const body=await response.json();if(!response.ok)throw new Error(body.message||'操作失败');return body}
async function shaBlob(blob){const hash=new StreamingSha256();for(let offset=0;offset<blob.size;offset+=partSize)hash.update(new Uint8Array(await blob.slice(offset,offset+partSize).arrayBuffer()));return hash.hex()}
function select(event){file.value=event.target.files?.[0]||null;progress.value=0;session.value=null}
async function start(){if(!file.value||!props.project)return;busy.value=true;paused.value=false;try{const selected=file.value,format=selected.name.split('.').at(-1)?.toUpperCase();if(!['TXT','DOCX','EPUB'].includes(format))throw new Error('仅支持 TXT、DOCX、EPUB');const fullHash=await shaBlob(selected),total=Math.ceil(selected.size/partSize),key=`novel-upload:${props.project.id}:${selected.name}:${selected.size}:${fullHash}`;let currentId=localStorage.getItem(key);if(currentId){try{session.value=await json(`/novels/uploads/${currentId}`)}catch{localStorage.removeItem(key);currentId=''}}if(!currentId){session.value=await json('/novels/uploads',{method:'POST',body:JSON.stringify({projectId:props.project.id,fileName:selected.name,fileSize:selected.size,format,contentType:selected.type||'application/octet-stream',partSize,totalParts:total,fileSha256:fullHash})});localStorage.setItem(key,session.value.id)}await sendMissing(selected);if(!paused.value){const completed=await json(`/novels/uploads/${session.value.id}/complete`,{method:'POST',body:'{}'});progress.value=100;localStorage.removeItem(key);emit('message',`《${completed.title}》已解析，共 ${completed.chapterCount} 章`);emit('refresh')}}catch(error){emit('message',error.message,true)}finally{busy.value=false}}
async function sendMissing(selected){for(const partNo of session.value.missingParts||[]){if(paused.value)return;const start=(partNo-1)*partSize,blob=selected.slice(start,Math.min(selected.size,start+partSize)),hash=await shaBlob(blob),form=new FormData();form.append('file',blob,selected.name);const response=await fetch(`/api/novels/uploads/${session.value.id}/parts/${partNo}`,{method:'PUT',headers:{'X-Part-SHA256':hash},body:form});const body=await response.json();if(!response.ok)throw new Error(body.message||`第 ${partNo} 片上传失败`);session.value=body;progress.value=Math.round((body.receivedParts/body.totalParts)*100)}}
async function cancel(){if(!session.value)return;try{await json(`/novels/uploads/${session.value.id}/cancel`,{method:'POST',body:'{}'});session.value=null;progress.value=0;emit('message','上传已取消')}catch(error){emit('message',error.message,true)}}
</script>
<template><main class="workspace"><aside class="panel"><span class="eyebrow">小说导入</span><h2>分片上传与断点续传</h2><p>原始文件按 4MB 分片保存，刷新后只补传缺失部分。解析过程不会调用模型。</p><label class="upload">选择或拖入 TXT / DOCX / EPUB<input type="file" accept=".txt,.docx,.epub,text/plain,application/epub+zip" @change="select"/></label><p v-if="file">{{file.name}} · {{(file.size/1024/1024).toFixed(2)}} MB</p><progress :value="progress" max="100"/><div class="button-row"><button class="primary" :disabled="busy||!file||!project" @click="start">{{session?'继续上传':'开始导入'}}</button><button :disabled="!busy" @click="paused=true">暂停</button><button :disabled="!session" @click="cancel">取消</button></div></aside><section><div v-if="source" class="panel"><span class="eyebrow">{{source.status}}</span><h3>{{source.title}}</h3><p>{{source.fileName}} · {{source.totalCharacters}} 字 · {{source.chapterCount}} 章 · {{source.encoding}}</p><small>文件哈希：{{source.fileHash}}</small></div><div v-else class="panel"><p class="muted">上传完成后显示书名、字数、章节和编码。</p></div><NovelChapters :source="source" :chapters="chapters" @changed="emit('refresh')" @message="(...args)=>emit('message',...args)"/><NovelAnalysis v-if="source" :source="source" :workspace="workspace" @refresh="emit('refresh')" @message="(...args)=>emit('message',...args)"/></section></main></template>
