<script setup>
import { computed, ref } from 'vue'
const props=defineProps({source:Object,chapters:Array})
const emit=defineEmits(['changed','message'])
const editing=ref(''),title=ref('')
const ordered=computed(()=>[...(props.chapters||[])].sort((a,b)=>(a.displayOrder??a.chapterNo)-(b.displayOrder??b.chapterNo)))
async function save(chapter){try{const response=await fetch(`/api/novels/chapters/${chapter.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:chapter.revision,title:title.value.trim()})});const body=await response.json();if(!response.ok)throw new Error(body.message||'章节修改失败');editing.value='';emit('changed');emit('message','章节名已保存')}catch(error){emit('message',error.message,true)}}
async function request(path,body){try{const response=await fetch('/api'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.message||'章节修改失败');emit('changed');emit('message','章节结构已更新')}catch(error){emit('message',error.message,true)}}
function split(chapter){const offset=Number(prompt(`在正文第几个字符处拆分？当前共 ${chapter.charCount} 字`,Math.floor(chapter.charCount/2)));if(!Number.isInteger(offset))return;const nextTitle=prompt('新章节名称',`${chapter.title}（下）`);if(!nextTitle)return;request(`/novels/chapters/${chapter.id}/split`,{revision:chapter.revision,offset,title:nextTitle})}
function merge(chapter,index){const next=ordered.value[index+1];if(next&&confirm(`确认把“${next.title}”合并到“${chapter.title}”？`))request(`/novels/chapters/${chapter.id}/merge/${next.id}`,{revision:chapter.revision})}
async function move(index,delta){const list=[...ordered.value],target=index+delta;if(target<0||target>=list.length)return;[list[index],list[target]]=[list[target],list[index]];try{const response=await fetch(`/api/novels/${props.source.id}/chapters/order`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({chapterIds:list.map(item=>item.id)})}),body=await response.json();if(!response.ok)throw new Error(body.message||'排序失败');emit('changed');emit('message','章节顺序已保存')}catch(error){emit('message',error.message,true)}}
</script>
<template><section class="panel"><div class="timeline-head"><h3>章节列表</h3><span class="pill">解析修订 {{source?.parsingRevision||1}}</span></div><p v-if="!ordered.length" class="muted">完成解析后显示章节。</p><div v-for="(chapter,index) in ordered" :key="chapter.id" class="job"><template v-if="editing===chapter.id"><input v-model="title"/><button class="tiny" :disabled="!title.trim()" @click="save(chapter)">保存</button><button class="tiny" @click="editing=''">取消</button></template><template v-else><b>{{chapter.chapterNo}} · {{chapter.title}}</b><span>{{chapter.charCount}} 字</span><small>{{chapter.synthetic?'系统合成章节':'识别到的章节'}} · {{chapter.contentHash?.slice(0,10)}}</small><div class="button-row"><button class="tiny" @click="editing=chapter.id;title=chapter.title">改名</button><button class="tiny" @click="split(chapter)">拆分</button><button class="tiny" :disabled="index===ordered.length-1" @click="merge(chapter,index)">合并下一章</button><button class="tiny" :disabled="index===0" @click="move(index,-1)">上移</button><button class="tiny" :disabled="index===ordered.length-1" @click="move(index,1)">下移</button></div></template></div></section></template>
