<script setup>
import { computed, ref, watch } from 'vue'
import ImpactPanel from './ImpactPanel.vue'
const props=defineProps({project:Object,workspace:Object,busy:Boolean})
const emit=defineEmits(['refresh','message'])
const episodes=computed(()=>props.workspace?.episodes||[]),selectedEpisodeId=ref(''),version=ref(null),history=ref([]),draft=ref(null),diff=ref(null),loading=ref(false),importing=ref(false),sourceTrace=ref(null)
async function api(path,options={}){const headers=options.body instanceof FormData?{}:{'Content-Type':'application/json'};const response=await fetch('/api'+path,{...options,headers:{...headers,...(options.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body.message||'操作失败');return body}
async function load(){if(!selectedEpisodeId.value){version.value=null;sourceTrace.value=null;return}loading.value=true;try{version.value=await api(`/episodes/${selectedEpisodeId.value}/script`);draft.value=structuredClone(version.value);history.value=(await api(`/projects/${props.project.id}/scripts`)).filter(item=>item.episodeId===selectedEpisodeId.value).sort((a,b)=>b.version-a.version);sourceTrace.value=version.value?.id?await api(`/script-versions/${version.value.id}/source-trace`):null;diff.value=null}catch(error){emit('message',error.message,true)}finally{loading.value=false}}
watch(episodes,list=>{if(!selectedEpisodeId.value&&list.length)selectedEpisodeId.value=list[0].id},{immediate:true});watch(selectedEpisodeId,load);watch(()=>props.project?.id,()=>{selectedEpisodeId.value=episodes.value[0]?.id||'';load()})
async function fork(){try{version.value=await api(`/episodes/${selectedEpisodeId.value}/script/fork`,{method:'POST',body:JSON.stringify({revision:version.value.revision,createdBy:'USER'})});draft.value=structuredClone(version.value);await load();emit('message','已创建新的编辑草稿')}catch(error){emit('message',error.message,true)}}
async function save(){try{version.value=await api(`/script-versions/${version.value.id}`,{method:'PUT',body:JSON.stringify({...draft.value,status:'REVIEW'})});draft.value=structuredClone(version.value);emit('message','草稿已保存');await load()}catch(error){emit('message',error.message,true)}}
async function compare(){if(history.value.length<2)return;try{diff.value=await api(`/script-versions/${history.value[1].id}/diff/${history.value[0].id}`)}catch(error){emit('message',error.message,true)}}
async function confirm(){try{version.value=await api(`/script-versions/${version.value.id}/confirm`,{method:'POST',body:JSON.stringify({revision:version.value.revision})});emit('message','剧本已确认，可以进入生产准备');emit('refresh');await load()}catch(error){emit('message',error.message,true)}}
async function rollback(item){try{version.value=await api(`/script-versions/${item.id}/rollback`,{method:'POST',body:JSON.stringify({createdBy:'USER'})});draft.value=structuredClone(version.value);emit('message','已从历史版本创建回滚草稿');await load()}catch(error){emit('message',error.message,true)}}
async function importScript(event){const file=event.target.files?.[0];if(!file)return;const format=file.name.toLowerCase().endsWith('.docx')?'DOCX':file.name.toLowerCase().endsWith('.txt')?'TXT':'';if(!format){emit('message','仅支持 TXT 或 DOCX 剧本',true);event.target.value='';return}importing.value=true;try{const form=new FormData();form.append('file',file);const result=await api(`/projects/${props.project.id}/script-import?format=${format}`,{method:'POST',body:form});emit('message',result.status==='IMPORT_REVIEW_REQUIRED'?'剧本已导入，有未识别内容需要人工复核':'剧本已导入并建立待审版本');emit('refresh')}catch(error){emit('message',error.message,true)}finally{importing.value=false;event.target.value=''}}
const actionText=scene=>(scene.actions||[]).map(item=>typeof item==='string'?item:item.text||'').filter(Boolean).join('\n')
function setActions(scene,value){scene.actions=value.split('\n').filter(Boolean).map(text=>({text,sourceType:'HUMAN_EDITED'}))}
const editable=computed(()=>['DRAFT','REVIEW'].includes(version.value?.status))
const importReviewRequired=computed(()=>draft.value?.structuredContent?.importStatus==='IMPORT_REVIEW_REQUIRED')
function markImportReviewed(){draft.value.structuredContent.importStatus='REVIEWED'}
</script>

<template>
<main class="workspace script-workspace">
  <aside class="panel"><span class="eyebrow">剧本工作台 · {{project?.sourceMode||'IDEA'}}</span><h2>先审剧本，再进入生产</h2><label v-if="project?.sourceMode==='SCRIPT'" class="upload">上传 TXT / DOCX 剧本<input type="file" accept=".txt,.docx,text/plain,application/vnd.openxmlformats-officedocument.wordprocessingml.document" :disabled="importing" @change="importScript"/><small>{{importing?'正在解析…':'导入后生成可编辑的待审版本；未识别内容会明确标记。'}}</small></label><button v-for="episode in episodes" :key="episode.id" :class="{active:selectedEpisodeId===episode.id}" @click="selectedEpisodeId=episode.id">第 {{episode.episodeNo}} 集 · {{episode.name}}<small>{{episode.scriptReviewStatus||'待建立版本'}}</small></button></aside>
  <section class="panel" v-if="draft"><div class="timeline-head"><div><span class="eyebrow">版本 {{draft.version}}</span><h3>{{draft.structuredContent.title}}</h3></div><span class="pill">{{draft.status}}</span></div>
    <label>集标题<input v-model="draft.structuredContent.title" :disabled="!editable"/></label><label>摘要<textarea v-model="draft.structuredContent.summary" :disabled="!editable" rows="3"/></label><label>开场 Hook<textarea v-model="draft.structuredContent.openingHook" :disabled="!editable" rows="2"/></label>
    <div v-if="importReviewRequired" class="error"><p>导入内容中有未识别段落，请逐场复核并补齐后再确认。</p><button :disabled="!editable" @click="markImportReviewed">我已完成人工复核</button></div><article v-for="(scene,index) in draft.structuredContent.scenes" :key="scene.sceneKey||index" class="panel"><span class="eyebrow">Scene {{index+1}} · {{scene.sourceType||'UNKNOWN'}}</span><label>场景标题<input v-model="scene.title" :disabled="!editable"/></label><label>场景描述<textarea v-model="scene.description" :disabled="!editable"/></label><label>动作（每行一条）<textarea :value="actionText(scene)" :disabled="!editable" @input="setActions(scene,$event.target.value)"/></label><div v-for="(line,lineIndex) in scene.dialogues||[]" :key="line.lineKey||lineIndex" class="form-row"><label>人物<input :value="line.character||line.speakerName" :disabled="!editable" @input="line.character=$event.target.value;line.speakerName=$event.target.value"/></label><label>对白<input v-model="line.text" :disabled="!editable||line.ownership==='HUMAN_LOCKED'"/></label><label>来源类型<select v-model="line.sourceType" :disabled="!editable"><option>ORIGINAL_QUOTE</option><option>ADAPTED</option><option>AI_CREATED</option></select></label><label>内容归属<select v-model="line.ownership" :disabled="!editable"><option>AI_GENERATED</option><option>HUMAN_EDITED</option><option>HUMAN_LOCKED</option></select></label></div></article>
    <label>结尾 Hook<textarea v-model="draft.structuredContent.endingHook" :disabled="!editable" rows="2"/></label><div class="button-row"><button v-if="!editable" @click="fork">创建编辑版本</button><button v-if="editable" @click="save">保存草稿</button><button @click="compare">比较版本</button><button v-if="editable" class="primary" :disabled="importReviewRequired" @click="confirm">确认剧本</button></div>
  </section><section v-else class="panel"><p>{{loading?'正在读取剧本…':'请选择一集'}}</p></section>
  <aside class="panel"><h3>版本历史</h3><div v-for="item in history" :key="item.id" class="job"><b>v{{item.version}}</b><span>{{item.status}}</span><small>{{item.changeSummary}}</small><button class="tiny" @click="rollback(item)">回滚此版本</button></div><details v-if="sourceTrace"><summary>查看内容来源</summary><small>改编计划：{{sourceTrace.adaptationPlan?.id||'无'}}</small><small>来源章节：{{sourceTrace.novelChapters?.length||0}} · 来源片段：{{sourceTrace.novelChunks?.length||0}}</small><p v-for="chapter in sourceTrace.novelChapters||[]" :key="chapter.id">{{chapter.title||chapter.name||chapter.id}}</p></details><template v-if="diff"><h3>版本差异</h3><p>{{diff.humanReadableSummary}}</p><small>字段：{{diff.changedFields?.join('、')||'无'}}</small><small>对白：{{diff.changedDialogues?.join('、')||'无'}}</small><small>动作：{{diff.changedActions?.join('、')||'无'}}</small></template><ImpactPanel :versions="history" :episode="episodes.find(item=>item.id===selectedEpisodeId)" @message="(...args)=>emit('message',...args)"/></aside>
</main>
</template>
