<script setup>
import { computed, ref, watch } from 'vue'
import ImpactPanel from './ImpactPanel.vue'
const props=defineProps({project:Object,workspace:Object,busy:Boolean})
const emit=defineEmits(['refresh','message'])
const episodes=computed(()=>props.workspace?.episodes||[]),selectedEpisodeId=ref(''),version=ref(null),history=ref([]),draft=ref(null),diff=ref(null),loading=ref(false)
async function api(path,options={}){const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});const body=await response.json();if(!response.ok)throw new Error(body.message||'操作失败');return body}
async function load(){if(!selectedEpisodeId.value){version.value=null;return}loading.value=true;try{version.value=await api(`/episodes/${selectedEpisodeId.value}/script`);draft.value=structuredClone(version.value);history.value=(await api(`/projects/${props.project.id}/scripts`)).filter(item=>item.episodeId===selectedEpisodeId.value).sort((a,b)=>b.version-a.version);diff.value=null}catch(error){emit('message',error.message,true)}finally{loading.value=false}}
watch(episodes,list=>{if(!selectedEpisodeId.value&&list.length)selectedEpisodeId.value=list[0].id},{immediate:true});watch(selectedEpisodeId,load);watch(()=>props.project?.id,()=>{selectedEpisodeId.value=episodes.value[0]?.id||'';load()})
async function fork(){try{version.value=await api(`/episodes/${selectedEpisodeId.value}/script/fork`,{method:'POST',body:JSON.stringify({revision:version.value.revision,createdBy:'USER'})});draft.value=structuredClone(version.value);await load();emit('message','已创建新的编辑草稿')}catch(error){emit('message',error.message,true)}}
async function save(){try{version.value=await api(`/script-versions/${version.value.id}`,{method:'PUT',body:JSON.stringify({...draft.value,status:'REVIEW'})});draft.value=structuredClone(version.value);emit('message','草稿已保存');await load()}catch(error){emit('message',error.message,true)}}
async function compare(){if(history.value.length<2)return;try{diff.value=await api(`/script-versions/${history.value[1].id}/diff/${history.value[0].id}`)}catch(error){emit('message',error.message,true)}}
async function confirm(){try{version.value=await api(`/script-versions/${version.value.id}/confirm`,{method:'POST',body:JSON.stringify({revision:version.value.revision})});emit('message','剧本已确认，可以进入生产准备');emit('refresh');await load()}catch(error){emit('message',error.message,true)}}
async function rollback(item){try{version.value=await api(`/script-versions/${item.id}/rollback`,{method:'POST',body:JSON.stringify({createdBy:'USER'})});draft.value=structuredClone(version.value);emit('message','已从历史版本创建回滚草稿');await load()}catch(error){emit('message',error.message,true)}}
const editable=computed(()=>['DRAFT','REVIEW'].includes(version.value?.status))
</script>

<template>
<main class="workspace script-workspace">
  <aside class="panel"><span class="eyebrow">剧本工作台</span><h2>先审剧本，再进入生产</h2><button v-for="episode in episodes" :key="episode.id" :class="{active:selectedEpisodeId===episode.id}" @click="selectedEpisodeId=episode.id">第 {{episode.episodeNo}} 集 · {{episode.name}}<small>{{episode.scriptReviewStatus||'待建立版本'}}</small></button></aside>
  <section class="panel" v-if="draft"><div class="timeline-head"><div><span class="eyebrow">版本 {{draft.version}}</span><h3>{{draft.structuredContent.title}}</h3></div><span class="pill">{{draft.status}}</span></div>
    <label>集标题<input v-model="draft.structuredContent.title" :disabled="!editable"/></label><label>摘要<textarea v-model="draft.structuredContent.summary" :disabled="!editable" rows="3"/></label><label>开场 Hook<textarea v-model="draft.structuredContent.openingHook" :disabled="!editable" rows="2"/></label>
    <article v-for="(scene,index) in draft.structuredContent.scenes" :key="scene.sceneKey||index" class="panel"><span class="eyebrow">Scene {{index+1}}</span><label>场景标题<input v-model="scene.title" :disabled="!editable"/></label><label>场景描述<textarea v-model="scene.description" :disabled="!editable"/></label><label>动作（每行一条）<textarea :value="(scene.actions||[]).join('\n')" :disabled="!editable" @input="scene.actions=$event.target.value.split('\n').filter(Boolean)"/></label><div v-for="(line,lineIndex) in scene.dialogues||[]" :key="line.lineKey||lineIndex" class="form-row"><label>人物<input v-model="line.character" :disabled="!editable"/></label><label>对白<input v-model="line.text" :disabled="!editable||line.ownership==='HUMAN_LOCKED'"/></label><label>内容归属<select v-model="line.ownership" :disabled="!editable"><option>AI_GENERATED</option><option>HUMAN_EDITED</option><option>HUMAN_LOCKED</option></select></label></div></article>
    <label>结尾 Hook<textarea v-model="draft.structuredContent.endingHook" :disabled="!editable" rows="2"/></label><div class="button-row"><button v-if="!editable" @click="fork">创建编辑版本</button><button v-if="editable" @click="save">保存草稿</button><button @click="compare">比较版本</button><button v-if="editable" class="primary" @click="confirm">确认剧本</button></div>
  </section><section v-else class="panel"><p>{{loading?'正在读取剧本…':'请选择一集'}}</p></section>
  <aside class="panel"><h3>版本历史</h3><div v-for="item in history" :key="item.id" class="job"><b>v{{item.version}}</b><span>{{item.status}}</span><small>{{item.changeSummary}}</small><button class="tiny" @click="rollback(item)">回滚此版本</button></div><template v-if="diff"><h3>版本差异</h3><p>{{diff.humanReadableSummary}}</p><small>字段：{{diff.changedFields?.join('、')||'无'}}</small><small>对白：{{diff.changedDialogues?.join('、')||'无'}}</small><small>动作：{{diff.changedActions?.join('、')||'无'}}</small></template><ImpactPanel :versions="history" :episode="episodes.find(item=>item.id===selectedEpisodeId)" @message="(...args)=>emit('message',...args)"/></aside>
</main>
</template>
