<script setup>
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue'
import RecursiveFields from './RecursiveFields.vue'
import { canConfirmStory, premiseReviewActions } from '../ui-policy.js'

const props = defineProps({ project: Object, workspace: Object, busy: Boolean })
const emit = defineEmits(['refresh', 'message', 'editing'])
onBeforeUnmount(() => emit('editing', false))
const stage = ref('STORY_BRIEF')
const selectedId = ref('')
const draft = ref(null)
const saving = ref(false)
const batchSize = ref(5)
const dirty = ref(false)
const syncing = ref(false)
const draftRevision = ref(null)
const draftDocumentId = ref(null)
const showHistory = ref(false)
const editReason = ref('')
const editNote = ref('')
const editReasons = [['HOOK_WEAK','开场钩子弱'],['CONFLICT_WEAK','冲突不足'],['NO_PROGRESS','剧情没有推进'],['REPETITIVE_PATTERN','情节重复'],['DIALOGUE_TOO_AI','对白生硬'],['TOO_VERBOSE','内容冗长'],['CHARACTER_OUT_OF_VOICE','人物说话不对'],['CHARACTER_OUT_OF_BEHAVIOR','人物行为不对'],['CONTINUITY_ERROR','连续性错误'],['GENRE_MISMATCH','类型不符'],['CLIFFHANGER_WEAK','结尾钩子弱'],['VISUAL_MISMATCH','视觉不符'],['EDITING_RHYTHM','节奏问题'],['OTHER','其他']]
watch([dirty, saving], ([isDirty, isSaving]) => emit('editing', Boolean(isDirty || isSaving)), { immediate: true })

const docs = computed(() => props.workspace?.['story-documents'] || [])
const jobs = computed(() => props.workspace?.jobs || [])
const core = computed(() => {
  const active = props.workspace?.project?.activeStoryDocumentId
  return docs.value.find(d => d.id === active) || docs.value.find(d => d.documentType === 'CORE') || null
})
const coreDocuments = computed(() => docs.value.filter(d => d.documentType === 'CORE').sort((a, b) => (a.version || 0) - (b.version || 0)))
const activeCoreId = computed(() => core.value?.id || props.workspace?.project?.activeStoryDocumentId || '')
const briefDocuments = computed(() => docs.value.filter(d => d.documentType === 'STORY_BRIEF' && (!activeCoreId.value || d.coreId === activeCoreId.value)).sort((a, b) => (a.version || 0) - (b.version || 0)))
const briefs = computed(() => showHistory.value ? briefDocuments.value : briefDocuments.value.filter(d => !d.stale))
const outlineDocuments = computed(() => docs.value.filter(d => d.documentType === 'OUTLINE_BATCH' && (!activeCoreId.value || d.coreId === activeCoreId.value)).sort((a, b) => (a.batchNo || 0) - (b.batchNo || 0)))
const scriptDocuments = computed(() => docs.value.filter(d => d.documentType === 'EPISODE_SCRIPT' && (!activeCoreId.value || d.coreId === activeCoreId.value)).sort((a, b) => (a.episodeNo || 0) - (b.episodeNo || 0)))
const outlines = computed(() => showHistory.value ? outlineDocuments.value : outlineDocuments.value.filter(d => !d.stale))
const scripts = computed(() => showHistory.value ? scriptDocuments.value : scriptDocuments.value.filter(d => !d.stale))
const currentList = computed(() => stage.value === 'STORY_BRIEF' ? briefs.value : stage.value === 'CORE' ? (showHistory.value ? coreDocuments.value : coreDocuments.value.filter(d => !d.stale && (!core.value || d.id === core.value.id))) : stage.value === 'OUTLINE_BATCH' ? outlines.value : scripts.value)
const selected = computed(() => currentList.value.find(d => d.id === selectedId.value) || currentList.value[0] || null)
const selectedJob = computed(() => { const id = ['QA_PENDING', 'QA_FAILED'].includes(selected.value?.reviewStatus) ? selected.value?.qaJobId : selected.value?.generationJobId; return id ? jobs.value.find(j => j.id === id) : null })
const premiseActions = computed(() => premiseReviewActions(selected.value))
const confirmAllowed = computed(() => canConfirmStory(selected.value, dirty.value))
const statusText = s => ({ PREMISE_ANALYSIS: '前提分析中', PREMISE_PASSED: '前提已通过', PREMISE_REVIEW_REQUIRED: '前提需处理', GENERATING: '生成中', QA_PENDING: '故事质检中', QA_FAILED: '故事质检失败', REVIEW: '待确认', CONFIRMED: '已确认', FAILED: '失败', STALE: '需要更新', WAITING: '等待生成' }[s] || s || '未知')
const statusClass = s => ({ PREMISE_ANALYSIS: 'busy', PREMISE_PASSED: 'good', PREMISE_REVIEW_REQUIRED: 'failed', GENERATING: 'busy', QA_PENDING: 'busy', REVIEW: 'review', CONFIRMED: 'good', QA_FAILED: 'failed', FAILED: 'failed', STALE: 'stale', WAITING: 'waiting' }[s] || 'waiting')
const documentStatusText = doc => { if (doc.stale) return '需要更新'; if (!['GENERATING', 'QA_PENDING'].includes(doc.reviewStatus)) return statusText(doc.reviewStatus); const jobId = doc.reviewStatus === 'QA_PENDING' ? doc.qaJobId : doc.generationJobId; const job = jobId ? jobs.value.find(j => j.id === jobId) : null; return job?.status === 'QUEUED' ? '排队中' : job?.status === 'SUCCESS' ? (doc.reviewStatus === 'QA_PENDING' ? '故事质检完成' : '待确认') : statusText(doc.reviewStatus) }
const documentStatusClass = doc => doc.stale ? 'stale' : documentStatusText(doc) === '待确认' ? 'review' : statusClass(doc.reviewStatus)
const jobTiming = job => { if (job?.status === 'SUCCESS') return '生成已完成'; if (['FAILED', 'CANCELLED'].includes(job?.status)) return '已停止'; const stamp = job?.startedAt || job?.createdAt; if (!stamp) return ''; const minutes = Math.max(0, Math.floor((Date.now() - new Date(stamp).getTime()) / 60000)); return minutes ? `${job?.status === 'QUEUED' ? '已排队' : '已执行'} ${minutes} 分钟` : '刚刚开始' }
const jobStatusText = s => ({ QUEUED: '排队中', RUNNING: '处理中', SUCCESS: '已完成', FAILED: '失败', CANCELLED: '已取消', RETRY_WAIT: '等待重试' }[s] || s || '未知')
const clone = value => value == null ? {} : JSON.parse(JSON.stringify(value))
const syncDraft = async () => { syncing.value = true; draft.value = selected.value ? clone(selected.value.content) : null; draftRevision.value = selected.value?.revision ?? null; draftDocumentId.value = selected.value?.id || null; dirty.value = false; editReason.value=''; editNote.value=''; await nextTick(); syncing.value = false }
watch(draft, () => { if (!syncing.value) dirty.value = true }, { deep: true })
watch([() => selected.value?.id, stage], () => { if (!dirty.value) syncDraft() }, { immediate: true })
watch(currentList, () => { if (dirty.value) return; if (!currentList.value.some(d => d.id === selectedId.value)) selectedId.value = currentList.value[0]?.id || ''; syncDraft() })
watch(() => props.project?.id, () => { if (dirty.value || saving.value) return; dirty.value = false; selectedId.value = ''; draft.value = null; draftDocumentId.value = null })

const textFields = {
  title: '标题', logline: '一句话梗概',
  summary: '内容摘要', script: '剧本正文', startState: '开场状态', endState: '结尾状态',
  originalIdea: '原始创意', goal: '故事目标', coreConflict: '核心冲突', failureCost: '失败代价', informationGap: '信息差', endingDirection: '结局方向'
}
const editableTextFields = computed(() => Object.fromEntries(Object.entries(textFields).filter(([key]) => draft.value && key in draft.value)))
const coreNestedLabels = { identityTraits: '身份特征', locationBible: '场景设定', propBible: '道具设定' }
const updateArrayItem = (key, index, patch) => { const next = clone(draft.value); next[key] = [...(next[key] || [])]; next[key][index] = { ...next[key][index], ...patch }; draft.value = next }
const addItem = key => { const next = clone(draft.value); next[key] = [...(next[key] || []), key === 'characters' ? { characterKey: `character-${Date.now()}`, name: '', description: '', narrativeBible:{storyRole:'',want:'',need:'',fear:'',weakness:'',secret:'',motivation:'',decisionPattern:'',arc:{start:'',turningPoints:[],end:''},speechStyle:'',behaviorRules:[],relationships:[]}, identityTraits: { age: '', face: '', hair: '', body: '', voiceDialect: '' }, looks: [{ lookKey: `look-${Date.now()}`, name: '', description: '' }] } : key === 'locations' ? { locationKey: `location-${Date.now()}`, name: '', description: '', locationBible: { layout: '', spatialAnchors: '', lighting: '' } } : { propKey: `prop-${Date.now()}`, name: '', description: '', state: '', propBible: { appearance: '', scale: '', ownership: '' } }]; draft.value = next }
const removeItem = (key, index) => { const next = clone(draft.value); next[key].splice(index, 1); draft.value = next }
const updateEpisode = (index, patch) => { const next = clone(draft.value); next.episodes[index] = { ...next.episodes[index], ...patch }; draft.value = next }
const referenceOptions = computed(() => ({ characters: core.value?.content?.characters || [], locations: core.value?.content?.locations || [], props: core.value?.content?.props || [] }))
const toggleEpisodeReference = (index, key, value, event) => { const current = draft.value?.episodes?.[index]?.[key] || []; updateEpisode(index, { [key]: event.target.checked ? [...current, value] : current.filter(item => item !== value) }) }
const toggleScriptReference = (key, value, event) => { const current = draft.value?.[key] || []; updateScript(key, event.target.checked ? [...current, value] : current.filter(item => item !== value)) }
const addEpisode = () => { const next = clone(draft.value); const format=props.project?.episodeFormat||{}; next.episodes = [...(next.episodes || []), { episodeNo: (next.episodes?.length || 0) + 1, title: '', episodeFunction:'',episodeGoal:'',hook:'',mainConflict:'',newInformation:'',characterDecision:'',escalation:'',payoff:'',cliffhanger:'',summary: '', startState: '', endState: '', characterKeys: [], locationKeys: [], propKeys: [],foreshadowing:{plant:[],advance:[],resolve:[]},episodeFormatId:format.profileId||'',beatMode:format.beatMode||'',beats:[],progressionEvents:[],estimatedDurationSec:format.targetDurationSec||props.project?.targetDuration||0,scenePlan: [] }]; draft.value = next }
const removeEpisode = index => { const next = clone(draft.value); next.episodes.splice(index, 1); draft.value = next }
const discard = () => syncDraft()
const updateScript = (key, value) => { draft.value = { ...draft.value, [key]: value } }
const updateScriptReferences = value => { draft.value = { ...draft.value, characterKeys: value.characterKeys || [], locationKeys: value.locationKeys || [], propKeys: value.propKeys || [] } }
const createCore = async () => { if (!props.project?.id) return; await request(`/projects/${props.project.id}/core`, 'POST', {}) }
const request = async (path, method, body) => { saving.value = true; try { const response = await fetch(`/api/story-development${path}`, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || '操作失败'); dirty.value = false; emit('message', method === 'PUT' ? '草稿已保存' : '操作已提交'); emit('refresh'); return data } catch (error) { emit('message', error.message, true); return null } finally { saving.value = false } }
const save = async () => { if (!selected.value || selected.value.stale || !dirty.value || !draftDocumentId.value) return; const data = await request(`/documents/${draftDocumentId.value}`, 'PUT', { revision: draftRevision.value, content: draft.value, reasonCodes:editReason.value?[editReason.value]:[], feedbackNote:editNote.value.trim() }); const newId = data?.id || data?.document?.id; if (newId) { selectedId.value = newId; draftDocumentId.value = newId; editReason.value=''; editNote.value='' } }
const confirm = () => { if (!confirmAllowed.value) { emit('message', dirty.value ? '请先保存草稿，再确认继续' : selected.value?.storyQa?.passed === false ? '故事质检仍有阻断问题，请先修改或定向改写' : '当前版本还不能确认', true); return } return request(`/documents/${selected.value.id}/confirm`, 'POST', { revision: draftRevision.value, ...(stage.value === 'CORE' ? { batchSize: Number(batchSize.value) } : {}) }) }
const rewrite = () => { if (!selected.value || dirty.value || !selected.value.storyQa?.rewriteRequired) return; return request(`/documents/${selected.value.id}/rewrite`, 'POST', { revision: draftRevision.value }) }
const premiseAction = action => { if (!selected.value) return; if (action === 'EDIT_IDEA') { const idea = window.prompt('修改一句话创意后重新评估', props.project?.idea || ''); if (!idea?.trim()) return; return request(`/documents/${selected.value.id}/premise`, 'POST', { action, idea: idea.trim(), reviewer: 'USER' }) } if (action === 'FORCE_CONTINUE') { const reason = window.prompt('说明为什么接受容量风险并继续（会写入审计记录）', ''); if (!reason?.trim()) return; return request(`/documents/${selected.value.id}/premise`, 'POST', { action, overrideBy: 'USER', overrideReason: reason.trim() }) } return request(`/documents/${selected.value.id}/premise`, 'POST', { action, reviewer: 'USER' }) }
const retry = () => { if (!selected.value || !['FAILED', 'QA_FAILED'].includes(selected.value.reviewStatus) || selectedJob.value?.submissionUncertain) return; return request(`/documents/${selected.value.id}/retry`, 'POST', {}) }
const selectDocument = id => { if (dirty.value) { emit('message', '请先保存当前草稿，再切换文档', true); return }; selectedId.value = id }
const selectStage = value => { if (dirty.value) { emit('message', '请先保存当前草稿，再切换阶段', true); return }; stage.value = value; selectedId.value = '' }
const confirmedCount = list => list.filter(d => d.reviewStatus === 'CONFIRMED').length
const totalBatches = computed(() => { const count = core.value?.projectSnapshot?.episodeCount || core.value?.content?.projectSnapshot?.episodeCount || props.project?.episodeCount || 0; const size = core.value?.batchSize || batchSize.value || 5; return count ? Math.ceil(count / size) : outlines.value.length })
const totalEpisodes = computed(() => core.value?.projectSnapshot?.episodeCount || core.value?.content?.projectSnapshot?.episodeCount || props.project?.episodeCount || scripts.value.length)
const coreContract = computed(()=>draft.value?Object.fromEntries(['storyProfile','emotionContract','storyEngine','worldRules','seasonArc','unitArcs','foreshadowingRules','continuityRules'].filter(k=>k in draft.value).map(k=>[k,draft.value[k]])):null)
const updateCoreContract=value=>{draft.value={...draft.value,...value}}
const episodeStructure=episode=>Object.fromEntries(['episodeFunction','episodeGoal','hook','mainConflict','newInformation','characterDecision','escalation','payoff','cliffhanger','foreshadowing','episodeFormatId','beatMode','beats','midHook','progressionEvents','estimatedDurationSec'].filter(k=>k in episode).map(k=>[k,episode[k]]))
const scriptStructure=computed(()=>draft.value?Object.fromEntries(['episodeFormatId','beatMode','targetDurationSec','beatBoundaries','midHook'].filter(k=>k in draft.value).map(k=>[k,draft.value[k]])):null)
const updateScriptStructure=value=>{draft.value={...draft.value,...value}}
</script>

<template>
  <main class="story-review workspace">
    <section class="sr-head">
      <div><span class="eyebrow">故事开发</span><h2>创作审查台</h2><p>创作需求、整季核心、分批集纲、单集剧本逐阶段确认；每一阶段都可修改、保存和断点续跑。</p></div>
      <div class="sr-legend"><span class="sr-state review">待确认</span><span class="sr-state good">已确认</span><span class="sr-state failed">失败</span><span class="sr-state stale">需要更新</span></div>
    </section>
    <section class="sr-steps">
      <button :class="{ active: stage === 'STORY_BRIEF' }" @click="selectStage('STORY_BRIEF')"><b>01</b><span>创作需求</span><small>{{ briefs.length ? documentStatusText(briefs[briefs.length - 1]) : '尚未创建' }}</small></button>
      <button :class="{ active: stage === 'CORE' }" @click="selectStage('CORE')"><b>02</b><span>整季核心</span><small>{{ core ? documentStatusText(core) : '等待创作需求确认' }}</small></button>
      <button :class="{ active: stage === 'OUTLINE_BATCH' }" @click="selectStage('OUTLINE_BATCH')"><b>03</b><span>分批集纲</span><small>{{ outlines.length || totalBatches ? `${confirmedCount(outlines)}/${totalBatches} 批已确认` : '等待核心确认' }}</small></button>
      <button :class="{ active: stage === 'EPISODE_SCRIPT' }" @click="selectStage('EPISODE_SCRIPT')"><b>04</b><span>单集剧本</span><small>{{ scripts.length ? `${confirmedCount(scripts)}/${totalEpisodes} 集已确认` : '等待集纲确认' }}</small></button>
    </section>
    <section v-if="stage === 'STORY_BRIEF' && !briefs.length" class="sr-empty panel"><h3>创建创作需求</h3><p>系统会先把原始想法整理为可审查的 StoryBrief；确认后才评估故事容量并生成整季核心。</p><button class="primary" :disabled="saving || !project?.id" @click="createCore">生成创作需求</button></section>
    <section v-else-if="stage === 'CORE' && !core" class="sr-empty panel"><h3>等待整季核心</h3><p>请先在“创作需求”中确认 StoryBrief。系统完成前提评估后会生成整季核心。</p></section>
    <section v-else class="sr-layout">
      <aside class="sr-list panel"><div class="sr-list-title"><h3>{{ stage === 'STORY_BRIEF' ? '需求版本' : stage === 'CORE' ? '核心版本' : stage === 'OUTLINE_BATCH' ? '集纲批次' : '剧本集数' }}</h3><span>{{ currentList.length }}</span></div><label class="sr-history"><input type="checkbox" v-model="showHistory" /> 查看旧版</label><button v-for="doc in currentList" :key="doc.id" class="sr-doc" :class="{ selected: selected?.id === doc.id }" @click="selectDocument(doc.id)"><div><b v-if="stage === 'STORY_BRIEF'">创作需求 v{{ doc.version || 1 }}</b><b v-else-if="stage === 'CORE'">核心 v{{ doc.version || 1 }}</b><b v-else-if="stage === 'OUTLINE_BATCH'">第 {{ doc.batchNo }} 批 · {{ doc.startEpisode }}—{{ doc.endEpisode }} 集</b><b v-else>第 {{ doc.episodeNo }} 集 · {{ doc.content?.title || '未命名' }}</b><span class="sr-state" :class="documentStatusClass(doc)">{{ documentStatusText(doc) }}</span></div><small>修订 {{ doc.revision || 0 }} · {{ doc.stale ? '旧版请回当前版本' : '当前版本' }}<template v-if="doc.generationJobId"> · {{ documentStatusText(doc) }}</template></small></button><div v-if="!currentList.length" class="sr-muted">暂时没有可审查文档</div></aside>
      <section v-if="selected" class="sr-editor panel">
        <header class="sr-editor-head"><div><span class="eyebrow">{{ stage === 'STORY_BRIEF' ? '创作需求' : stage === 'CORE' ? '整季核心' : stage === 'OUTLINE_BATCH' ? `第 ${selected.batchNo} 批` : `第 ${selected.episodeNo} 集` }}</span><h3>{{ stage === 'STORY_BRIEF' ? (draft?.title || 'StoryBrief') : stage === 'CORE' ? (draft?.title || '故事核心') : stage === 'OUTLINE_BATCH' ? `第 ${selected.batchNo} 批集纲` : (draft?.title || `第 ${selected.episodeNo} 集剧本`) }}</h3><details class="sr-meta"><summary>查看追踪信息</summary><span>文档 ID：{{ selected.id }} · 核心 ID：{{ selected.coreId || selected.id }} · 生成任务：{{ selected.generationJobId || '—' }} · 版本 v{{ selected.version || 1 }} · 修订 {{ selected.revision || 0 }}</span></details></div><span class="sr-state large" :class="documentStatusClass(selected)">{{ documentStatusText(selected) }}</span></header>
        <fieldset :disabled="selected.stale || ['PREMISE_ANALYSIS','GENERATING'].includes(selected.reviewStatus)" class="sr-fieldset"><div v-if="selected.stale" class="sr-alert">这是旧版内容，请回当前版本查看；旧版不可保存或确认。</div><div v-if="selected.qaFailureReason || selectedJob?.failureReason" class="sr-alert danger">{{ selected.qaFailureReason || selectedJob.failureReason }}<span v-if="selectedJob?.submissionUncertain"> · 提交状态不确定，请先核对服务商记录。</span></div><div v-if="selectedJob" class="sr-trace">任务状态：{{ jobStatusText(selectedJob.status) }} · {{ jobTiming(selectedJob) }}<template v-if="selectedJob.providerRequestId || selectedJob.providerTaskId"> · 服务商记录：{{ selectedJob.providerRequestId || '—' }} · {{ selectedJob.providerTaskId || '—' }}</template></div><div v-if="stage === 'CORE' && selected.premiseAnalysis" class="sr-validation" :class="{danger:!selected.premiseAnalysis.viable}"><b>前提门禁：{{selected.premiseAnalysis.viable?'容量可行':'存在扩展风险'}}</b><p>{{selected.premiseAnalysis.audiencePromise}}</p><p v-if="selected.premiseAnalysis.capacityRisk">容量风险：{{selected.premiseAnalysis.capacityRisk}}</p><p v-if="selected.premiseAnalysis.weaknesses?.length">弱点：{{selected.premiseAnalysis.weaknesses.join('；')}}</p><p v-if="selected.premiseAnalysis.questionsForCore?.length">CORE 必须回答：{{selected.premiseAnalysis.questionsForCore.join('；')}}</p><p v-if="selected.premiseAnalysis.recommendedAdjustments?.length">建议调整：{{selected.premiseAnalysis.recommendedAdjustments.join('；')}}</p><div v-if="premiseActions.length" class="sr-actions"><button v-if="premiseActions.includes('EDIT_IDEA')" @click="premiseAction('EDIT_IDEA')">修改创意并重评</button><button v-if="premiseActions.includes('ACCEPT_RECOMMENDATIONS')" @click="premiseAction('ACCEPT_RECOMMENDATIONS')">采纳建议继续</button><button v-if="premiseActions.includes('FORCE_CONTINUE')" class="danger-btn" @click="premiseAction('FORCE_CONTINUE')">说明原因后强制继续</button></div></div><div v-if="selected.validation" class="sr-validation">校验：{{ selected.validation.message || selected.validation.summary || '已执行' }} · {{ selected.validation.passed === true ? '通过' : selected.validation.passed === false ? '未通过' : (selected.validation.status || '待查看') }}</div><div v-if="selected.storyQa" class="sr-validation" :class="{danger:!selected.storyQa.passed}">故事质检：{{selected.storyQa.passed?'通过':'需要修改'}} · 开场 {{selected.storyQa.dimensions?.hook||0}} · 推进 {{selected.storyQa.dimensions?.progression||0}} · 对白 {{selected.storyQa.dimensions?.dialogueNaturalness||0}}<p v-if="selected.storyQa.blockingIssues?.length">阻断问题：{{selected.storyQa.blockingIssues.join('；')}}</p></div>
        <div v-if="stage === 'STORY_BRIEF' && draft" class="sr-fields"><label v-for="(label, key) in editableTextFields" :key="key">{{ label }}<textarea v-model="draft[key]" rows="3" /></label><label>受众、题材、角色范围、情绪承诺与制作约束<RecursiveFields :model-value="draft" @update:model-value="draft=$event" /></label></div>
        <div v-else-if="stage === 'CORE' && draft" class="sr-fields"><label v-for="(label, key) in editableTextFields" :key="key">{{ label }}<textarea v-model="draft[key]" rows="3" /></label><label>故事画像、情绪合同、剧情发动机与整季单元<RecursiveFields :model-value="coreContract" @update:model-value="updateCoreContract" /></label><div class="sr-array"><div class="sr-array-head"><h4>人物</h4><button class="tiny" @click="addItem('characters')">添加人物</button></div><article v-for="(item, index) in draft.characters || []" :key="index" class="sr-card"><div class="sr-grid-3"><label>人物标识<input :value="item.characterKey" readonly @input="updateArrayItem('characters', index, { characterKey: $event.target.value })" /></label><label>姓名<input :value="item.name" @input="updateArrayItem('characters', index, { name: $event.target.value })" /></label><label>简介<input :value="item.description" @input="updateArrayItem('characters', index, { description: $event.target.value })" /></label></div><label>叙事人物圣经<RecursiveFields :model-value="item.narrativeBible || {}" @update:model-value="updateArrayItem('characters', index, { narrativeBible: $event })" /></label><label>视觉身份特征<RecursiveFields :model-value="item.identityTraits || {}" :label-map="coreNestedLabels" @update:model-value="updateArrayItem('characters', index, { identityTraits: $event })" /></label><label>定妆<RecursiveFields :model-value="{ looks: item.looks || [] }" @update:model-value="updateArrayItem('characters', index, { looks: $event.looks || [] })" /></label><button class="tiny danger-btn" @click="removeItem('characters', index)">删除人物</button></article></div><div v-for="key in ['locations', 'props']" :key="key" class="sr-array"><div class="sr-array-head"><h4>{{ key === 'locations' ? '场景' : '道具' }}</h4><button class="tiny" @click="addItem(key)">添加{{ key === 'locations' ? '场景' : '道具' }}</button></div><article v-for="(item, index) in draft[key] || []" :key="index" class="sr-card"><div class="sr-grid-3"><label>标识<input :value="item[`${key === 'locations' ? 'location' : 'prop'}Key`]" readonly @input="updateArrayItem(key, index, { [key === 'locations' ? 'locationKey' : 'propKey']: $event.target.value })" /></label><label>名称<input :value="item.name" @input="updateArrayItem(key, index, { name: $event.target.value })" /></label><label v-if="key === 'props'">状态<input :value="item.state" @input="updateArrayItem(key, index, { state: $event.target.value })" /></label></div><label>描述<textarea :value="item.description" rows="2" @input="updateArrayItem(key, index, { description: $event.target.value })" /></label><label>{{ key === 'locations' ? '场景设定' : '道具设定' }}<RecursiveFields :model-value="item[key === 'locations' ? 'locationBible' : 'propBible'] || {}" @update:model-value="updateArrayItem(key, index, { [key === 'locations' ? 'locationBible' : 'propBible']: $event })" /></label><button class="tiny danger-btn" @click="removeItem(key, index)">删除{{ key === 'locations' ? '场景' : '道具' }}</button></article></div></div>
        <div v-else-if="stage === 'OUTLINE_BATCH'" class="sr-fields"><label v-for="(label, key) in editableTextFields" :key="key">{{ label }}<textarea v-model="draft[key]" rows="3" /></label><div class="sr-array"><div class="sr-array-head"><h4>本批集纲（{{ draft.episodes?.length || 0 }} 集）</h4><button class="tiny" @click="addEpisode">添加一集</button></div><article v-for="(episode, index) in draft.episodes || []" :key="index" class="sr-card"><div class="sr-grid-3"><label>集数<input type="number" :value="episode.episodeNo" @input="updateEpisode(index, { episodeNo: Number($event.target.value) })" /></label><label>标题<input :value="episode.title" @input="updateEpisode(index, { title: $event.target.value })" /></label><label>摘要<input :value="episode.summary" @input="updateEpisode(index, { summary: $event.target.value })" /></label></div><label>本集功能、推进、节拍与中段钩子<RecursiveFields :model-value="episodeStructure(episode)" @update:model-value="updateEpisode(index,$event)" /></label><div class="sr-grid-2"><label>开场状态<textarea :value="episode.startState" rows="2" @input="updateEpisode(index, { startState: $event.target.value })" /></label><label>结尾状态<textarea :value="episode.endState" rows="2" @input="updateEpisode(index, { endState: $event.target.value })" /></label></div><div class="sr-reference-groups"><div v-for="(group, groupKey) in referenceOptions" :key="groupKey"><b>{{ groupKey === 'characters' ? '人物' : groupKey === 'locations' ? '场景' : '道具' }}</b><label v-for="option in group" :key="option[`${groupKey === 'characters' ? 'character' : groupKey === 'locations' ? 'location' : 'prop'}Key`]" class="sr-check"><input type="checkbox" :checked="(episode[groupKey === 'characters' ? 'characterKeys' : groupKey === 'locations' ? 'locationKeys' : 'propKeys'] || []).includes(option[`${groupKey === 'characters' ? 'character' : groupKey === 'locations' ? 'location' : 'prop'}Key`])" @change="toggleEpisodeReference(index, groupKey === 'characters' ? 'characterKeys' : groupKey === 'locations' ? 'locationKeys' : 'propKeys', option[`${groupKey === 'characters' ? 'character' : groupKey === 'locations' ? 'location' : 'prop'}Key`], $event)" />{{ option.name }}</label></div></div><label>场景计划<RecursiveFields :model-value="{ scenePlan: episode.scenePlan || [] }" @update:model-value="updateEpisode(index, { scenePlan: $event.scenePlan || [] })" /></label><button class="tiny danger-btn" @click="removeEpisode(index)">删除本集</button></article></div></div>
        <div v-else-if="stage === 'EPISODE_SCRIPT'" class="sr-fields"><label v-for="(label, key) in editableTextFields" :key="key">{{ label }}<textarea v-model="draft[key]" :rows="key === 'script' ? 12 : 3" /></label><label>篇幅制式、节拍边界与中段钩子<RecursiveFields :model-value="scriptStructure" @update:model-value="updateScriptStructure" /></label><div class="sr-reference-groups"><div v-for="(group, groupKey) in referenceOptions" :key="groupKey"><b>{{ groupKey === 'characters' ? '人物' : groupKey === 'locations' ? '场景' : '道具' }}</b><label v-for="option in group" :key="option[`${groupKey === 'characters' ? 'character' : groupKey === 'locations' ? 'location' : 'prop'}Key`]" class="sr-check"><input type="checkbox" :checked="(draft[groupKey === 'characters' ? 'characterKeys' : groupKey === 'locations' ? 'locationKeys' : 'propKeys'] || []).includes(option[`${groupKey === 'characters' ? 'character' : groupKey === 'locations' ? 'location' : 'prop'}Key`])" @change="toggleScriptReference(groupKey === 'characters' ? 'characterKeys' : groupKey === 'locations' ? 'locationKeys' : 'propKeys', option[`${groupKey === 'characters' ? 'character' : groupKey === 'locations' ? 'location' : 'prop'}Key`], $event)" />{{ option.name }}</label></div></div><label v-if="draft.scenes">场景列表<RecursiveFields :model-value="{ scenes: draft.scenes }" @update:model-value="updateScript('scenes', $event.scenes || [])" /></label></div>
        </fieldset><div v-if="dirty" class="sr-feedback"><label>这次主要修改原因（可选）<select v-model="editReason"><option value="">不标记</option><option v-for="reason in editReasons" :key="reason[0]" :value="reason[0]">{{reason[1]}}</option></select></label><label>修改说明（可选）<input v-model="editNote" placeholder="例如：缩短对白，让人物更符合前文性格" /></label></div><footer class="sr-actions"><button v-if="dirty" :disabled="saving" @click="discard">放弃修改</button><button :disabled="saving || selected.stale || selected.reviewStatus === 'GENERATING'" @click="save">保存草稿</button><select v-if="stage === 'CORE'" v-model="batchSize" title="批次大小"><option :value="5">下一批 5 集</option><option :value="10">下一批 10 集</option></select><button v-if="stage === 'EPISODE_SCRIPT' && selected.storyQa?.rewriteRequired" :disabled="saving || selected.reviewStatus !== 'REVIEW' || selected.stale || dirty || (selected.rewriteAttempt || 0) >= 2" @click="rewrite">按质检定向改写</button><button class="primary" :disabled="saving || !confirmAllowed" @click="confirm">确认并继续</button><button v-if="['FAILED','QA_FAILED'].includes(selected.reviewStatus)" class="retry" :disabled="saving || selectedJob?.submissionUncertain || selected.stale" @click="retry">局部重试</button></footer>
      </section><section v-else class="sr-empty panel"><h3>选择一份文档</h3><p>左侧列表会显示当前阶段的文档。</p></section>
    </section>
  </main>
</template>








