package com.yourapp.drama.domain;
public enum JobType {
    STORY, SCRIPT, STORY_QA, DIRECTOR_PLAN, SHOT_DETAIL, STORYBOARD, KEYFRAME, KEYFRAME_QC,
    VIDEO, VIDEO_QC, TTS, LIPSYNC, TIMELINE, RENDER, ARCHIVE, ASSET_IMAGE
}
