package com.yourapp.drama.domain;
public enum ShotStatus {
    DRAFT, PLANNED, STORYBOARD_GENERATING, STORYBOARD_READY, STORYBOARD_LOCKED,
    KEYFRAME_GENERATING, KEYFRAME_READY, KEYFRAME_QC, KEYFRAME_LOCKED,
    VIDEO_GENERATING, VIDEO_READY, VIDEO_QC, VIDEO_LOCKED, AUDIO_READY, EDITED, FINISHED,
    FAILED, NEEDS_REPAIR, PROVIDER_URL_EXPIRED
}
