package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yourapp.drama.persistence.DocumentStore;
import com.yourapp.drama.persistence.ResourceKind;
import org.springframework.stereotype.Service;

import java.util.*;

import static com.yourapp.drama.persistence.ResourceKind.*;
import static com.yourapp.drama.workflow.Documents.*;

@Service
public class EpisodeAdaptationService {
    private final DocumentStore store;private final NovelAdaptationService adaptations;private final NovelAdaptationContextAssembler contexts;private final ScriptWorkspaceService scripts;private final DependencyRevisionService revisions;private final NovelEpisodeScreenwriter screenwriter;private final NovelScreenplayValidator validator;private final NovelIntelligenceRunService runs;
    public EpisodeAdaptationService(DocumentStore store,NovelAdaptationService adaptations,NovelAdaptationContextAssembler contexts,ScriptWorkspaceService scripts,DependencyRevisionService revisions,NovelEpisodeScreenwriter screenwriter,NovelScreenplayValidator validator,NovelIntelligenceRunService runs){this.store=store;this.adaptations=adaptations;this.contexts=contexts;this.scripts=scripts;this.revisions=revisions;this.screenwriter=screenwriter;this.validator=validator;this.runs=runs;}
    public ObjectNode generate(String planId,int episodeNo,ObjectNode request){
        ObjectNode plan=adaptations.requireConfirmed(planId),novel=store.get(NOVEL_SOURCE,required(plan,"novelId"));NovelIntelligenceRunService.Estimate estimate=estimate(1,request.path("contextBudgetChars").asInt(12000));return runs.execute(novel,"SCREENPLAY","EPISODE",request,false,estimate,()->generateInternal(plan,episodeNo,request));
    }
    private ObjectNode generateInternal(ObjectNode plan,int episodeNo,ObjectNode request){
        String planId=id(plan);ObjectNode episodePlan=adaptations.episodes(planId).stream().filter(e->e.path("episodeNo").asInt()==episodeNo).findFirst().orElseThrow(()->new IllegalArgumentException("分集不存在："+episodeNo));ObjectNode context=contexts.assemble(planId,episodeNo,request.path("contextBudgetChars").asInt(12000));String projectId=project(plan),adaptationContextHash=required(context,"contextHash");String generationContextHash=DependencyRevisionService.hash(obj().put("adaptationContextHash",adaptationContextHash).put("compilerVersion",NovelPromptCompiler.EPISODE_SCRIPT_VERSION).put("model",screenwriter.cacheIdentity()));Optional<ObjectNode> existing=store.list(EPISODE_SCRIPT_VERSION,projectId,null).stream().filter(v->id(episodePlan).equals(text(v,"episodeAdaptationPlanId"))&&generationContextHash.equals(text(v,"contextHash"))).max(Comparator.comparingInt(v->v.path("version").asInt()));if(existing.isPresent())return existing.get();
        ObjectNode novel=store.get(NOVEL_SOURCE,required(plan,"novelId"));NovelEpisodeScreenwriter.Result generated=screenwriter.write(new NovelEpisodeScreenwriter.Input(projectId,novel,plan,episodePlan,context,generationContextHash));ObjectNode structured=generated.script();validator.validate(projectId,episodePlan,structured);ObjectNode provenance=obj().put("sourceType","AI_ADAPTATION").put("adaptationPlanId",planId).put("episodeAdaptationPlanId",id(episodePlan)).put("contextHash",generationContextHash).put("adaptationContextHash",adaptationContextHash).put("contextInputChars",context.path("inputChars").asInt()).put("analysisRevision",plan.path("analysisRevision").asInt()).put("model",generated.model()).put("providerRequestId",generated.requestId()).put("compilerVersion",generated.compilerVersion());for(String field:List.of("sourceChunkIds","sourceFactIds","entityVersionIds","entityStateIds"))provenance.set(field,context.path(field).deepCopy());return store.transaction(()->{ObjectNode episode=findOrCreateEpisode(plan,episodePlan);ObjectNode version=scripts.createReviewVersion(id(episode),structured,"NOVEL","AI_ADAPTATION",provenance);applyTransitions(episode,episodePlan);return version;});
    }
    public ObjectNode estimate(String planId,ObjectNode request){adaptations.requireConfirmed(planId);int count=selected(planId,request).size(),budget=request.path("contextBudgetChars").asInt(12000);ObjectNode result=obj().put("planId",planId).put("pendingEpisodes",count).put("estimatedRequests",count).put("estimatedInputTokens",Math.max(1,count*(budget/2L+3072))).put("estimatedOutputTokens",Math.max(1,count*4096L)).put("estimatedCost",0).put("pricingStatus","UNPRICED");result.putObject("layerLimits").putObject("EPISODE_SCREENPLAY").put("maxRequests",count);return result;}
    public ObjectNode generateBatch(String planId,ObjectNode request){ObjectNode plan=adaptations.requireConfirmed(planId),novel=store.get(NOVEL_SOURCE,required(plan,"novelId"));List<Integer> selected=selected(planId,request);NovelIntelligenceRunService.Estimate estimate=estimate(selected.size(),request.path("contextBudgetChars").asInt(12000));return runs.execute(novel,"SCREENPLAY","BATCH",request,false,estimate,()->{ObjectNode result=obj().put("planId",planId).put("requestedEpisodes",selected.size());var versions=result.putArray("versions");int completed=0;for(int episodeNo:selected){try{versions.add(generateInternal(plan,episodeNo,request));completed++;runs.progress("EPISODE_SCREENPLAY",completed,selected.size());}catch(RuntimeException error){return result.put("status","PARTIAL_FAILED").put("completedEpisodes",completed).put("failedEpisodeNo",episodeNo).put("failureCode",error instanceof WorkflowException workflow?workflow.code():"EPISODE_SCREENPLAY_FAILED").put("failureReason",String.valueOf(error.getMessage()));}}return result.put("status","SUCCEEDED").put("completedEpisodes",completed);});}
    private List<Integer> selected(String planId,ObjectNode request){List<ObjectNode> all=adaptations.episodes(planId);String mode=request.path("mode").asText("RANGE").toUpperCase(Locale.ROOT);int from=request.path("fromEpisode").asInt(1),requestedTo=request.path("toEpisode").asInt(all.size()),to="SINGLE".equals(mode)?from:requestedTo;if(!Set.of("SINGLE","RANGE","ALL_UNSTARTED").contains(mode)||from<1||to<from)throw new IllegalArgumentException("剧本批次范围无效");Set<String> generated=new HashSet<>();store.list(EPISODE_SCRIPT_VERSION,project(store.get(ADAPTATION_PLAN,planId)),null).forEach(value->generated.add(text(value,"episodeAdaptationPlanId")));return all.stream().filter(value->"ALL_UNSTARTED".equals(mode)?!generated.contains(id(value)):value.path("episodeNo").asInt()>=from&&value.path("episodeNo").asInt()<=to).map(value->value.path("episodeNo").asInt()).toList();}
    private static NovelIntelligenceRunService.Estimate estimate(int count,int contextChars){ObjectNode layers=obj();layers.putObject("EPISODE_SCREENPLAY").put("maxRequests",count);return new NovelIntelligenceRunService.Estimate(Math.max(1,count),Math.max(1,(long)Math.max(1,count)*(contextChars/2L+3072)),Math.max(1,(long)Math.max(1,count)*4096),0,layers);}
    private ObjectNode findOrCreateEpisode(ObjectNode plan,ObjectNode episodePlan){int number=episodePlan.path("episodeNo").asInt();return store.list(EPISODE,project(plan),null).stream().filter(e->e.path("episodeNo").asInt()==number).findFirst().orElseGet(()->store.create(EPISODE,obj().put("projectId",project(plan)).put("episodeNo",number).put("name","第 "+number+" 集").put("summary",text(episodePlan,"episodeGoal")).put("sourceMode","NOVEL").put("scriptReviewStatus","REVIEW").put("productionReady",false)));}
    private void applyTransitions(ObjectNode episode,ObjectNode plan){apply(episode,plan.path("characterChanges"),CHARACTER);apply(episode,plan.path("locationChanges"),LOCATION);apply(episode,plan.path("propChanges"),PROP);}
    private void apply(ObjectNode episode,JsonNode changes,ResourceKind kind){for(JsonNode node:changes){if(!node.isObject())throw new IllegalArgumentException("状态变化必须是对象");String entityId=required(node,"entityId");ObjectNode entity=store.get(kind,entityId);if(!project(entity).equals(project(episode)))throw new IllegalArgumentException("状态变化实体不属于当前项目");double storyTime=node.path("storyTime").asDouble(Double.NaN);if(Double.isNaN(storyTime))throw new IllegalArgumentException("状态变化缺少 storyTime");ObjectNode state=(ObjectNode)node.deepCopy();state.remove(List.of("entityId","storyTime"));revisions.recordStoryStateTransition(kind,entityId,state,new ChangePoint(id(episode),episode.path("episodeNo").asInt(),null,null,storyTime,null),"NOVEL_ADAPTATION");}}
}
