package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yourapp.drama.persistence.DocumentStore;
import com.yourapp.drama.persistence.ResourceKind;
import org.springframework.stereotype.Service;

import java.util.*;

import static com.yourapp.drama.persistence.ResourceKind.*;
import static com.yourapp.drama.workflow.Documents.*;

@Service
public class EpisodeAdaptationService {
    private final DocumentStore store;private final NovelAdaptationService adaptations;private final NovelAdaptationContextAssembler contexts;private final ScriptWorkspaceService scripts;private final DependencyRevisionService revisions;
    public EpisodeAdaptationService(DocumentStore store,NovelAdaptationService adaptations,NovelAdaptationContextAssembler contexts,ScriptWorkspaceService scripts,DependencyRevisionService revisions){this.store=store;this.adaptations=adaptations;this.contexts=contexts;this.scripts=scripts;this.revisions=revisions;}
    public ObjectNode generate(String planId,int episodeNo,ObjectNode request){
        ObjectNode plan=adaptations.requireConfirmed(planId),episodePlan=adaptations.episodes(planId).stream().filter(e->e.path("episodeNo").asInt()==episodeNo).findFirst().orElseThrow(()->new IllegalArgumentException("分集不存在："+episodeNo));ObjectNode context=contexts.assemble(planId,episodeNo,request.path("contextBudgetChars").asInt(12000));String projectId=project(plan),contextHash=required(context,"contextHash");Optional<ObjectNode> existing=store.list(EPISODE_SCRIPT_VERSION,projectId,null).stream().filter(v->id(episodePlan).equals(text(v,"episodeAdaptationPlanId"))&&contextHash.equals(text(v,"contextHash"))).max(Comparator.comparingInt(v->v.path("version").asInt()));if(existing.isPresent())return existing.get();
        ObjectNode episode=findOrCreateEpisode(plan,episodePlan),structured=structure(plan,episodePlan,context);ObjectNode provenance=obj().put("sourceType","AI_ADAPTATION").put("adaptationPlanId",planId).put("episodeAdaptationPlanId",id(episodePlan)).put("contextHash",contextHash).put("contextInputChars",context.path("inputChars").asInt()).put("analysisRevision",plan.path("analysisRevision").asInt());for(String field:List.of("sourceChunkIds","sourceFactIds","entityVersionIds","entityStateIds"))provenance.set(field,context.path(field).deepCopy());ObjectNode version=scripts.createReviewVersion(id(episode),structured,"NOVEL","AI_ADAPTATION",provenance);applyTransitions(episode,episodePlan);return version;
    }
    private ObjectNode findOrCreateEpisode(ObjectNode plan,ObjectNode episodePlan){int number=episodePlan.path("episodeNo").asInt();return store.list(EPISODE,project(plan),null).stream().filter(e->e.path("episodeNo").asInt()==number).findFirst().orElseGet(()->store.create(EPISODE,obj().put("projectId",project(plan)).put("episodeNo",number).put("name","第 "+number+" 集").put("summary",text(episodePlan,"episodeGoal")).put("sourceMode","NOVEL").put("scriptReviewStatus","REVIEW").put("productionReady",false)));}
    private ObjectNode structure(ObjectNode plan,ObjectNode episodePlan,ObjectNode context){ObjectNode script=obj().put("title",store.get(NOVEL_SOURCE,required(plan,"novelId")).path("title").asText("小说改编")+" · 第"+episodePlan.path("episodeNo").asInt()+"集").put("summary",text(episodePlan,"episodeGoal")).put("openingHook",text(episodePlan,"openingHook")).put("endingHook",text(episodePlan,"endingHook")).put("sourceType","AI_ADAPTATION").put("episodeAdaptationPlanId",id(episodePlan)).put("contextHash",required(context,"contextHash"));script.set("sourceRefs",episodePlan.path("sourceRefs").deepCopy());ArrayNode scenes=script.putArray("scenes");int number=0;for(JsonNode chunkId:episodePlan.path("sourceChunkIds")){ObjectNode chunk=store.get(NOVEL_CHUNK,chunkId.asText()),chapter=store.get(NOVEL_CHAPTER,required(chunk,"chapterId"));String sourceText=text(chunk,"normalizedText");ObjectNode scene=obj().put("sceneKey","novel-"+id(episodePlan)+"-"+(++number)).put("title",text(chapter,"title")).put("summary",abbreviate(sourceText,180)).put("description",abbreviate(sourceText,180)).put("sourceType","ADAPTED");scene.putArray("sourceRefs").add(id(chunk));scene.putArray("actions").add(abbreviate(sourceText,300));scene.set("characterIds",episodePlan.path("characters").deepCopy());scene.set("locationIds",episodePlan.path("locations").deepCopy());scene.set("propIds",episodePlan.path("props").deepCopy());ObjectNode dialogue=scene.putArray("dialogues").addObject().put("lineKey","novel-"+id(episodePlan)+"-line-"+number).put("text","根据本段事件继续行动。").put("semanticText","根据本段事件继续行动。").put("sourceType","ADAPTED");if(!episodePlan.path("characters").isEmpty())dialogue.put("characterId",episodePlan.path("characters").get(0).asText());dialogue.putArray("sourceRefs").add(id(chunk));scenes.add(scene);}ObjectNode bridge=script.putObject("creativeBridge").put("sourceType","AI_ADAPTATION").put("episodeAdaptationPlanId",id(episodePlan)).put("contextHash",required(context,"contextHash")).put("purpose",text(episodePlan,"centralConflict"));bridge.putArray("sourceRefs");return script;}
    private void applyTransitions(ObjectNode episode,ObjectNode plan){apply(episode,plan.path("characterChanges"),CHARACTER);apply(episode,plan.path("locationChanges"),LOCATION);apply(episode,plan.path("propChanges"),PROP);}
    private void apply(ObjectNode episode,JsonNode changes,ResourceKind kind){for(JsonNode node:changes){if(!node.isObject())throw new IllegalArgumentException("状态变化必须是对象");String entityId=required(node,"entityId");ObjectNode entity=store.get(kind,entityId);if(!project(entity).equals(project(episode)))throw new IllegalArgumentException("状态变化实体不属于当前项目");double storyTime=node.path("storyTime").asDouble(Double.NaN);if(Double.isNaN(storyTime))throw new IllegalArgumentException("状态变化缺少 storyTime");ObjectNode state=(ObjectNode)node.deepCopy();state.remove(List.of("entityId","storyTime"));revisions.recordStoryStateTransition(kind,entityId,state,new ChangePoint(id(episode),episode.path("episodeNo").asInt(),null,null,storyTime,null),"NOVEL_ADAPTATION");}}
    private static String abbreviate(String value,int max){return value.length()<=max?value:value.substring(0,max);}
}
