package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yourapp.drama.persistence.DocumentStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import java.util.*;
import static com.yourapp.drama.persistence.ResourceKind.*;
import static com.yourapp.drama.workflow.Documents.*;

@Component
public class HierarchicalNovelAdaptationPlanner implements NovelAdaptationPlanner {
    private final DocumentStore store;private final NovelIntelligenceExecutor ai;private final NovelPromptCompiler prompts;private final int batchSize;
    public HierarchicalNovelAdaptationPlanner(DocumentStore store,NovelIntelligenceExecutor ai,NovelPromptCompiler prompts,@Value("${novel.adaptation.episode-batch-size:10}")int batchSize){this.store=store;this.ai=ai;this.prompts=prompts;this.batchSize=Math.max(1,batchSize);}
    @Override public String contextHash(ObjectNode novel,ObjectNode request){return NovelIngestionService.hashText(id(novel)+"|"+novel.path("analysisRevision").asInt()+"|"+request.path("targetEpisodeCount").asInt()+"|"+request.path("targetEpisodeDuration").asInt(90)+"|"+request.path("adaptationStyle").asText("BALANCED")+"|"+request.path("genre").asText()+"|"+request.path("platform").asText()+"|"+request.path("region").asText()+"|"+request.path("contentRating").toString()+"|"+NovelPromptCompiler.ADAPTATION_PLAN_VERSION+"|"+ai.cacheIdentity("novel_adaptation"));}
    @Override public ObjectNode plan(ObjectNode novel,ObjectNode request){
        String rootHash=contextHash(novel,request),projectId=project(novel);int count=request.path("targetEpisodeCount").asInt();if(count<1)throw new IllegalArgumentException("targetEpisodeCount 必须大于 0");
        List<ObjectNode> chapters=chapters(novel),arcs=store.list(NOVEL_STORY_ARC,projectId,id(novel)),facts=store.list(STORY_FACT,projectId,null).stream().filter(f->id(novel).equals(text(f,"novelId"))).toList();
        ObjectNode skeleton=skeleton(novel,request,chapters,arcs,facts);NovelPromptIR skeletonIr=ir(novel,request,NovelIngestionService.hashText(rootHash+":skeleton"),chapterIds(chapters),entityIds(novel),ids(facts),skeletonInput(novel,request,chapters,arcs,facts));
        var skeletonResult=ai.executeOrReuse(projectId,skeletonIr,prompts.compileAdaptationPlan(skeletonIr));mergeSkeleton(skeleton,skeletonResult.value());
        List<ObjectNode> generated=allocate(novel,request,chapters,facts);ArrayNode batchIds=array();
        for(int from=0;from<count;from+=batchSize){int to=Math.min(count,from+batchSize);String hash=NovelIngestionService.hashText(rootHash+":batch:"+(from+1)+"-"+to);ObjectNode payload=obj();payload.set("seasonSkeleton",skeleton.deepCopy());payload.set("episodes",array(generated.subList(from,to)));if(from>0)payload.set("previousBatchHandoff",handoff(generated.get(from-1)));payload.set("relevantStoryArcs",array(arcs));NovelPromptIR batchIr=ir(novel,request,hash,sourceChapterIds(generated.subList(from,to)),entityIds(novel),ids(facts),payload.toString());var result=ai.executeOrReuse(projectId,batchIr,prompts.compileAdaptationPlan(batchIr));if(result.value().path("episodes").isArray()&&!result.value().path("episodes").isEmpty()){for(int i=0;i<Math.min(to-from,result.value().path("episodes").size());i++)generated.set(from+i,(ObjectNode)result.value().path("episodes").get(i).deepCopy());}batchIds.add(result.requestId());}
        ObjectNode output=obj().put("planningContextHash",rootHash).put("model",ai.cacheIdentity("novel_adaptation")).put("compilerVersion",NovelPromptCompiler.ADAPTATION_PLAN_VERSION).put("seasonSkeletonRequestId",skeletonResult.requestId());output.set("seasonSkeleton",skeleton);output.set("batchRequestIds",batchIds);output.set("episodes",array(generated));return output;
    }
    private ObjectNode skeleton(ObjectNode novel,ObjectNode request,List<ObjectNode> chapters,List<ObjectNode> arcs,List<ObjectNode> facts){int count=request.path("targetEpisodeCount").asInt();ObjectNode s=obj().put("seasonGoal",text(store.list(NOVEL_STORY_GRAPH,project(novel),id(novel)).getLast(),"mainPlot")).put("mainCharacterArc","按人物欲望、阻力和选择推进");for(String f:List.of("macroArcs","episodeRanges","majorHooks","majorClimaxes","paywallCandidates","subplotAllocation","factReleaseSchedule","reservedFutureFacts","mergeCandidates","omittedSourceRanges"))s.putArray(f);for(ObjectNode arc:arcs)s.withArray("macroArcs").add(id(arc));if(!arcs.isEmpty())s.withArray("episodeRanges").addObject().put("fromEpisode",1).put("toEpisode",count).put("arcId",id(arcs.getFirst()));for(ObjectNode fact:facts){int preferred=Math.max(1,Math.min(count,(int)Math.ceil(fact.path("validFromStoryTime").asDouble(1)/Math.max(1,chapters.size())*count)));s.withArray("factReleaseSchedule").addObject().put("factId",id(fact)).put("earliestRevealEpisode",Math.max(1,preferred-1)).put("preferredRevealEpisode",preferred).put("latestRevealEpisode",Math.min(count,preferred+1));if(preferred>1)s.withArray("reservedFutureFacts").add(id(fact));}return s;}
    private List<ObjectNode> allocate(ObjectNode novel,ObjectNode request,List<ObjectNode> chapters,List<ObjectNode> facts){int total=request.path("targetEpisodeCount").asInt(),duration=request.path("targetEpisodeDuration").asInt(90);if(total<chapters.size())return groupChapters(novel,request,chapters,facts);double[] weights=new double[chapters.size()];int assigned=0;int[] slots=new int[chapters.size()];if(total>=chapters.size()){Arrays.fill(slots,1);assigned=chapters.size();}for(int i=0;i<chapters.size();i++)weights[i]=weight(novel,chapters.get(i),i==chapters.size()-1);double sum=Arrays.stream(weights).sum();while(assigned<total){int best=0;double score=-1;for(int i=0;i<slots.length;i++){double candidate=weights[i]/(slots[i]+1);if(candidate>score){score=candidate;best=i;}}slots[best]++;assigned++;}List<ObjectNode> result=new ArrayList<>();int number=0;for(int ci=0;ci<chapters.size();ci++){ObjectNode chapter=chapters.get(ci);List<ObjectNode> chunks=store.list(NOVEL_CHUNK,project(novel),id(chapter)).stream().filter(c->c.path("active").asBoolean(true)).toList();for(int part=1;part<=slots[ci];part++){ObjectNode e=obj().put("episodeNo",++number).put("episodeGoal",text(chapter,"title")+" · 推进阶段 "+part+"/"+slots[ci]).put("openingHook",number==1?"前三秒建立人物欲望与核心异常":"承接上一集未决行动").put("centralConflict",abbreviate(text(chapter,"normalizedText"),180)).put("informationReveal","仅释放当前章节与计划窗口允许的信息").put("emotionalTurn",part==slots[ci]?"人物因本章结果作出新选择":"压力继续累积").put("climax",part==slots[ci]?"本章关键行动产生后果":"冲突升级但尚未解决").put("endingHook",number==total?"季终问题形成明确余波":"下一步行动由当前因果直接触发").put("estimatedDurationSec",duration).put("adaptationReason","依据章节叙事重要度 "+weights[ci]+" 分配 "+slots[ci]+" 集，保留因果与信息揭示顺序");e.putArray("sourceChapterIds").add(id(chapter));ArrayNode chunkIds=e.putArray("sourceChunkIds");chunks.forEach(c->chunkIds.add(id(c)));e.set("sourceRefs",chunkIds.deepCopy());for(String f:List.of("characters","locations","props","requiredFacts","newFacts","reservedFutureFacts","relationshipChanges","characterChanges","propChanges","locationChanges"))e.putArray(f);e.set("characters",canonical(novel,"canonicalCharacters"));e.set("locations",canonical(novel,"canonicalLocations"));e.set("props",canonical(novel,"canonicalProps"));for(String f:List.of("knowledgeStart","knowledgeEnd","propStateStart","propStateEnd","locationStateStart","locationStateEnd"))e.putObject(f);for(ObjectNode fact:facts){if(fact.path("validFromStoryTime").asDouble()>chapter.path("chapterNo").asDouble())e.withArray("reservedFutureFacts").add(id(fact));else e.withArray("requiredFacts").add(id(fact));}result.add(e);}}return result;}
    private List<ObjectNode> groupChapters(ObjectNode novel,ObjectNode request,List<ObjectNode> chapters,List<ObjectNode> facts){
        int total=request.path("targetEpisodeCount").asInt(),duration=request.path("targetEpisodeDuration").asInt(90);double[] weights=new double[chapters.size()];for(int i=0;i<weights.length;i++)weights[i]=weight(novel,chapters.get(i),i==weights.length-1);double remainingWeight=Arrays.stream(weights).sum();int cursor=0;List<ObjectNode> result=new ArrayList<>();
        for(int episodeNo=1;episodeNo<=total;episodeNo++){int remainingEpisodes=total-episodeNo+1,start=cursor;double target=remainingWeight/remainingEpisodes,used=0;while(cursor<chapters.size()-(remainingEpisodes-1)&&(used<target||cursor==start)){used+=weights[cursor++];}List<ObjectNode> selected=chapters.subList(start,cursor);remainingWeight-=used;ObjectNode e=obj().put("episodeNo",episodeNo).put("episodeGoal","整合 "+text(selected.getFirst(),"title")+" 至 "+text(selected.getLast(),"title")+" 的核心因果").put("openingHook",episodeNo==1?"前三秒建立人物欲望与核心异常":"承接上一集未决行动").put("centralConflict","在有限时长内推进所选章节的主冲突").put("informationReveal","按原作顺序释放所选章节事实").put("emotionalTurn","本批章节的关键选择改变人物关系").put("climax","所选章节中最高权重事件产生后果").put("endingHook",episodeNo==total?"季终问题形成明确余波":"下一批章节的行动由当前因果直接触发").put("estimatedDurationSec",duration).put("adaptationReason","按累计叙事权重合并连续章节，避免平均章节切割");ArrayNode chapterIds=e.putArray("sourceChapterIds"),chunkIds=e.putArray("sourceChunkIds");selected.forEach(chapter->{chapterIds.add(id(chapter));store.list(NOVEL_CHUNK,project(novel),id(chapter)).stream().filter(c->c.path("active").asBoolean(true)).forEach(c->chunkIds.add(id(c)));});e.set("sourceRefs",chunkIds.deepCopy());for(String f:List.of("characters","locations","props","requiredFacts","newFacts","reservedFutureFacts","relationshipChanges","characterChanges","propChanges","locationChanges"))e.putArray(f);e.set("characters",canonical(novel,"canonicalCharacters"));e.set("locations",canonical(novel,"canonicalLocations"));e.set("props",canonical(novel,"canonicalProps"));for(String f:List.of("knowledgeStart","knowledgeEnd","propStateStart","propStateEnd","locationStateStart","locationStateEnd"))e.putObject(f);double lastChapter=selected.getLast().path("chapterNo").asDouble();for(ObjectNode fact:facts){if(fact.path("validFromStoryTime").asDouble()>lastChapter)e.withArray("reservedFutureFacts").add(id(fact));else e.withArray("requiredFacts").add(id(fact));}result.add(e);}return result;
    }
    private ArrayNode canonical(ObjectNode novel,String field){JsonNode values=store.list(NOVEL_STORY_GRAPH,project(novel),id(novel)).getLast().path(field);return values.isArray()?(ArrayNode)values.deepCopy():array();}
    private double weight(ObjectNode novel,ObjectNode chapter,boolean last){ObjectNode analysis=store.list(NOVEL_CHAPTER_ANALYSIS,project(novel),id(chapter)).stream().max(Comparator.comparingInt(a->a.path("analysisRevision").asInt())).orElse(null);double weight=analysis==null?1:Math.max(1,analysis.path("plotImportance").asDouble(50)/25);String body=text(chapter,"normalizedText");for(String marker:List.of("真相","幕后","死亡","高潮","揭晓","反转"))if(body.contains(marker))weight+=2;if(body.contains("钥匙")||body.contains("开启"))weight+=1;if(last)weight+=2;return weight;}
    private String skeletonInput(ObjectNode novel,ObjectNode request,List<ObjectNode> chapters,List<ObjectNode> arcs,List<ObjectNode> facts){ObjectNode input=obj();input.set("globalStoryGraph",store.list(NOVEL_STORY_GRAPH,project(novel),id(novel)).getLast().deepCopy());input.set("storyArcs",array(arcs));ArrayNode metadata=input.putArray("chapterMetadata");chapters.forEach(c->metadata.addObject().put("chapterId",id(c)).put("chapterNo",c.path("chapterNo").asInt()).put("title",text(c,"title")).put("charCount",c.path("charCount").asInt()));input.set("majorFacts",array(facts));input.set("targetConfig",request.deepCopy());return input.toString();}
    private void mergeSkeleton(ObjectNode target,ObjectNode aiValue){for(String field:List.of("seasonGoal","mainCharacterArc"))if(!text(aiValue,field).isBlank())target.put(field,text(aiValue,field));for(String field:List.of("macroArcs","episodeRanges","majorHooks","majorClimaxes","paywallCandidates","subplotAllocation","factReleaseSchedule","reservedFutureFacts","mergeCandidates","omittedSourceRanges"))if(aiValue.path(field).isArray()&&!aiValue.path(field).isEmpty())target.set(field,aiValue.path(field).deepCopy());}
    private NovelPromptIR ir(ObjectNode novel,ObjectNode request,String hash,List<String> chapterIds,List<String> entityIds,List<String> factIds,String payload){return new NovelPromptIR(id(novel),chapterIds,List.of(),entityIds,factIds,novel.path("analysisProfile").asText("STANDARD"),request.path("adaptationStyle").asText("BALANCED"),request.path("targetEpisodeDuration").asInt(90),hash,"UNTRUSTED_NOVEL_TEXT",List.of("不得泄漏 reservedFutureFacts","分集编号连续","每批最多 "+batchSize+" 集"),payload);}
    private List<ObjectNode> chapters(ObjectNode novel){return store.list(NOVEL_CHAPTER,project(novel),id(novel)).stream().filter(c->c.path("active").asBoolean(true)).sorted(Comparator.comparingInt(c->c.path("chapterNo").asInt())).toList();}
    private List<String> entityIds(ObjectNode novel){List<String> values=new ArrayList<>();for(var kind:List.of(CHARACTER,LOCATION,PROP))store.list(kind,project(novel),null).stream().filter(e->id(novel).equals(text(e,"novelId"))).map(Documents::id).forEach(values::add);return values;}
    private static List<String> chapterIds(List<ObjectNode> values){return values.stream().map(Documents::id).toList();}
    private static List<String> sourceChapterIds(List<ObjectNode> episodes){LinkedHashSet<String> ids=new LinkedHashSet<>();episodes.forEach(e->e.path("sourceChapterIds").forEach(v->ids.add(v.asText())));return List.copyOf(ids);}
    private static List<String> ids(List<ObjectNode> values){return values.stream().map(Documents::id).toList();}
    private static ArrayNode array(){return com.fasterxml.jackson.databind.node.JsonNodeFactory.instance.arrayNode();}
    private static ArrayNode array(List<ObjectNode> values){ArrayNode a=array();values.forEach(v->a.add(v.deepCopy()));return a;}
    private static ObjectNode handoff(ObjectNode episode){return obj().put("episodeNo",episode.path("episodeNo").asInt()).put("endingHook",text(episode,"endingHook")).set("reservedFutureFacts",episode.path("reservedFutureFacts").deepCopy());}
    private static String abbreviate(String value,int max){return value==null?"":value.length()<=max?value:value.substring(0,max);}
}



