package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yourapp.drama.persistence.DocumentStore;
import com.yourapp.drama.storage.NovelStorage;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Instant;
import java.util.*;

import static com.yourapp.drama.persistence.ResourceKind.*;
import static com.yourapp.drama.workflow.Documents.*;

@Service
public class NovelIngestionService {
    private final DocumentStore store;private final NovelStorage storage;private final NovelDocumentParser parser;private final ChapterBoundaryDetector boundaries;private final long maxFileSize,defaultPartSize;private final int maxParts;
    public NovelIngestionService(DocumentStore store,NovelStorage storage,NovelDocumentParser parser,ChapterBoundaryDetector boundaries,@Value("${novel.upload.max-file-size:1073741824}")long maxFileSize,@Value("${novel.upload.part-size:4194304}")long defaultPartSize,@Value("${novel.upload.max-parts:2000}")int maxParts){this.store=store;this.storage=storage;this.parser=parser;this.boundaries=boundaries;this.maxFileSize=maxFileSize;this.defaultPartSize=defaultPartSize;this.maxParts=maxParts;}
    public ObjectNode startUpload(String projectId,ObjectNode request){store.get(PROJECT,projectId);String name=required(request,"fileName"),format=required(request,"format").toUpperCase(Locale.ROOT),hash=required(request,"fileSha256").toLowerCase(Locale.ROOT);long size=request.path("fileSize").asLong(-1),partSize=request.path("partSize").asLong(defaultPartSize);int total=request.path("totalParts").asInt((int)Math.ceil(size/(double)partSize));if(name.contains("/")||name.contains("\\")||name.contains(".."))throw new IllegalArgumentException("文件名不能包含路径");String ext=switch(format){case "TXT"->"txt";case "DOCX"->"docx";case "EPUB"->"epub";default->throw new IllegalArgumentException("只支持 TXT、DOCX、EPUB");};if(!name.toLowerCase(Locale.ROOT).endsWith("."+ext))throw new IllegalArgumentException("文件扩展名与格式不一致");String mime=text(request,"contentType");if(!mime.isBlank()&&!validMime(format,mime))throw new IllegalArgumentException("文件 MIME 与格式不一致");if(size<1||size>maxFileSize||partSize<1||partSize>maxFileSize||total<1||total>maxParts||total!=(int)Math.ceil(size/(double)partSize))throw new IllegalArgumentException("上传大小或分片参数超出限制");if(!hash.matches("[0-9a-f]{64}"))throw new IllegalArgumentException("fileSha256 无效");String uploadId=UUID.randomUUID().toString(),storageKey=UUID.randomUUID()+"."+ext;ObjectNode session=obj().put("id",uploadId).put("uploadId",uploadId).put("projectId",projectId).put("fileName",name).put("fileSize",size).put("format",format).put("partSize",partSize).put("totalParts",total).put("fileSha256",hash).put("status","UPLOADING").put("storageKey",storageKey);session.putArray("parts");return withMissing(store.create(NOVEL_UPLOAD_SESSION,session));}
    public ObjectNode putPart(String uploadId,int partNo,InputStream input,long declaredSize,String declaredHash){return store.transaction(()->{ObjectNode session=store.getForUpdate(NOVEL_UPLOAD_SESSION,uploadId);if(!"UPLOADING".equals(text(session,"status")))throw new WorkflowException("UPLOAD_NOT_ACTIVE","上传会话不是进行中");int total=session.path("totalParts").asInt();if(partNo<1||partNo>total)throw new IllegalArgumentException("partNo 超出范围");for(JsonNode existing:session.path("parts"))if(existing.path("partNo").asInt()==partNo){if(!text(existing,"sha256").equalsIgnoreCase(declaredHash)||existing.path("size").asLong()!=declaredSize)throw new WorkflowException("UPLOAD_PART_CONFLICT","同一分片已上传不同内容");return withMissing(session);}long max=session.path("partSize").asLong(),expected=partNo==total?session.path("fileSize").asLong()-max*(total-1):max;if(declaredSize!=expected)throw new IllegalArgumentException("分片大小不正确");NovelStorage.StoredPart saved=storage.writePart(uploadId,partNo,input,max);if(saved.size()!=declaredSize||!saved.sha256().equalsIgnoreCase(declaredHash))throw new WorkflowException("UPLOAD_PART_HASH_MISMATCH","分片 SHA-256 校验失败");ObjectNode next=session.deepCopy();next.withArray("parts").add(obj().put("partNo",partNo).put("size",saved.size()).put("sha256",saved.sha256()).put("receivedAt",Instant.now().toString()));next.put("receivedParts",next.path("parts").size());return withMissing(store.update(NOVEL_UPLOAD_SESSION,uploadId,revision(session),next));});}
    public ObjectNode upload(String id){return withMissing(store.get(NOVEL_UPLOAD_SESSION,id));}
    public ObjectNode complete(String uploadId){ObjectNode session=store.get(NOVEL_UPLOAD_SESSION,uploadId);if("COMPLETED".equals(text(session,"status")))return store.get(NOVEL_SOURCE,required(session,"novelId"));if(withMissing(session).path("missingParts").size()>0)throw new WorkflowException("UPLOAD_INCOMPLETE","仍有分片未上传");NovelStorage.StoredPart file=storage.assemble(uploadId,session.path("totalParts").asInt(),required(session,"storageKey"));if(file.size()!=session.path("fileSize").asLong()||!file.sha256().equalsIgnoreCase(text(session,"fileSha256")))throw new WorkflowException("UPLOAD_FILE_HASH_MISMATCH","完整文件大小或 SHA-256 不匹配");ObjectNode source=store.create(NOVEL_SOURCE,obj().put("projectId",project(session)).put("title",stripExtension(text(session,"fileName"))).put("author","UNKNOWN").put("format",text(session,"format")).put("storageKey",text(session,"storageKey")).put("fileName",text(session,"fileName")).put("fileSize",file.size()).put("fileHash",file.sha256()).put("status","PARSING").put("totalCharacters",0).put("chapterCount",0).put("parsingRevision",1));ObjectNode current=store.get(NOVEL_UPLOAD_SESSION,uploadId);store.update(NOVEL_UPLOAD_SESSION,uploadId,revision(current),current.deepCopy().put("status","COMPLETED").put("novelId",id(source)));try{return parse(source);}catch(RuntimeException error){ObjectNode failed=store.get(NOVEL_SOURCE,id(source));String status=error instanceof WorkflowException workflow&&"ENCODING_REVIEW_REQUIRED".equals(workflow.code())?"ENCODING_REVIEW_REQUIRED":"FAILED";store.update(NOVEL_SOURCE,id(source),revision(failed),failed.deepCopy().put("status",status).put("failureReason",error.getMessage()));throw error;}}
    public ObjectNode cancel(String uploadId){ObjectNode session=store.get(NOVEL_UPLOAD_SESSION,uploadId);if(!"COMPLETED".equals(text(session,"status")))storage.cancel(uploadId);return store.update(NOVEL_UPLOAD_SESSION,uploadId,revision(session),session.deepCopy().put("status","CANCELLED"));}
    public ObjectNode renameChapter(String chapterId,ObjectNode request){ObjectNode chapter=store.get(NOVEL_CHAPTER,chapterId);long expected=request.path("revision").asLong(-1);if(expected!=revision(chapter))throw new com.yourapp.drama.persistence.RevisionConflictException(NOVEL_CHAPTER,chapterId);ObjectNode saved=store.update(NOVEL_CHAPTER,chapterId,expected,chapter.deepCopy().put("title",required(request,"title")).put("manuallyCorrected",true));bumpParsing(required(chapter,"novelId"));return saved;}
    public ObjectNode splitChapter(String chapterId,ObjectNode request){return store.transaction(()->{ObjectNode chapter=store.getForUpdate(NOVEL_CHAPTER,chapterId);if(request.path("revision").asLong(-1)!=revision(chapter))throw new com.yourapp.drama.persistence.RevisionConflictException(NOVEL_CHAPTER,chapterId);if(!chapter.path("active").asBoolean(true))throw new WorkflowException("CHAPTER_INACTIVE","已合并章节不能再拆分");String content=text(chapter,"normalizedText");int offset=request.path("offset").asInt(-1);if(offset<1||offset>=content.length())throw new IllegalArgumentException("拆分位置必须位于章节正文内");String novelId=required(chapter,"novelId");int parsingRevision=bumpParsing(novelId),maxNo=store.list(NOVEL_CHAPTER,project(chapter),novelId).stream().mapToInt(c->c.path("chapterNo").asInt()).max().orElse(0);double order=chapter.path("displayOrder").asDouble(chapter.path("chapterNo").asDouble());String before=content.substring(0,offset).strip(),after=content.substring(offset).strip();ObjectNode first=store.update(NOVEL_CHAPTER,chapterId,revision(chapter),chapter.deepCopy().put("normalizedText",before).put("rawText",before).put("charCount",before.length()).put("contentHash",hashText(before)).put("sourceEnd",chapter.path("sourceStart").asInt()+offset).put("manuallyCorrected",true).put("parsingRevision",parsingRevision));ObjectNode second=store.create(NOVEL_CHAPTER,obj().put("projectId",project(chapter)).put("novelId",novelId).put("chapterNo",maxNo+1).put("displayOrder",order+.5).put("title",request.path("title").asText(text(chapter,"title")+"（下）")).put("rawText",after).put("normalizedText",after).put("charCount",after.length()).put("sourceStart",chapter.path("sourceStart").asInt()+offset).put("sourceEnd",chapter.path("sourceEnd").asInt()).put("contentHash",hashText(after)).put("synthetic",chapter.path("synthetic").asBoolean()).put("active",true).put("manuallyCorrected",true).put("parsingRevision",parsingRevision));rebuildChunks(first,parsingRevision);chunks(second);return second;});}
    public ObjectNode mergeChapters(String targetId,String sourceId,ObjectNode request){return store.transaction(()->{if(targetId.equals(sourceId))throw new IllegalArgumentException("不能合并同一章节");ObjectNode target=store.getForUpdate(NOVEL_CHAPTER,targetId),source=store.getForUpdate(NOVEL_CHAPTER,sourceId);if(request.path("revision").asLong(-1)!=revision(target))throw new com.yourapp.drama.persistence.RevisionConflictException(NOVEL_CHAPTER,targetId);if(!required(target,"novelId").equals(required(source,"novelId"))||!source.path("active").asBoolean(true))throw new WorkflowException("CHAPTER_MERGE_INVALID","只能合并同一本书中的有效章节");int parsingRevision=bumpParsing(required(target,"novelId"));String content=(text(target,"normalizedText")+"\n"+text(source,"normalizedText")).strip();ObjectNode merged=store.update(NOVEL_CHAPTER,targetId,revision(target),target.deepCopy().put("normalizedText",content).put("rawText",content).put("charCount",content.length()).put("contentHash",hashText(content)).put("sourceEnd",Math.max(target.path("sourceEnd").asInt(),source.path("sourceEnd").asInt())).put("manuallyCorrected",true).put("parsingRevision",parsingRevision));store.update(NOVEL_CHAPTER,sourceId,revision(source),source.deepCopy().put("active",false).put("mergedIntoChapterId",targetId).put("parsingRevision",parsingRevision));for(ObjectNode chunk:store.list(NOVEL_CHUNK,project(source),sourceId))store.update(NOVEL_CHUNK,id(chunk),revision(chunk),chunk.deepCopy().put("active",false).put("parsingRevision",parsingRevision));rebuildChunks(merged,parsingRevision);return merged;});}
    public ObjectNode reorderChapters(String novelId,ArrayNode chapterIds){return store.transaction(()->{ObjectNode source=store.getForUpdate(NOVEL_SOURCE,novelId);List<ObjectNode> active=store.list(NOVEL_CHAPTER,project(source),novelId).stream().filter(c->c.path("active").asBoolean(true)).toList();List<String> requested=new ArrayList<>();chapterIds.forEach(node->requested.add(node.asText()));Set<String> expected=new HashSet<>(active.stream().map(c->id(c)).toList());if(requested.size()!=expected.size()||new HashSet<>(requested).size()!=requested.size()||!expected.equals(new HashSet<>(requested)))throw new IllegalArgumentException("排序必须且只能包含全部有效章节");int parsingRevision=bumpParsing(novelId);for(int i=0;i<requested.size();i++){ObjectNode chapter=store.get(NOVEL_CHAPTER,requested.get(i));store.update(NOVEL_CHAPTER,id(chapter),revision(chapter),chapter.deepCopy().put("displayOrder",i+1).put("manuallyCorrected",true).put("parsingRevision",parsingRevision));}return store.get(NOVEL_SOURCE,novelId);});}
    private ObjectNode parse(ObjectNode source){String projectId=project(source),novelId=id(source);Accumulator accumulator=new Accumulator(projectId,novelId);String encoding=parser.parse(storage.source(required(source,"storageKey")),text(source,"format"),accumulator::accept);accumulator.finish();ObjectNode current=store.get(NOVEL_SOURCE,novelId);return store.update(NOVEL_SOURCE,novelId,revision(current),current.deepCopy().put("status","READY").put("encoding",encoding).put("totalCharacters",accumulator.offset).put("chapterCount",accumulator.chapterNo));}
    private final class Accumulator {final String projectId,novelId;String title="";StringBuilder content=new StringBuilder();int chapterNo=0,offset=0,start=0;boolean explicit=false;Accumulator(String projectId,String novelId){this.projectId=projectId;this.novelId=novelId;}void accept(String paragraph){String line=paragraph==null?"":paragraph.strip();boolean boundary=boundaries.isBoundary(line);if(boundary){flush();title=line;start=offset;explicit=true;}else{if(content.isEmpty()&&title.isBlank())start=offset;if(!line.isBlank()){if(!content.isEmpty())content.append('\n');content.append(line);}if(!explicit&&content.length()>=20_000)flush();}offset+=paragraph==null?1:paragraph.length()+1;}void finish(){flush();}void flush(){if(content.isEmpty()&&title.isBlank())return;String raw=content.toString(),normalized=raw.replace("\r\n","\n").strip();ObjectNode chapter=store.create(NOVEL_CHAPTER,obj().put("projectId",projectId).put("novelId",novelId).put("chapterNo",++chapterNo).put("displayOrder",chapterNo).put("title",title.isBlank()?"第 "+chapterNo+" 节":title).put("rawText",raw).put("normalizedText",normalized).put("charCount",normalized.length()).put("sourceStart",start).put("sourceEnd",offset).put("contentHash",hashText(normalized)).put("synthetic",!explicit).put("active",true).put("parsingRevision",1));chunks(chapter);title="";content.setLength(0);start=offset;}}
    private void chunks(ObjectNode chapter){int parsingRevision=chapter.path("parsingRevision").asInt(store.get(NOVEL_SOURCE,required(chapter,"novelId")).path("parsingRevision").asInt(1));String value=text(chapter,"normalizedText");List<int[]> ranges=semanticRanges(value);List<ObjectNode> saved=new ArrayList<>();int number=0;for(int[] range:ranges){String part=value.substring(range[0],range[1]);ObjectNode chunk=store.create(NOVEL_CHUNK,obj().put("projectId",project(chapter)).put("novelId",required(chapter,"novelId")).put("chapterId",id(chapter)).put("chunkNo",++number).put("normalizedText",part).put("sourceStart",chapter.path("sourceStart").asInt()+range[0]).put("sourceEnd",chapter.path("sourceStart").asInt()+range[1]).put("charCount",part.length()).put("contentHash",hashText(part)).put("active",true).put("parsingRevision",parsingRevision));saved.add(chunk);sourceReference(chapter,chunk,parsingRevision);}link(saved);}
    private void rebuildChunks(ObjectNode chapter,int parsingRevision){String content=text(chapter,"normalizedText");List<int[]> ranges=semanticRanges(content);List<ObjectNode> existing=store.list(NOVEL_CHUNK,project(chapter),id(chapter)).stream().sorted(Comparator.comparingInt(c->c.path("chunkNo").asInt())).toList(),saved=new ArrayList<>();for(int i=0;i<ranges.size();i++){int[] range=ranges.get(i);String part=content.substring(range[0],range[1]);ObjectNode chunk;if(i<existing.size()){ObjectNode old=existing.get(i);chunk=store.update(NOVEL_CHUNK,id(old),revision(old),old.deepCopy().put("normalizedText",part).put("sourceStart",chapter.path("sourceStart").asInt()+range[0]).put("sourceEnd",chapter.path("sourceStart").asInt()+range[1]).put("charCount",part.length()).put("contentHash",hashText(part)).put("active",true).put("parsingRevision",parsingRevision));}else chunk=store.create(NOVEL_CHUNK,obj().put("projectId",project(chapter)).put("novelId",required(chapter,"novelId")).put("chapterId",id(chapter)).put("chunkNo",i+1).put("normalizedText",part).put("sourceStart",chapter.path("sourceStart").asInt()+range[0]).put("sourceEnd",chapter.path("sourceStart").asInt()+range[1]).put("charCount",part.length()).put("contentHash",hashText(part)).put("active",true).put("parsingRevision",parsingRevision));saved.add(chunk);sourceReference(chapter,chunk,parsingRevision);}for(int i=ranges.size();i<existing.size();i++){ObjectNode old=existing.get(i);store.update(NOVEL_CHUNK,id(old),revision(old),old.deepCopy().put("active",false).put("parsingRevision",parsingRevision));}link(saved);}
    private void sourceReference(ObjectNode chapter,ObjectNode chunk,int parsingRevision){store.create(SOURCE_REFERENCE,obj().put("projectId",project(chapter)).put("sourceType","NOVEL").put("novelId",required(chapter,"novelId")).put("chapterId",id(chapter)).put("chunkId",id(chunk)).put("startOffset",chunk.path("sourceStart").asInt()).put("endOffset",chunk.path("sourceEnd").asInt()).put("contentHash",text(chunk,"contentHash")).put("parsingRevision",parsingRevision));}
    private void link(List<ObjectNode> saved){for(int i=0;i<saved.size();i++){ObjectNode chunk=store.get(NOVEL_CHUNK,id(saved.get(i))),next=chunk.deepCopy();if(i>0)next.put("previousChunkId",id(saved.get(i-1)));else next.remove("previousChunkId");if(i+1<saved.size())next.put("nextChunkId",id(saved.get(i+1)));else next.remove("nextChunkId");if(!next.equals(chunk))store.update(NOVEL_CHUNK,id(chunk),revision(chunk),next);}}
    private static List<int[]> semanticRanges(String text){List<int[]> result=new ArrayList<>();if(text.isEmpty()){result.add(new int[]{0,0});return result;}int start=0;while(start<text.length()){int max=Math.min(text.length(),start+6000),target=Math.min(text.length(),start+4000),end=max;if(max<text.length()){for(int i=max-1;i>=Math.min(start+2000,target);i--)if("\n。！？!?；;".indexOf(text.charAt(i))>=0){end=i+1;break;}}result.add(new int[]{start,end});start=end;}return result;}
    private ObjectNode withMissing(ObjectNode session){ObjectNode result=session.deepCopy();Set<Integer> received=new HashSet<>();for(JsonNode part:session.path("parts"))received.add(part.path("partNo").asInt());ArrayNode missing=result.putArray("missingParts");for(int i=1;i<=session.path("totalParts").asInt();i++)if(!received.contains(i))missing.add(i);result.put("receivedParts",received.size());return result;}
    private int bumpParsing(String novelId){ObjectNode source=store.getForUpdate(NOVEL_SOURCE,novelId);int next=source.path("parsingRevision").asInt(1)+1;store.update(NOVEL_SOURCE,novelId,revision(source),source.deepCopy().put("parsingRevision",next));return next;}
    private static boolean validMime(String format,String mime){String value=mime.toLowerCase(Locale.ROOT);return switch(format){case "TXT"->value.startsWith("text/")||value.equals("application/octet-stream");case "DOCX"->value.contains("wordprocessingml")||value.equals("application/zip");case "EPUB"->value.contains("epub+zip")||value.equals("application/zip");default->false;};}
    private static String stripExtension(String value){int dot=value.lastIndexOf('.');return dot>0?value.substring(0,dot):value;}
    private static String hashText(String value){return DependencyRevisionService.hash(com.fasterxml.jackson.databind.node.TextNode.valueOf(value));}
}
