package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yourapp.drama.model.ProviderException;
import com.yourapp.drama.persistence.DocumentStore;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.function.Supplier;

import static com.yourapp.drama.persistence.ResourceKind.NOVEL_INTELLIGENCE_RUN;
import static com.yourapp.drama.workflow.Documents.*;

@Service
public class NovelIntelligenceRunService {
    public record Estimate(long requests,long inputTokens,long outputTokens,double estimatedCost,ObjectNode layerLimits){}
    public record Reservation(String runId,String layer,long inputTokens,long outputTokens,double estimatedCost){static Reservation none(){return new Reservation(null,"",0,0,0);}}
    private final DocumentStore store;private final NovelIntelligenceBudgetGuard guard;private final NovelIntelligenceProviderGate gate;private final ThreadLocal<String> current=new ThreadLocal<>();
    public NovelIntelligenceRunService(DocumentStore store,NovelIntelligenceBudgetGuard guard,NovelIntelligenceProviderGate gate){this.store=store;this.guard=guard;this.gate=gate;}

    public <T>T execute(ObjectNode novel,String type,String profile,ObjectNode request,boolean resume,Estimate estimate,Supplier<T> work){
        if(current.get()!=null)return work.get();ObjectNode run=resume?resumable(id(novel),type):null;if(run!=null&&"RECONCILIATION_REQUIRED".equals(text(run,"status")))throw new WorkflowException("NOVEL_INTELLIGENCE_RECONCILIATION_REQUIRED","上次文本请求状态不确定，禁止重新提交");if(run==null)run=create(novel,type,profile,request,estimate);else run=store.update(NOVEL_INTELLIGENCE_RUN,id(run),revision(run),run.deepCopy().put("status","RUNNING").put("resumedAt",Instant.now().toString()));String runId=id(run);current.set(runId);
        try{T result=work.get();String status=result instanceof JsonNode node&&"PARTIAL_FAILED".equals(text(node,"status"))?"PARTIAL_FAILED":"SUCCEEDED";finishRun(runId,status,null);return result;}catch(RuntimeException error){String status=error instanceof ProviderException pe&&pe.uncertain()?"RECONCILIATION_REQUIRED":"FAILED";finishRun(runId,status,error);throw error;}finally{current.remove();}
    }
    public Reservation reserve(String layer,long inputTokens,long outputTokens,double estimatedCost){String runId=current.get();if(runId==null)return Reservation.none();return store.transaction(()->{ObjectNode run=store.getForUpdate(NOVEL_INTELLIGENCE_RUN,runId);guard.assertCanReserve(run,layer,inputTokens,outputTokens,estimatedCost);ObjectNode next=run.deepCopy().put("usedRequests",run.path("usedRequests").asLong()+1).put("reservedInputTokens",run.path("reservedInputTokens").asLong()+inputTokens).put("reservedOutputTokens",run.path("reservedOutputTokens").asLong()+outputTokens).put("reservedEstimatedCost",run.path("reservedEstimatedCost").asDouble()+estimatedCost);ObjectNode layerUsage=next.withObject("layerUsage").withObject(layer);layerUsage.put("usedRequests",layerUsage.path("usedRequests").asLong()+1);store.update(NOVEL_INTELLIGENCE_RUN,runId,revision(run),next);return new Reservation(runId,layer,inputTokens,outputTokens,estimatedCost);});}
    public void complete(Reservation reservation,long actualInput,long actualOutput){if(reservation.runId()==null)return;settle(reservation,Math.max(0,actualInput),Math.max(0,actualOutput),reservation.estimatedCost());}
    public void fail(Reservation reservation){if(reservation.runId()==null)return;settle(reservation,reservation.inputTokens(),reservation.outputTokens(),reservation.estimatedCost());}
    public List<ObjectNode> list(String novelId){ObjectNode source=store.get(com.yourapp.drama.persistence.ResourceKind.NOVEL_SOURCE,novelId);return store.list(NOVEL_INTELLIGENCE_RUN,project(source),null).stream().filter(run->novelId.equals(text(run,"novelId"))).toList();}
    public ObjectNode get(String runId){return store.get(NOVEL_INTELLIGENCE_RUN,runId);}
    public void progress(String phase,long completed,long total){String runId=current.get();if(runId==null)return;store.transaction(()->{ObjectNode run=store.getForUpdate(NOVEL_INTELLIGENCE_RUN,runId),next=run.deepCopy().put("phase",phase).put("completedUnits",completed).put("totalUnits",total);store.update(NOVEL_INTELLIGENCE_RUN,runId,revision(run),next);return null;});}
    public void provider(String model,String requestId){String runId=current.get();if(runId==null)return;store.transaction(()->{ObjectNode run=store.getForUpdate(NOVEL_INTELLIGENCE_RUN,runId),next=run.deepCopy().put("model",model==null?"":model);if(requestId!=null&&!requestId.isBlank())next.put("providerRequestId",requestId);store.update(NOVEL_INTELLIGENCE_RUN,runId,revision(run),next);return null;});}

    private ObjectNode create(ObjectNode novel,String type,String profile,ObjectNode request,Estimate estimate){if(gate.liveMode()&&!request.path("liveConfirmed").asBoolean())throw new WorkflowException("NOVEL_INTELLIGENCE_LIVE_CONFIRMATION_REQUIRED","真实小说智能必须由用户在页面明确确认");ObjectNode limits=request.path("budget").isObject()?(ObjectNode)request.path("budget").deepCopy():obj();if(!gate.liveMode()){limits.putIfAbsent("maxRequests",com.fasterxml.jackson.databind.node.LongNode.valueOf(Math.max(1,estimate.requests())));limits.putIfAbsent("maxInputTokens",com.fasterxml.jackson.databind.node.LongNode.valueOf(Math.max(1,estimate.inputTokens())));limits.putIfAbsent("maxOutputTokens",com.fasterxml.jackson.databind.node.LongNode.valueOf(Math.max(1,estimate.outputTokens())));limits.putIfAbsent("maxEstimatedCost",com.fasterxml.jackson.databind.node.DoubleNode.valueOf(Math.max(0,estimate.estimatedCost())));}guard.validate(limits);ObjectNode value=obj().put("projectId",project(novel)).put("novelId",id(novel)).put("type",type).put("profile",profile).put("status","RUNNING").put("model","").put("maxRequests",limits.path("maxRequests").asLong()).put("maxInputTokens",limits.path("maxInputTokens").asLong()).put("maxOutputTokens",limits.path("maxOutputTokens").asLong()).put("maxEstimatedCost",limits.path("maxEstimatedCost").asDouble()).put("usedRequests",0).put("usedInputTokens",0).put("usedOutputTokens",0).put("usedEstimatedCost",0).put("reservedInputTokens",0).put("reservedOutputTokens",0).put("reservedEstimatedCost",0).put("pricingStatus","UNPRICED").put("startedAt",Instant.now().toString());value.set("estimate",obj().put("requests",estimate.requests()).put("inputTokens",estimate.inputTokens()).put("outputTokens",estimate.outputTokens()).put("estimatedCost",estimate.estimatedCost()));value.set("layerLimits",estimate.layerLimits()==null?obj():estimate.layerLimits().deepCopy());value.putObject("layerUsage");return store.create(NOVEL_INTELLIGENCE_RUN,value);}
    private ObjectNode resumable(String novelId,String type){return list(novelId).stream().filter(run->type.equals(text(run,"type"))&&Set.of("FAILED","PARTIAL_FAILED","RUNNING","RECONCILIATION_REQUIRED").contains(text(run,"status"))).max(Comparator.comparing(run->text(run,"createdAt"))).orElse(null);}
    private void settle(Reservation reservation,long input,long output,double cost){store.transaction(()->{ObjectNode run=store.getForUpdate(NOVEL_INTELLIGENCE_RUN,reservation.runId()),next=run.deepCopy().put("reservedInputTokens",Math.max(0,run.path("reservedInputTokens").asLong()-reservation.inputTokens())).put("reservedOutputTokens",Math.max(0,run.path("reservedOutputTokens").asLong()-reservation.outputTokens())).put("reservedEstimatedCost",Math.max(0,run.path("reservedEstimatedCost").asDouble()-reservation.estimatedCost())).put("usedInputTokens",run.path("usedInputTokens").asLong()+input).put("usedOutputTokens",run.path("usedOutputTokens").asLong()+output).put("usedEstimatedCost",run.path("usedEstimatedCost").asDouble()+cost);store.update(NOVEL_INTELLIGENCE_RUN,reservation.runId(),revision(run),next);return null;});}
    private void finishRun(String runId,String status,RuntimeException error){store.transaction(()->{ObjectNode run=store.getForUpdate(NOVEL_INTELLIGENCE_RUN,runId),next=run.deepCopy().put("status",status).put("completedAt",Instant.now().toString());if(error!=null){next.put("failureCode",error instanceof ProviderException pe?pe.code():error instanceof WorkflowException we?we.code():"NOVEL_INTELLIGENCE_FAILED").put("failureReason",String.valueOf(error.getMessage()));if(error instanceof ProviderException pe&&pe.requestId()!=null)next.put("providerRequestId",pe.requestId());}store.update(NOVEL_INTELLIGENCE_RUN,runId,revision(run),next);return null;});}
}
