package com.yourapp.drama.workflow;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.xml.stream.*;
import java.io.*;
import java.nio.charset.*;
import java.nio.file.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.zip.*;

@Component
public class NovelDocumentParser {
    private final long maxUncompressed;private final int maxEntries;private final double maxRatio;
    public NovelDocumentParser(@Value("${novel.parse.max-uncompressed-size:1073741824}")long maxUncompressed,@Value("${novel.parse.max-entries:20000}")int maxEntries,@Value("${novel.parse.max-compression-ratio:100}")double maxRatio){this.maxUncompressed=maxUncompressed;this.maxEntries=maxEntries;this.maxRatio=maxRatio;}
    public String parse(Path file,String format,Consumer<String> paragraphs){return switch(format){case "TXT"->txt(file,paragraphs);case "DOCX"->{archive(file);xmlText(file,"word/document.xml",paragraphs,Set.of("p"));yield "UTF-8";}case "EPUB"->{archive(file);epub(file,paragraphs);yield "UTF-8";}default->throw new IllegalArgumentException("不支持的小说格式");};}
    private String txt(Path file,Consumer<String> paragraphs){Charset charset;if(valid(file,StandardCharsets.UTF_8))charset=StandardCharsets.UTF_8;else if(valid(file,Charset.forName("GB18030")))charset=Charset.forName("GB18030");else throw new WorkflowException("ENCODING_REVIEW_REQUIRED","TXT 编码无法可靠识别，请人工选择编码");try(BufferedReader reader=Files.newBufferedReader(file,charset)){String line;boolean first=true;while((line=reader.readLine())!=null){if(first&&!line.isEmpty()&&line.charAt(0)=='\ufeff')line=line.substring(1);first=false;paragraphs.accept(line);}}catch(IOException e){throw new UncheckedIOException("读取 TXT 失败",e);}return charset.name();}
    private boolean valid(Path file,Charset charset){try(Reader reader=new InputStreamReader(Files.newInputStream(file),charset.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT))){char[] buffer=new char[64*1024];while(reader.read(buffer)>=0){}return true;}catch(IOException e){return false;}}
    private void archive(Path file){long total=0;int count=0;try(ZipFile zip=new ZipFile(file.toFile(),StandardCharsets.UTF_8)){for(Enumeration<? extends ZipEntry> entries=zip.entries();entries.hasMoreElements();){ZipEntry entry=entries.nextElement();count++;if(count>maxEntries)throw new WorkflowException("ARCHIVE_ENTRY_LIMIT","压缩包文件数量超过限制");String name=entry.getName().replace('\\','/');if(name.startsWith("/")||name.contains("../")||name.equals(".."))throw new WorkflowException("ZIP_TRAVERSAL","压缩包包含越界路径");long size=Math.max(0,entry.getSize()),compressed=entry.getCompressedSize();total+=size;if(total>maxUncompressed)throw new WorkflowException("ZIP_BOMB","压缩包解压大小超过限制");if(compressed>0&&size/(double)compressed>maxRatio)throw new WorkflowException("ZIP_BOMB","压缩倍率超过限制");}}catch(IOException e){throw new WorkflowException("ARCHIVE_INVALID","DOCX/EPUB 压缩结构无效");}}
    private void epub(Path file,Consumer<String> paragraphs){try(ZipFile zip=new ZipFile(file.toFile(),StandardCharsets.UTF_8)){String opf=containerPath(zip);Map<String,String> manifest=new LinkedHashMap<>();List<String> spine=new ArrayList<>();XMLInputFactory factory=xmlFactory();try(InputStream input=entry(zip,opf)){XMLStreamReader reader=factory.createXMLStreamReader(input);while(reader.hasNext()){int event=reader.next();if(event==XMLStreamConstants.START_ELEMENT&&reader.getLocalName().equals("item"))manifest.put(attribute(reader,"id"),attribute(reader,"href"));if(event==XMLStreamConstants.START_ELEMENT&&reader.getLocalName().equals("itemref"))spine.add(attribute(reader,"idref"));}}String base=opf.contains("/")?opf.substring(0,opf.lastIndexOf('/')+1):"";for(String id:spine){String href=manifest.get(id);if(href==null)continue;String path=normalize(base,href);xmlText(zip,path,paragraphs,Set.of("p","div","h1","h2","h3","li"));}}catch(XMLStreamException|IOException e){throw new WorkflowException("EPUB_PARSE_FAILED","EPUB 阅读顺序或 XHTML 无法解析");}}
    private String containerPath(ZipFile zip)throws IOException,XMLStreamException{XMLInputFactory factory=xmlFactory();try(InputStream input=entry(zip,"META-INF/container.xml")){XMLStreamReader reader=factory.createXMLStreamReader(input);while(reader.hasNext()){if(reader.next()==XMLStreamConstants.START_ELEMENT&&reader.getLocalName().equals("rootfile")){String path=attribute(reader,"full-path");if(path!=null&&!path.isBlank())return normalize("",path);}}}throw new WorkflowException("EPUB_OPF_MISSING","EPUB 缺少 OPF 路径");}
    private void xmlText(Path file,String entry,Consumer<String> paragraphs,Set<String> blocks){try(ZipFile zip=new ZipFile(file.toFile(),StandardCharsets.UTF_8)){xmlText(zip,entry,paragraphs,blocks);}catch(IOException e){throw new UncheckedIOException(e);}}
    private void xmlText(ZipFile zip,String name,Consumer<String> paragraphs,Set<String> blocks){try(InputStream input=entry(zip,name)){XMLStreamReader reader=xmlFactory().createXMLStreamReader(input);StringBuilder text=new StringBuilder();int skip=0;while(reader.hasNext()){int event=reader.next();String local=reader.hasName()?reader.getLocalName():"";if(event==XMLStreamConstants.START_ELEMENT&&(local.equalsIgnoreCase("script")||local.equalsIgnoreCase("style")))skip++;else if(event==XMLStreamConstants.END_ELEMENT&&(local.equalsIgnoreCase("script")||local.equalsIgnoreCase("style")))skip=Math.max(0,skip-1);else if(event==XMLStreamConstants.CHARACTERS&&skip==0)text.append(reader.getText());else if(event==XMLStreamConstants.END_ELEMENT&&blocks.contains(local.toLowerCase(Locale.ROOT))){String value=text.toString().replaceAll("\\s+"," ").trim();if(!value.isBlank())paragraphs.accept(value);text.setLength(0);}}String value=text.toString().replaceAll("\\s+"," ").trim();if(!value.isBlank())paragraphs.accept(value);}catch(XMLStreamException|IOException e){throw new WorkflowException("ARCHIVE_XML_INVALID","文档 XML 无法安全解析");}}
    private static XMLInputFactory xmlFactory(){XMLInputFactory factory=XMLInputFactory.newFactory();factory.setProperty(XMLInputFactory.SUPPORT_DTD,false);factory.setProperty("javax.xml.stream.isSupportingExternalEntities",false);return factory;}
    private static InputStream entry(ZipFile zip,String name)throws IOException{ZipEntry entry=zip.getEntry(name);if(entry==null)throw new FileNotFoundException(name);return zip.getInputStream(entry);}
    private static String normalize(String base,String value){String decoded=value.split("#",2)[0].replace('\\','/');Path path=Path.of(base).resolve(decoded).normalize();String result=path.toString().replace('\\','/');if(result.startsWith("../")||result.equals("..")||result.startsWith("/"))throw new WorkflowException("ZIP_TRAVERSAL","压缩包引用越界");return result;}
    private static String attribute(XMLStreamReader reader,String name){for(int i=0;i<reader.getAttributeCount();i++)if(reader.getAttributeLocalName(i).equals(name))return reader.getAttributeValue(i);return null;}
}
