package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yourapp.drama.job.JobService;
import com.yourapp.drama.persistence.DocumentStore;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.*;

import static com.yourapp.drama.persistence.ResourceKind.*;
import static com.yourapp.drama.workflow.Documents.*;

@Service
public class ScriptWorkspaceService {
    private static final Set<String> EDITABLE_STATUS=Set.of("DRAFT","REVIEW");
    private final DocumentStore store;private final ScriptDiffService diffs;private final DependencyRevisionService revisions;private final JobService jobs;
    public ScriptWorkspaceService(DocumentStore store,ScriptDiffService diffs,DependencyRevisionService revisions,JobService jobs){this.store=store;this.diffs=diffs;this.revisions=revisions;this.jobs=jobs;}

    public List<ObjectNode> projectScripts(String projectId){return store.list(EPISODE_SCRIPT_VERSION,projectId,null);}
    public ObjectNode get(String id){return store.get(EPISODE_SCRIPT_VERSION,id);}
    public ObjectNode current(String episodeId){
        ObjectNode episode=store.get(EPISODE,episodeId);List<ObjectNode> versions=versions(episode);
        if(versions.isEmpty())return baseline(episode);
        return versions.stream().filter(v->!"SUPERSEDED".equals(text(v,"status"))).max(Comparator.comparingInt(v->v.path("version").asInt())).orElse(versions.getLast());
    }
    public ObjectNode createReviewVersion(String episodeId,JsonNode structured,String sourceMode,String createdBy,ObjectNode provenance){
        ObjectNode episode=store.get(EPISODE,episodeId);validateStructured(structured);List<ObjectNode> versions=versions(episode);int next=versions.stream().mapToInt(v->v.path("version").asInt()).max().orElse(0)+1;
        ObjectNode value=obj().put("projectId",project(episode)).put("episodeId",episodeId).put("version",next).put("status","REVIEW").put("createdBy",createdBy).put("changeType","AI_SCRIPT_REVISION").put("changeReason","GENERATED_FOR_REVIEW").put("changeSummary","生成待审查剧本").put("ownership","AI_GENERATED").put("sourceMode",normalizeSourceMode(sourceMode)).put("contentHash",DependencyRevisionService.hash(structured));
        value.set("structuredContent",structured.deepCopy());value.put("rawText",structured.path("rawText").asText(structured.path("script").asText("")));if(provenance!=null){value.set("sourceProvenance",provenance.deepCopy());for(String field:List.of("adaptationPlanId","episodeAdaptationPlanId","contextHash","importStatus"))if(provenance.hasNonNull(field))value.set(field,provenance.path(field).deepCopy());}return store.create(EPISODE_SCRIPT_VERSION,value);
    }
    public ObjectNode fork(String episodeId,ObjectNode request){
        return store.transaction(()->{ObjectNode base=current(episodeId);requireRevision(base,request);ObjectNode value=copyForNew(base).put("version",base.path("version").asInt()+1).put("status","DRAFT").put("supersedesId",id(base)).put("sourceVersionId",id(base)).put("createdBy",request.path("createdBy").asText("USER")).put("changeType","HUMAN_SCRIPT_EDIT").put("changeReason",request.path("changeReason").asText("USER_EDIT")).put("changeSummary",request.path("changeSummary").asText("人工编辑剧本"));ObjectNode saved=store.create(EPISODE_SCRIPT_VERSION,value);protectInFlightJobs(base);return saved;});
    }
    public ObjectNode update(String versionId,ObjectNode request){
        return store.transaction(()->{ObjectNode current=store.getForUpdate(EPISODE_SCRIPT_VERSION,versionId);requireRevision(current,request);if(!EDITABLE_STATUS.contains(text(current,"status")))throw new WorkflowException("SCRIPT_VERSION_IMMUTABLE","只有草稿或待审查版本可以编辑");JsonNode structured=request.path("structuredContent");if(!structured.isObject())structured=current.path("structuredContent");validateStructured(structured);ObjectNode next=current.deepCopy();next.set("structuredContent",structured.deepCopy());next.put("rawText",request.path("rawText").asText(text(current,"rawText"))).put("contentHash",DependencyRevisionService.hash(structured)).put("ownership","HUMAN_EDITED");if(structured.hasNonNull("importStatus")){String importStatus=text(structured,"importStatus");next.put("importStatus",importStatus);if(next.path("sourceProvenance").isObject())((ObjectNode)next.path("sourceProvenance")).put("importStatus",importStatus);}if(request.hasNonNull("status")){String status=text(request,"status");if(!EDITABLE_STATUS.contains(status))throw new IllegalArgumentException("编辑只能保存为 DRAFT 或 REVIEW");next.put("status",status);}return store.update(EPISODE_SCRIPT_VERSION,versionId,revision(current),next);});
    }
    public ObjectNode updateByAi(String versionId,ObjectNode proposed){
        ObjectNode current=store.get(EPISODE_SCRIPT_VERSION,versionId);if(hasChangedHumanLock(current.path("structuredContent"),proposed))throw new WorkflowException("HUMAN_LOCKED_CONTENT","AI 改写不能覆盖人工锁定内容");ObjectNode request=current.deepCopy();request.set("structuredContent",proposed.deepCopy());return update(versionId,request);
    }
    public ObjectNode confirm(String versionId,ObjectNode request){
        return store.transaction(()->{ObjectNode version=store.getForUpdate(EPISODE_SCRIPT_VERSION,versionId);requireRevision(version,request);if(!EDITABLE_STATUS.contains(text(version,"status"))&&!"CONFIRMED".equals(text(version,"status")))throw new WorkflowException("SCRIPT_NOT_REVIEWABLE","当前剧本版本不能确认");if("IMPORT_REVIEW_REQUIRED".equals(text(version.path("structuredContent"),"importStatus")))throw new WorkflowException("SCRIPT_IMPORT_REVIEW_REQUIRED","导入剧本包含未识别内容，必须人工复核并标记完成后才能确认");String projectId=project(version),episodeId=required(version,"episodeId");for(ObjectNode old:versions(store.get(EPISODE,episodeId)))if(!id(old).equals(versionId)&&"CONFIRMED".equals(text(old,"status")))store.update(EPISODE_SCRIPT_VERSION,id(old),revision(old),old.deepCopy().put("status","SUPERSEDED"));ObjectNode snapshot=snapshot(version);ObjectNode next=version.deepCopy().put("status","CONFIRMED").put("confirmedAt",Instant.now().toString()).put("productionScriptSnapshotId",id(snapshot));ObjectNode saved=store.update(EPISODE_SCRIPT_VERSION,versionId,revision(version),next);ObjectNode episode=store.getForUpdate(EPISODE,episodeId);store.update(EPISODE,episodeId,revision(episode),episode.deepCopy().put("confirmedScriptVersionId",versionId).put("scriptVersionId",versionId).put("productionScriptSnapshotId",id(snapshot)).put("productionReady",true).put("scriptReviewStatus","CONFIRMED"));return saved;});
    }
    public ObjectNode rollback(String versionId,ObjectNode request){ObjectNode source=store.get(EPISODE_SCRIPT_VERSION,versionId);ObjectNode current=current(required(source,"episodeId"));ObjectNode body=obj().put("revision",revision(current)).put("createdBy",request.path("createdBy").asText("USER")).put("changeReason","ROLLBACK").put("changeSummary","回滚到版本 "+source.path("version").asInt());ObjectNode draft=fork(required(source,"episodeId"),body);ObjectNode edit=draft.deepCopy();edit.set("structuredContent",source.path("structuredContent").deepCopy());edit.put("rawText",text(source,"rawText"));return update(id(draft),edit);}
    public ObjectNode diff(String from,String to){ObjectNode a=get(from),b=get(to);if(!project(a).equals(project(b)))throw new IllegalArgumentException("只能比较同一项目的剧本版本");ObjectNode result=diffs.compare(a.path("structuredContent"),b.path("structuredContent"));result.put("fromVersionId",from).put("toVersionId",to);return result;}
    public ObjectNode requireProductionReady(String episodeId,String requestedVersionId){ObjectNode episode=store.get(EPISODE,episodeId);if(!episode.path("productionReady").asBoolean()||text(episode,"productionScriptSnapshotId").isBlank())throw new WorkflowException("SCRIPT_REVIEW_REQUIRED","请先在剧本工作台确认当前版本");ObjectNode snapshot=store.get(PRODUCTION_SCRIPT_SNAPSHOT,text(episode,"productionScriptSnapshotId"));if(requestedVersionId!=null&&!requestedVersionId.isBlank()&&!requestedVersionId.equals(text(snapshot,"scriptVersionId")))throw new WorkflowException("STALE_SCRIPT_VERSION","任务引用的剧本版本已经过期");return snapshot;}

    private ObjectNode baseline(ObjectNode episode){String legacyId=text(episode,"storyDocumentId");if(legacyId.isBlank())throw new WorkflowException("SCRIPT_VERSION_MISSING","本集尚无剧本版本");ObjectNode legacy=store.get(STORY_DOCUMENT,legacyId);ObjectNode structured=legacyStructured(legacy.path("content"));String status="CONFIRMED".equals(text(legacy,"reviewStatus"))?"CONFIRMED":"REVIEW";ObjectNode value=obj().put("projectId",project(episode)).put("episodeId",id(episode)).put("version",1).put("status",status).put("createdBy","SYSTEM").put("changeType","MIGRATED_BASELINE").put("changeReason","MIGRATED_BASELINE").put("changeSummary","从旧剧本建立工作台基线").put("ownership","AI_GENERATED").put("sourceMode",sourceMode(project(episode))).put("contentHash",DependencyRevisionService.hash(structured)).put("legacyStoryDocumentId",legacyId).put("rawText",structured.path("script").asText(""));value.set("structuredContent",structured.deepCopy());ObjectNode saved=store.create(EPISODE_SCRIPT_VERSION,value);if("CONFIRMED".equals(status))return confirm(id(saved),obj().put("revision",revision(saved)));return saved;}
    private ObjectNode snapshot(ObjectNode version){String projectId=project(version),episodeId=required(version,"episodeId");for(ObjectNode existing:store.list(PRODUCTION_SCRIPT_SNAPSHOT,projectId,episodeId))if(id(version).equals(text(existing,"scriptVersionId")))return existing;revisions.ensureBaseline(projectId);ObjectNode entities=obj();entities.set("characterDefinitionVersionIds",ids(store.list(CHARACTER_DEFINITION_VERSION,projectId,null)));entities.set("characterLookVersionIds",ids(store.list(CHARACTER_LOOK,projectId,null)));entities.set("locationDefinitionVersionIds",ids(store.list(LOCATION_DEFINITION_VERSION,projectId,null)));entities.set("propDefinitionVersionIds",ids(store.list(PROP_DEFINITION_VERSION,projectId,null)));String continuity=DependencyRevisionService.hash(obj().set("entities",entities.deepCopy()));ObjectNode value=obj().put("projectId",projectId).put("episodeId",episodeId).put("scriptVersionId",id(version)).put("scriptHash",text(version,"contentHash")).put("confirmedAt",Instant.now().toString()).put("continuitySnapshotHash",continuity);value.set("entityVersionSnapshot",entities);return store.create(PRODUCTION_SCRIPT_SNAPSHOT,value);}
    private void protectInFlightJobs(ObjectNode base){for(ObjectNode job:store.list(GENERATION_JOB,project(base),null))if(id(base).equals(text(job.path("inputSnapshot"),"scriptVersionId"))){String status=text(job,"status");if(Set.of("QUEUED","RETRY_WAIT").contains(status)&&text(job,"providerRequestId").isBlank()&&text(job,"providerTaskId").isBlank())jobs.cancel(id(job));else if("RUNNING".equals(status))store.update(GENERATION_JOB,id(job),revision(job),job.deepCopy().put("staleResultExpected",true));}}
    private List<ObjectNode> versions(ObjectNode episode){List<ObjectNode> result=new ArrayList<>(store.list(EPISODE_SCRIPT_VERSION,project(episode),id(episode)));result.sort(Comparator.comparingInt(v->v.path("version").asInt()));return result;}
    private String sourceMode(String projectId){return normalizeSourceMode(text(store.get(PROJECT,projectId),"sourceMode"));}
    private static String normalizeSourceMode(String value){return Set.of("NOVEL","SCRIPT").contains(value)?value:"IDEA";}
    private static ObjectNode copyForNew(ObjectNode source){ObjectNode value=obj();for(String field:List.of("projectId","episodeId","sourceMode","ownership","rawText","sourceProvenance","adaptationPlanId","episodeAdaptationPlanId","contextHash","importStatus"))if(source.has(field))value.set(field,source.path(field).deepCopy());value.set("structuredContent",source.path("structuredContent").deepCopy());value.put("contentHash",text(source,"contentHash"));return value;}
    private static void requireRevision(ObjectNode current,JsonNode request){long expected=request.path("revision").asLong(-1);if(expected<1)throw new IllegalArgumentException("修改必须包含 revision");if(expected!=revision(current))throw new com.yourapp.drama.persistence.RevisionConflictException(EPISODE_SCRIPT_VERSION,id(current));}
    private static void validateStructured(JsonNode value){if(!value.isObject())throw new IllegalArgumentException("structuredContent 必须是对象");for(String field:List.of("title","summary","openingHook","endingHook"))if(!value.path(field).isTextual())throw new IllegalArgumentException("structuredContent 缺少 "+field);if(!value.path("scenes").isArray())throw new IllegalArgumentException("structuredContent.scenes 必须是数组");}
    private static ObjectNode legacyStructured(JsonNode value){if(!value.isObject())throw new IllegalArgumentException("旧剧本 content 必须是对象");ObjectNode result=(ObjectNode)value.deepCopy();for(String field:List.of("title","summary","openingHook","endingHook"))result.putIfAbsent(field,com.fasterxml.jackson.databind.node.TextNode.valueOf(""));if(!result.path("scenes").isArray())result.putArray("scenes");return result;}
    private static ArrayNode ids(List<ObjectNode> values){ArrayNode result=obj().putArray("ids");values.stream().sorted(Comparator.comparing(Documents::createdAt)).forEach(value->result.add(id(value)));return result;}
    private static boolean hasChangedHumanLock(JsonNode current,JsonNode proposed){Map<String,JsonNode> proposedByKey=new HashMap<>();proposed.findValues("lineKey").forEach(v->{});for(JsonNode scene:proposed.path("scenes"))for(JsonNode dialogue:scene.path("dialogues"))proposedByKey.put(text(dialogue,"lineKey"),dialogue);for(JsonNode scene:current.path("scenes"))for(JsonNode dialogue:scene.path("dialogues"))if("HUMAN_LOCKED".equals(text(dialogue,"ownership"))&&!dialogue.equals(proposedByKey.get(text(dialogue,"lineKey"))))return true;return false;}
}
