package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yourapp.drama.persistence.DocumentStore;
import com.yourapp.drama.persistence.ResourceKind;
import org.springframework.stereotype.Service;

import java.util.*;

import static com.yourapp.drama.persistence.ResourceKind.*;
import static com.yourapp.drama.workflow.Documents.*;

@Service
public class SourceTraceabilityService {
    private final DocumentStore store;
    public SourceTraceabilityService(DocumentStore store){this.store=store;}
    public ObjectNode scriptVersion(String versionId){ObjectNode version=store.get(EPISODE_SCRIPT_VERSION,versionId);return traceVersion(version,refs(version.path("sourceProvenance").path("sourceChunkIds"),version.path("structuredContent").path("sourceRefs")));}
    public ObjectNode scriptElement(String versionId,String type,String key){ObjectNode version=store.get(EPISODE_SCRIPT_VERSION,versionId),found=null;String normalized=type.toUpperCase(Locale.ROOT);for(JsonNode scene:version.path("structuredContent").path("scenes")){if("SCENE".equals(normalized)&&key.equals(text(scene,"sceneKey")))found=(ObjectNode)scene;for(JsonNode dialogue:scene.path("dialogues"))if("DIALOGUE".equals(normalized)&&key.equals(text(dialogue,"lineKey")))found=(ObjectNode)dialogue;}if(found==null)throw new WorkflowException("SCRIPT_ELEMENT_NOT_FOUND","剧本元素不存在");ObjectNode result=traceVersion(version,refs(found.path("sourceRefs"),version.path("sourceProvenance").path("sourceChunkIds")));result.put("elementType",normalized).put("elementKey",key);result.set("element",found.deepCopy());return result;}
    public ObjectNode reverseChapter(String chapterId){ObjectNode chapter=store.get(NOVEL_CHAPTER,chapterId);String projectId=project(chapter);Set<String> chunkIds=new LinkedHashSet<>();store.list(NOVEL_CHUNK,projectId,chapterId).forEach(chunk->chunkIds.add(id(chunk)));ObjectNode result=obj();result.set("novelChapter",chapter.deepCopy());ArrayNode episodeResults=result.putArray("episodes"),sceneResults=result.putArray("scenes"),dialogueResults=result.putArray("dialogues");Set<String> planEpisodeIds=new LinkedHashSet<>();for(ObjectNode plan:store.list(EPISODE_ADAPTATION_PLAN,projectId,null))if(contains(plan.path("sourceChapterIds"),chapterId)){planEpisodeIds.add(id(plan));episodeResults.add(plan.deepCopy());}for(ObjectNode version:store.list(EPISODE_SCRIPT_VERSION,projectId,null)){if(!planEpisodeIds.contains(text(version,"episodeAdaptationPlanId")))continue;for(JsonNode scene:version.path("structuredContent").path("scenes")){if(overlaps(scene.path("sourceRefs"),chunkIds)){ObjectNode hit=((ObjectNode)scene).deepCopy().put("scriptVersionId",id(version)).put("episodeId",text(version,"episodeId"));sceneResults.add(hit);}for(JsonNode dialogue:scene.path("dialogues"))if(overlaps(dialogue.path("sourceRefs"),chunkIds)){ObjectNode hit=((ObjectNode)dialogue).deepCopy().put("scriptVersionId",id(version)).put("episodeId",text(version,"episodeId"));dialogueResults.add(hit);}}}return result;}
    public ObjectNode media(ResourceKind kind,String id){
        if(!Set.of(VIDEO_TAKE,KEYFRAME,PROMPT_VERSION,TIMELINE,TIMELINE_ITEM,GENERATION_JOB).contains(kind))throw new IllegalArgumentException("媒体溯源仅支持渲染任务、时间线、视频、关键帧和提示词版本");
        ObjectNode artifact=store.get(kind,id),result=obj().put("tracedFromKind",kind.path()).put("tracedFromId",id);result.set("artifact",artifact.deepCopy());
        if(kind==GENERATION_JOB){if(!"RENDER".equals(text(artifact,"type")))throw new IllegalArgumentException("只有 RENDER 任务可以作为成片溯源入口");String timelineId=required(artifact.path("inputSnapshot"),"timelineId");result.set("renderJob",artifact.deepCopy());return traceTimeline(store.get(TIMELINE,timelineId),result);}
        if(kind==TIMELINE)return traceTimeline(artifact,result);
        if(kind==TIMELINE_ITEM){result.set("timelineItem",artifact.deepCopy());String takeId=text(artifact,"videoTakeId");if(!takeId.isBlank())result.set("mediaLineage",media(VIDEO_TAKE,takeId));return result;}
        return traceMediaArtifact(kind,artifact,result);
    }
    private ObjectNode traceTimeline(ObjectNode timeline,ObjectNode result){result.set("timeline",timeline.deepCopy());ArrayNode lineages=result.putArray("mediaLineages");for(ObjectNode item:store.list(TIMELINE_ITEM,project(timeline),id(timeline))){String takeId=text(item,"videoTakeId");if(takeId.isBlank())continue;ObjectNode lineage=media(VIDEO_TAKE,takeId);lineage.set("timelineItem",item.deepCopy());lineages.add(lineage);}if(lineages.isEmpty()){String versionId=first(text(timeline,"lastRenderScriptVersionId"),text(timeline,"scriptVersionId"));if(!versionId.isBlank())lineages.add(traceVersion(store.get(EPISODE_SCRIPT_VERSION,versionId),Set.of()));}return result;}
    private ObjectNode traceMediaArtifact(ResourceKind kind,ObjectNode artifact,ObjectNode result){ObjectNode keyframe=null,prompt=null,snapshot=null,version=null;if(kind==VIDEO_TAKE){String keyframeId=text(artifact,"sourceKeyframeId");if(!keyframeId.isBlank()){keyframe=store.get(KEYFRAME,keyframeId);result.set("keyframe",keyframe.deepCopy());}}else if(kind==KEYFRAME)keyframe=artifact;if(kind==PROMPT_VERSION)prompt=artifact;String promptId=first(text(artifact,"promptVersionId"),keyframe==null?"":text(keyframe,"promptVersionId"));if(prompt==null&&!promptId.isBlank()){prompt=store.get(PROMPT_VERSION,promptId);result.set("promptVersion",prompt.deepCopy());}String snapshotId=first(text(artifact,"productionInputSnapshotId"),keyframe==null?"":text(keyframe,"productionInputSnapshotId"),prompt==null?"":text(prompt,"productionInputSnapshotId"));if(!snapshotId.isBlank()){snapshot=store.get(PRODUCTION_INPUT_SNAPSHOT,snapshotId);result.set("productionInputSnapshot",snapshot.deepCopy());String versionId=text(snapshot,"scriptVersionId");if(!versionId.isBlank())version=store.get(EPISODE_SCRIPT_VERSION,versionId);}if(version==null){String versionId=text(artifact,"scriptVersionId");if(!versionId.isBlank())version=store.get(EPISODE_SCRIPT_VERSION,versionId);}if(version!=null)result.setAll(traceVersion(version,refs(version.path("sourceProvenance").path("sourceChunkIds"),snapshot==null?null:snapshot.path("sourceChunkIds"))));return result;}
    private ObjectNode traceVersion(ObjectNode version,Set<String> chunkIds){ObjectNode result=obj();result.set("scriptVersion",version.deepCopy());String episodePlanId=first(text(version,"episodeAdaptationPlanId"),text(version.path("sourceProvenance"),"episodeAdaptationPlanId")),planId=first(text(version,"adaptationPlanId"),text(version.path("sourceProvenance"),"adaptationPlanId"));if(!episodePlanId.isBlank())result.set("episodeAdaptationPlan",store.get(EPISODE_ADAPTATION_PLAN,episodePlanId).deepCopy());if(!planId.isBlank())result.set("adaptationPlan",store.get(ADAPTATION_PLAN,planId).deepCopy());ArrayNode chunks=result.putArray("novelChunks"),chapters=result.putArray("novelChapters"),references=result.putArray("sourceReferences");Set<String> chapterIds=new LinkedHashSet<>();String novelId="";for(String chunkId:chunkIds){ObjectNode chunk=store.get(NOVEL_CHUNK,chunkId);chunks.add(chunk.deepCopy());chapterIds.add(required(chunk,"chapterId"));novelId=text(chunk,"novelId");for(ObjectNode reference:store.list(SOURCE_REFERENCE,project(version),chunkId))references.add(reference.deepCopy());}chapterIds.forEach(chapterId->chapters.add(store.get(NOVEL_CHAPTER,chapterId).deepCopy()));if(novelId.isBlank()&&!planId.isBlank())novelId=text(store.get(ADAPTATION_PLAN,planId),"novelId");if(!novelId.isBlank())result.set("novelSource",store.get(NOVEL_SOURCE,novelId).deepCopy());return result;}
    private static Set<String> refs(JsonNode... candidates){Set<String> result=new LinkedHashSet<>();for(JsonNode candidate:candidates)if(candidate!=null&&candidate.isArray())candidate.forEach(value->result.add(value.asText()));return result;}
    private static boolean contains(JsonNode values,String expected){for(JsonNode value:values)if(expected.equals(value.asText()))return true;return false;}
    private static boolean overlaps(JsonNode values,Set<String> expected){for(JsonNode value:values)if(expected.contains(value.asText()))return true;return false;}
    private static String first(String... values){for(String value:values)if(value!=null&&!value.isBlank())return value;return "";}
}
