package com.yourapp.drama.workflow;

import com.fasterxml.jackson.databind.node.*;
import com.yourapp.drama.job.*;
import com.yourapp.drama.persistence.*;
import com.yourapp.drama.storage.MediaStorage;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.transaction.annotation.Transactional;
import java.nio.file.*;
import static com.yourapp.drama.persistence.ResourceKind.*;
import static com.yourapp.drama.workflow.Documents.*;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest(properties={"drama.render.ffmpeg=frontend/node_modules/ffmpeg-static/ffmpeg.exe","drama.render.ffprobe=frontend/node_modules/ffprobe-static/bin/win32/x64/ffprobe.exe"})
@ActiveProfiles("test")
@Transactional
class PostProductionIntegrationTest {
    @Autowired DocumentStore store;@Autowired PostProductionService post;@Autowired WorkflowService workflow;@Autowired GenerationWorker worker;@Autowired JobService jobs;@Autowired MediaStorage media;@Autowired AssetViewService assetViews;@Autowired StudioService studio;
    @Test void dialectTtsTimelineAndPreviewRenderComplete()throws Exception{
        assertThat(Path.of("frontend/node_modules/ffmpeg-static/ffmpeg.exe")).as("项目 FFmpeg 运行时").isRegularFile();
        assertThat(Path.of("frontend/node_modules/ffprobe-static/bin/win32/x64/ffprobe.exe")).as("项目 ffprobe 运行时").isRegularFile();
        ObjectNode project=store.create(PROJECT,obj().put("name","后期测试").put("idea","一句方言对白"));ObjectNode episode=store.create(EPISODE,obj().put("projectId",id(project)).put("name","第一集"));ObjectNode scene=store.create(SCENE,obj().put("projectId",id(project)).put("episodeId",id(episode)).put("name","屋内").put("sceneNo",1));ObjectNode location=store.create(LOCATION,obj().put("projectId",id(project)).put("name","屋内").put("locationKey","room").put("description","方桌、北窗和旧木门"));NewWorkflowTestFixtures.install(store,assetViews,project,episode,null,null,location);
        ObjectNode shot=obj().put("projectId",id(project)).put("sceneId",id(scene)).put("locationId",id(location)).put("purpose","说话").put("action","人物平静说出一句话").put("duration",3).put("shotNo",1).put("status","VIDEO_LOCKED").put("directorIntent","SHOW_REACTION").put("shotSize","INSERT");shot.putArray("characterIds");shot.putArray("propIds");shot.putArray("dialogueIds");shot.set("assetViewIds",NewWorkflowTestFixtures.approvedViewIds(store,id(project),id(location)));shot.set("startState",obj());shot.set("endState",obj().put("reviewed",true));shot=store.create(SHOT,shot);
        ObjectNode voiceProfile=store.create(VOICE_PROFILE,obj().put("projectId",id(project)).put("providerVoiceId","fixture-voice").put("approved",true).put("name","测试角色音色"));ObjectNode line=store.create(DIALOGUE_LINE,obj().put("projectId",id(project)).put("shotId",id(shot)).put("semanticText","你今天到哪里去了？").put("subtitleText","你今天去了哪里？").put("dialect","LEIYANG").put("startMs",300).put("endMs",2600).put("voiceProfileId",id(voiceProfile)));ObjectNode correction=obj().put("dialect","LEIYANG");correction.set("correction",obj().put("approved",true).put("spokenText","本地方言发音"));line=post.dialect(id(line),correction);assertThat(text(line,"semanticText")).isEqualTo("你今天到哪里去了？");assertThat(text(line,"subtitleText")).isEqualTo("你今天去了哪里？");assertThat(text(line,"spokenText")).isEqualTo("本地方言发音");
        ObjectNode tts=post.tts(id(line),obj());assertThat(text(tts.path("inputSnapshot"),"spokenText")).isEqualTo("本地方言发音");assertThat(text(tts.path("inputSnapshot"),"subtitleText")).isEqualTo("你今天去了哪里？");assertThat(tts.path("inputSnapshot").path("compilerVersion").asText()).isEqualTo("4.0.0-voice");assertThat(tts.path("inputSnapshot").path("promptIR").path("taskType").asText()).isEqualTo("VOICE");assertThat(tts.path("inputSnapshot").path("prompt").asText()).contains("唯一允许说出的对白：本地方言发音").doesNotContain("你今天到哪里去了？","你今天去了哪里？");worker.tick();assertThat(text(store.get(GENERATION_JOB,id(tts)),"status")).isEqualTo("SUCCESS");ObjectNode clip=store.list(AUDIO_CLIP,id(project),id(shot)).getFirst();clip=workflow.lock(AUDIO_CLIP,id(clip),obj());clip=store.update(AUDIO_CLIP,id(clip),revision(clip),clip.deepCopy().put("providerUrl","https://audio.volces.com/line.mp3"));
        ObjectNode prompt=store.create(PROMPT_VERSION,obj().put("projectId",id(project)).put("shotId",id(shot)).put("purpose","VIDEO").put("version",1).put("prompt","test"));String providerUrl="https://image.volces.com/frame.png?sig=original";ObjectNode frame=store.create(KEYFRAME,obj().put("projectId",id(project)).put("shotId",id(shot)).put("provider","VOLCENGINE").put("sourceModel","seedream").put("providerUrl",providerUrl).put("archiveUrl","/demo/keyframe.svg").put("handoffStatus","HANDED_OFF").put("qcStatus","PASSED").put("locked",true).put("selected",true).set("assetViewIds",NewWorkflowTestFixtures.approvedViewIds(store,id(project),id(location))));
        ObjectNode take=store.create(VIDEO_TAKE,obj().put("projectId",id(project)).put("shotId",id(shot)).put("takeNo",1).put("provider","VOLCENGINE").put("model","seedance").put("promptVersionId",id(prompt)).put("providerRequestId","task-1").put("sourceKeyframeId",id(frame)).put("sourceProviderUrlSnapshot",providerUrl).put("videoUrl","https://video.volces.com/take.mp4").put("archiveUrl","/demo/take.mp4").put("actualDurationMs",3000).put("providerStatus","SUCCEEDED").put("qcStatus","PASSED").put("qcScore",100).put("selected",true).put("locked",true).put("cost",0));
        ObjectNode lipSync=post.lipsync(id(take),obj().put("audioClipId",id(clip)).put("requestKey","lipsync-contract"));assertThat(lipSync.path("inputSnapshot").path("compilerVersion").asText()).isEqualTo("4.0.0-lipsync");assertThat(lipSync.path("inputSnapshot").path("promptIR").path("taskType").asText()).isEqualTo("LIPSYNC");ObjectNode lipPrompt=store.get(PROMPT_VERSION,required(lipSync.path("inputSnapshot"),"promptVersionId"));assertThat(lipPrompt.path("promptIR").path("audio").path("audioClipIds").get(0).asText()).isEqualTo(id(clip));jobs.cancel(id(lipSync));
        ObjectNode timelineJob=post.timeline(id(episode),obj());worker.tick();ObjectNode timelineDone=store.get(GENERATION_JOB,id(timelineJob));assertThat(text(timelineDone,"status")).withFailMessage(timelineDone.toString()).isEqualTo("SUCCESS");ObjectNode timeline=store.list(TIMELINE,id(project),id(episode)).getFirst();assertThat(text(timeline,"srt")).contains("你今天去了哪里？").doesNotContain("本地方言发音","你今天到哪里去了？");ObjectNode dialogueItem=store.list(TIMELINE_ITEM,id(project),id(timeline)).stream().filter(i->"DIALOGUE".equals(text(i,"track"))).findFirst().orElseThrow();assertThat(text(dialogueItem,"ttsReconciliationAction")).isNotBlank();assertThat(dialogueItem.path("ttsEstimatedDurationMs").asLong()).isPositive();assertThat(dialogueItem.path("ttsActualDurationMs").asLong()).isPositive();ObjectNode videoItem=store.list(TIMELINE_ITEM,id(project),id(timeline)).stream().filter(i->"VIDEO".equals(text(i,"track"))).findFirst().orElseThrow();assertThat(videoItem.path("locked").asBoolean()).isFalse();assertThat(videoItem.path("sourceInMs").asLong()).isZero();assertThat(videoItem.path("sourceOutMs").asLong()).isEqualTo(3000);assertThat(videoItem.path("editOperations").toString()).contains("CUT","REACTION_SHOT","INSERT_SHOT");videoItem=studio.update(TIMELINE_ITEM,id(videoItem),obj().put("revision",revision(videoItem)).put("sourceOutMs",2800).put("durationMs",2800));assertThat(videoItem.path("editOperations").toString()).contains("TRIM","REACTION_SHOT","INSERT_SHOT");timeline=store.get(TIMELINE,id(timeline));assertThat(timeline.path("contentRevision").asLong()).isEqualTo(2);assertThat(timeline.path("previewStale").asBoolean()).isTrue();ObjectNode render=post.render(id(timeline),obj().put("quality","PREVIEW"));worker.tick();ObjectNode finished=store.get(GENERATION_JOB,id(render));assertThat(text(finished,"status")).withFailMessage(finished.toString()).isEqualTo("SUCCESS");timeline=store.get(TIMELINE,id(timeline));assertThat(timeline.path("previewTimelineRevision").asLong()).isEqualTo(render.path("inputSnapshot").path("timelineRevision").asLong());ObjectNode qa=ReflectionTestUtils.invokeMethod(post,"quality",id(timeline));assertThat(qa.path("passed").asBoolean()).isTrue();timeline=workflow.lock(TIMELINE,id(timeline),obj());assertThat(timeline.path("locked").asBoolean()).isTrue();String url=required(finished.path("outputSnapshot"),"videoUrl");assertThat(url).startsWith("/api/media/renders/");try(var result=media.open(url.substring("/api/media/".length()))){assertThat(result.readAllBytes().length).isGreaterThan(1024);}
    }
}
