package com.yourapp.drama.production;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import org.junit.jupiter.api.Test; import java.io.InputStream; import static org.assertj.core.api.Assertions.*; import static com.yourapp.drama.workflow.Documents.obj;
class ProductionAcceptanceTest { private final ObjectMapper mapper=new ObjectMapper();
 @Test void fiveUnadaptedGenresProduceBoundedProviderRequests() throws Exception {JsonNode fixtures=read();assertThat(fixtures).hasSize(5);for(JsonNode fixture:fixtures){ObjectNode request=request(fixture);var compiled=new PromptCompiler(mapper,new ContinuityEngine(mapper)).compileImage(request);assertThat(compiled.prompt()).contains(fixture.path("style").asText(),fixture.path("state").asText(),fixture.path("fact").asText()).doesNotContain("future-secret","unused-character-99","unused-prop-99");assertThat(compiled.prompt().length()).isLessThan(12_000);assertThat(compiled.references()).hasSize(4);}}
 @Test void fixtureSetIncludesRealLongStoryScale(){JsonNode f=read().get(4);assertThat(f.path("plannedShots").asInt()).isBetween(100,200);assertThat(f.path("characters").asInt()).isGreaterThanOrEqualTo(10);assertThat(f.path("locations").asInt()).isGreaterThanOrEqualTo(5);}
 @Test void shotTwoHundredKeepsItsRelevantFactWithoutSendingTheWholeHistory(){ObjectNode request=request(read().get(4)),shot=(ObjectNode)request.path("shot");shot.put("shotId","long-series-shot-200").put("storyTime",200);ArrayNode facts=request.putArray("storyFacts");for(int i=1;i<200;i++)facts.add(obj().put("id","old-"+i).put("statement","其他支线事实 "+i).put("subjectEntityId","unused-character-"+i).put("validFromStoryTime",i));facts.add(obj().put("id","current-fact").put("statement","演员在第二百镜确认贯穿道具仍由自己持有").put("subjectEntityId","actor").put("objectEntityId","prop").put("validFromStoryTime",200));var compiled=new PromptCompiler(mapper,new ContinuityEngine(mapper)).compileImage(request);assertThat(compiled.prompt()).contains("演员在第二百镜确认贯穿道具仍由自己持有").doesNotContain("其他支线事实 1").hasSizeLessThan(12_000);}
    @Test void providerPromptConsumesDirectorIntentBlockingAndPerformance(){ObjectNode request=request(read().get(0)),shot=(ObjectNode)request.path("shot");shot.put("directorIntent","SHOW_REACTION").put("shotPurpose","让观众先看到听者压住惊恐").put("subject","actor").put("eyeLine","向画面右侧").put("focus","左眼泪光");shot.set("blocking",obj().put("axis","门与供桌轴线").put("cameraWorldPosition","供桌南侧").put("doorWindowState","南门关闭"));shot.set("performancePlan",obj().put("primaryAction","听者停止呼吸").put("microExpression","下眼睑轻颤").put("bodyLanguage","肩膀僵住").put("gaze","不敢看门").put("gesture","手指收紧"));String prompt=new PromptCompiler(mapper,new ContinuityEngine(mapper)).compileImage(request).prompt();assertThat(prompt).contains("SHOW_REACTION","门与供桌轴线","下眼睑轻颤","左眼泪光").containsOnlyOnce("SHOW_REACTION");}
 @Test void mediaCompilationRejectsAContradictoryShotBeforeProvider(){ObjectNode request=request(read().get(0)),shot=(ObjectNode)request.path("shot");shot.putObject("visibilityPlan").put("occlusion","HEAVY").put("requiredDetail","IDENTITY");assertThatThrownBy(()->new PromptCompiler(mapper,new ContinuityEngine(mapper)).compileImage(request)).hasMessageContaining("INFORMATION_VISIBILITY_CONFLICT");}
 private JsonNode read(){try(InputStream in=getClass().getResourceAsStream("/acceptance/production-fixtures.json")){return mapper.readTree(in);}catch(Exception e){throw new IllegalStateException(e);}}
 private ObjectNode request(JsonNode f){ObjectNode r=obj();ObjectNode shot=r.putObject("shot").put("shotId",f.path("id").asText()+"-shot-10").put("duration",3).put("purpose","验收").put("action","完成一次明确动作").put("shotSize","MEDIUM").put("cameraAngle","EYE_LEVEL").put("cameraMovement","STATIC").put("locationId","location").put("relationToPrevious","ESTABLISHING").put("difficulty","B");shot.putArray("characterIds").add("actor");shot.putArray("propIds").add("prop");shot.putArray("dialogueIds");shot.set("cameraPlan",obj().put("position","正前方").put("height","胸口").put("distance","3米").put("lensMm",50).put("horizontalAngle","正面").put("verticalAngle","水平").put("subjectPlacement","左三分之一").put("focusPoint","眼睛").put("depthOfField","中等").put("lightingDirection","左后方"));shot.set("referenceViews",obj().put("look","FRONT").put("location","FRONT").put("prop","FRONT"));ObjectNode state=obj();state.putObject("characters").putObject("actor").put("identityId","actor").put("lookId","look").put("holding","prop").put("position","门前");state.putObject("props").putObject("prop").put("holder","actor").put("position","右手").put("state","完好");shot.set("startState",state);r.set("previousState",state.deepCopy());r.put("style",f.path("style").asText());r.putArray("storyFacts").add(obj().put("statement",f.path("fact").asText()).put("knownBy","actor"));r.putObject("characterStates").putObject("actor").set("state",obj().put("description",f.path("state").asText()));ObjectNode assets=r.putObject("assets").put("style",f.path("style").asText());assets.putArray("characters").add(obj().put("id","actor").put("name","验收人物").set("identityTraits",obj().put("face","固定脸型")));ObjectNode look=assets.putArray("looks").addObject().put("id","look").put("characterId","actor").put("description","固定基础定妆");ObjectNode location=assets.putArray("locations").addObject().put("id","location").put("description","固定布局");ObjectNode prop=assets.putArray("props").addObject().put("id","prop").put("description","贯穿道具");views(look,false);views(location,true);views(prop,false);return r;}
 private void views(ObjectNode a,boolean location){ArrayNode v=a.putArray("approvedViews");String[] names=location?new String[]{"FRONT","SIDE","REVERSE","LAYOUT"}:new String[]{"FRONT","SIDE","BACK","DETAIL"};for(String n:names)v.addObject().put("id",a.path("id").asText()+n).put("view",n).put("setVersion",1).put("approved",true).put("providerUrl","https://example.com/"+n+".png");}
}

