<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import StoryReview from './components/StoryReview.vue'
import AssetViews from './components/AssetViews.vue'

const tabs=[['create','创作'],['review','审查台'],['assets','素材多视图'],['director','导演台'],['edit','剪辑台']]
const active=ref('create'), system=ref(null), projects=ref([]), projectId=ref(localStorage.getItem('drama.projectId')||''), workspace=ref(null), selectedShotId=ref(''), busy=ref(false), toast=ref(''), error=ref(''), editingStory=ref(false)
const soundPlans=reactive({}), soundItems=reactive({}), voiceDrafts=reactive({}), previewLoad=reactive({}), reviewedEndStates=reactive({})
const projectForm=reactive({name:'',idea:'',episodeCount:1,targetDuration:20,style:'乡村写实电影',ratio:'9:16',dialect:'MANDARIN',directorPreset:'balanced'})
const directorPresets={balanced:{visualRhythm:'动作清楚，信息变化时切镜',averageShotLength:3,cameraActivity:'LOW',closeUpPreference:.45,reactionShotPreference:.65,compositionStyle:'先建立空间，再按人物关系组织景别',tensionStyle:'通过信息保留和反应逐级推进'},fast:{visualRhythm:'动作完成即切镜，关键反应保留停顿',averageShotLength:2.2,cameraActivity:'BALANCED',closeUpPreference:.55,reactionShotPreference:.7,compositionStyle:'中近景推进，重要空间先用全景交代',tensionStyle:'缩短信息变化之间的间隔'},emotion:{visualRhythm:'对白留出呼吸，反应先于解释',averageShotLength:3.8,cameraActivity:'LOW',closeUpPreference:.75,reactionShotPreference:.9,compositionStyle:'以视线和面部反应组织正反打',tensionStyle:'延迟切镜观察情绪变化'},graphic:{visualRhythm:'明确姿态与构图转换',averageShotLength:2.8,cameraActivity:'BALANCED',closeUpPreference:.5,reactionShotPreference:.55,compositionStyle:'轮廓清楚，前中后景层次分离',tensionStyle:'用构图尺度变化推进信息'}}
const dialogueForm=reactive({displayText:'',dialectText:'',speechText:'',dialect:'MANDARIN'})
let events=null, refreshTimer=null
const items=key=>workspace.value?.[key]||[]
const project=computed(()=>workspace.value?.project||projects.value.find(p=>p.id===projectId.value))
const activeStoryDocumentId=computed(()=>project.value?.activeStoryDocumentId||'')
const episodes=computed(()=>items('episodes').filter(item=>!item.stale&&(!activeStoryDocumentId.value||item.storyBibleId===activeStoryDocumentId.value)))
const episodeIds=computed(()=>new Set(episodes.value.map(item=>item.id)))
const scenes=computed(()=>items('scenes').filter(item=>!item.stale&&(!activeStoryDocumentId.value?true:episodeIds.value.has(item.episodeId))))
const sceneIds=computed(()=>new Set(scenes.value.map(item=>item.id)))
const shots=computed(()=>items('shots').filter(item=>!item.stale&&sceneIds.value.has(item.sceneId)).slice().sort((a,b)=>(a.shotNo||0)-(b.shotNo||0)))
const characters=computed(()=>items('characters').filter(item=>!item.stale&&(!activeStoryDocumentId.value||item.storyBibleId===activeStoryDocumentId.value)))
const characterIds=computed(()=>new Set(characters.value.map(item=>item.id)))
const locations=computed(()=>items('locations').filter(item=>!item.stale&&(!activeStoryDocumentId.value||item.storyBibleId===activeStoryDocumentId.value)))
const looks=computed(()=>items('character-looks').filter(item=>!item.stale&&characterIds.value.has(item.characterId)))
const props=computed(()=>items('props').filter(item=>!item.stale&&(!activeStoryDocumentId.value||item.storyBibleId===activeStoryDocumentId.value)))
const voices=computed(()=>items('voice-profiles').filter(item=>!item.stale&&item.approved===true&&item.referenceAudioUrl&&characterIds.value.has(item.characterId)))
const retiredJobTypes=new Set(['CHARACTER_PLAN','CHARACTER_LOOK','LOCATION_LOOK','SHOT_PLAN','REPAIR'])
const archivedLegacyJobs=computed(()=>items('jobs').filter(job=>retiredJobTypes.has(job.type)))
const jobs=computed(()=>items('jobs').filter(job=>!retiredJobTypes.has(job.type)).slice().reverse())
const selectedShot=computed(()=>shots.value.find(s=>s.id===selectedShotId.value)||shots.value[0]||null)
const shotAssets=(key)=>items(key).filter(x=>x.shotId===selectedShot.value?.id)
const mediaUrl=a=>a?.previewUrl||a?.archiveUrl||a?.videoUrl||a?.providerUrl||''
const jobLabel=s=>({QUEUED:'排队中',RUNNING:'生成中',SUCCESS:'已完成',FAILED:'失败',CANCELLED:'已取消',RETRY_WAIT:'等待重试'}[s]||s)
const providerTrace=(job)=>{const parts=[];if(job.providerRequestId)parts.push(`请求ID：${job.providerRequestId}`);if(job.providerTaskId)parts.push(`任务ID：${job.providerTaskId}`);return parts.join(' · ')}
const automaticReviewFor=id=>items('qc-results').filter(item=>item.targetId===id&&item.reviewer==='AUTOMATIC').sort((a,b)=>(a.reviewSequence||0)-(b.reviewSequence||0)).at(-1)
const automaticRouteLabel=route=>({AUTO_PASS:'自动通过',AUTO_REGENERATE:'自动返修',MANUAL_REVIEW:'需要人工复核'}[route]||route||'等待质检')
const shotStatusLabel=s=>({PLANNED:'待生成画面',STORYBOARD_GENERATING:'分镜生成中',KEYFRAME_GENERATING:'关键帧生成中',KEYFRAME_READY:'关键帧待审查',KEYFRAME_LOCKED:'关键帧已采用',VIDEO_GENERATING:'视频生成中',VIDEO_READY:'视频待审查',VIDEO_LOCKED:'视频已采用',NEEDS_REPAIR:'需要修订'}[s]||s||'未设置')
const relationLabel=s=>({ESTABLISHING:'建立镜头',CONTINUOUS:'连续动作',REACTION:'反应镜头',REVERSE_SHOT:'正反打',INSERT:'插入镜头',CUTAWAY:'切出镜头',MATCH_CUT:'匹配剪辑',TIME_JUMP:'时间跳跃',LOCATION_CHANGE:'场景切换'}[s]||s||'未设置')
const reviewStatusLabel=s=>({PENDING:'待质检',PASSED:'质检通过',FAILED:'审查未通过',GENERATING:'生成中'}[s]||s||'待质检')
const failureChoices=[['IDENTITY_MISMATCH','人物身份或脸不一致'],['CHARACTER_COUNT_ERROR','人物数量错误'],['AGE_MISMATCH','年龄错误'],['HAIR_MISMATCH','发型错误'],['CLOTHING_MISMATCH','服装错误'],['PROP_MISMATCH','道具、持有人或使用方式错误'],['LOCATION_MISMATCH','地点或门窗状态错误'],['POSITION_MISMATCH','空间位置或朝向错误'],['ACTION_MISMATCH','动作错误'],['EXPRESSION_MISMATCH','表情错误'],['CAMERA_MISMATCH','机位、角度或拍摄方向错误'],['COMPOSITION_ERROR','景别、主体位置或构图错误'],['STYLE_MISMATCH','视觉风格错误'],['TEXT_OR_WATERMARK','文字或水印'],['CONTINUITY_MISMATCH','与上一镜不连续'],['REFERENCE_FAILURE','参考图错误或失效'],['OTHER','其他']]
const cameraFields=[['position','机位位置'],['height','相机高度'],['distance','距离'],['lensMm','镜头焦段'],['verticalAngle','俯仰角'],['horizontalAngle','水平朝向'],['subjectPlacement','主体位置'],['focusPoint','对焦点'],['depthOfField','景深'],['lightingDirection','光线方向']]
function previewLoaded(id){return previewLoad[id]==='loaded'}
function previewFailed(id){return previewLoad[id]==='failed'}
function markPreviewLoaded(id){previewLoad[id]='loaded'}
function markPreviewFailed(id){previewLoad[id]='failed'}
function canReviewAsset(asset){return Boolean(mediaUrl(asset)&&previewLoaded(asset.id)&&!previewFailed(asset.id))}
const stateFieldLabel=field=>({locationId:'场景',time:'时间',lighting:'光线',spatialRelations:'空间关系',characterId:'人物',lookId:'定妆',position:'位置',pose:'姿态',lookDirection:'视线',holding:'持物',actionState:'动作状态',holder:'持有人',state:'道具状态',identity:'身份',material:'材质',scale:'比例'}[field]||field)
const stateValue=value=>{if(typeof value==='object'&&value!==null)return Object.entries(value).map(([key,item])=>`${stateFieldLabel(key)}：${stateValue(item)}`).join('；');return [...characters.value,...looks.value,...locations.value,...props.value].find(item=>item.id===value)?.name||String(value??'无')}
const visibleEndState=computed(()=>{const shot=selectedShot.value;if(!shot?.endState)return null;const state=shot.endState;return {...state,characters:Object.fromEntries((shot.characterIds||[]).filter(id=>state.characters?.[id]).map(id=>[id,state.characters[id]])),props:Object.fromEntries((shot.propIds||[]).filter(id=>state.props?.[id]).map(id=>[id,state.props[id]]))}})
const endStateRows=computed(()=>{const state=visibleEndState.value;if(!state)return [];return Object.entries(state).flatMap(([field,value])=>['characters','props'].includes(field)?Object.entries(value).map(([id,detail])=>({label:stateValue(id),value:stateValue(detail)})):[{label:stateFieldLabel(field),value:stateValue(value)}])})

async function api(path,options={}){const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let body=null;try{body=await response.json()}catch{}if(!response.ok){const trace=[body?.providerRequestId&&`请求ID：${body.providerRequestId}`,body?.providerTaskId&&`任务ID：${body.providerTaskId}`].filter(Boolean).join(' · ');throw new Error(`${body?.message||'操作失败'}${trace?` · ${trace}`:''}`)}return body}
async function act(label,fn){busy.value=true;error.value='';try{const result=await fn();toast.value=label;await refresh();return result}catch(e){error.value=e.message;return null}finally{busy.value=false;setTimeout(()=>toast.value='',2400)}}
async function loadProjects(){projects.value=await api('/resources/projects');if(!projectId.value&&projects.value.length)projectId.value=projects.value[0].id}
async function refresh(){if(!projectId.value){workspace.value=null;return}workspace.value=await api(`/resources/projects/${projectId.value}/workspace`);if(!selectedShotId.value&&shots.value.length)selectedShotId.value=shots.value[0].id}
async function createProject(){await act('项目已创建',async()=>{const {directorPreset,...base}=projectForm;const p=await api('/resources/projects',{method:'POST',body:JSON.stringify({...base,directorStyleProfile:directorPresets[directorPreset]})});projectId.value=p.id;await loadProjects()})}
async function uploadVoice(actor,event){const file=event.target.files?.[0];if(!file)return;if(!/audio\/(mpeg|wav|x-wav|wave)/i.test(file.type)&&!/[.]wav$|[.]mp3$/i.test(file.name)){error.value='请上传 MP3 或 WAV 音频';event.target.value='';return}busy.value=true;error.value='';try{const form=new FormData();form.append('file',file);const response=await fetch('/api/media',{method:'POST',body:form});const saved=await response.json();if(!response.ok)throw new Error(saved?.message||'音色上传失败');voiceDrafts[actor.id]={url:saved.url,name:file.name};toast.value='音色已上传，可试听后确认'}catch(e){error.value=e.message}finally{busy.value=false;event.target.value=''}}
async function approveVoice(actor){const draft=voiceDrafts[actor.id];if(!draft?.url)return;if(!window.confirm('请先试听这段音频，确认音色、清晰度和人物匹配后再保存。'))return;const name=window.prompt('声音档案名称',`${actor.name}的声音`)||`${actor.name}的声音`;await act('音色已确认',()=>api('/resources/voice-profiles',{method:'POST',body:JSON.stringify({projectId:projectId.value,characterId:actor.id,name,referenceAudioUrl:draft.url,approved:true,dialect:project.value?.dialect||'MANDARIN',status:'AVAILABLE'})}));delete voiceDrafts[actor.id]}
async function reviseAndRegenerate(){if(!selectedShot.value)return;await act('已创建局部重拍版本',async()=>{await api(`/shots/${selectedShot.value.id}/revise`,{method:'POST'});return api(`/shots/${selectedShot.value.id}/keyframe`,{method:'POST',body:JSON.stringify({requestKey:crypto.randomUUID()})})})}
async function regenerateFrame(frame){await act('已按原参数提交重画',()=>api(`/keyframes/${frame.id}/regenerate`,{method:'POST',body:JSON.stringify({requestKey:crypto.randomUUID()})}))}
async function designSound(episode){const result=await act('声音设计建议已生成',()=>api(`/episodes/${episode.id}/sound-design`,{method:'POST',body:'{}'}));if(result)soundPlans[episode.id]=result}
async function uploadSound(episode,event,track){const file=event.target.files?.[0];if(!file)return;busy.value=true;error.value='';try{const form=new FormData();form.append('file',file);const response=await fetch('/api/media',{method:'POST',body:form});const saved=await response.json();if(!response.ok)throw new Error(saved?.message||'上传失败');const duration=Math.max(.2,Number(prompt('这段声音在成片中使用多少秒？',track==='BGM'?'18':'1'))||1);const start=Math.max(0,Number(prompt('从成片第几秒开始？','0'))||0);soundItems[episode.id]??=[];soundItems[episode.id].push({track,sourceUrl:saved.url,startMs:Math.round(start*1000),durationMs:Math.round(duration*1000),volume:track==='BGM'?.16:.55});toast.value='声音素材已归档'}catch(e){error.value=e.message}finally{busy.value=false;event.target.value=''}}
async function createTimeline(episode){return act('时间线任务已开始',()=>api(`/episodes/${episode.id}/timeline`,{method:'POST',body:JSON.stringify({requestKey:crypto.randomUUID(),soundDesign:soundPlans[episode.id],soundItems:soundItems[episode.id]||[]})}))}
async function lock(kind,id,body={}){return act('已采用并锁定',()=>api(`/${kind}/${id}/lock`,{method:'POST',body:JSON.stringify(body)}))}
async function review(kind,id,passed=true,observedState=null){if(passed&&!window.confirm('请先实际查看图片或视频，核对人物身份、定妆、场景、道具、机位和动作连续性。确认已完成人工检查后再提交。'))return;const notes=passed?window.prompt('请输入人工检查结论（例如：人物、服装、道具和镜头衔接均一致）','人工检查通过'):window.prompt('请输入需要重做的原因','需要重做');if(notes===null||!notes.trim())return;const body={passed,score:passed?92:45,notes:notes.trim(),reviewer:'HUMAN'};if(!passed){const menu=failureChoices.map((item,index)=>`${index+1}. ${item[1]}`).join('\n');const selected=window.prompt(`请选择所有问题类型，用逗号分隔序号：\n${menu}`,'');if(selected===null)return;body.failureCodes=[...new Set(selected.split(/[,，\s]+/).map(value=>failureChoices[Number(value)-1]?.[0]).filter(Boolean))];if(!body.failureCodes.length)body.failureCodes=['OTHER']}if(observedState)body.observedState=observedState;return act(passed?'人工检查通过':'已标记重做',()=>api(`/${kind}/${id}/review`,{method:'POST',body:JSON.stringify(body)}))}
async function automaticReview(kind,id){const media=kind==='keyframes'?'keyframes':'video-takes';return act('视觉模型质检完成',()=>api(`/${media}/${id}/automatic-review`,{method:'POST',body:JSON.stringify({apply:true})}))}
async function generate(path,label){return act(label,()=>api(path,{method:'POST',body:JSON.stringify({requestKey:crypto.randomUUID()})}))}
async function addDialogue(){if(!selectedShot.value)return;await act('对白已添加',()=>api('/resources/dialogue-lines',{method:'POST',body:JSON.stringify({...dialogueForm,projectId:projectId.value,shotId:selectedShot.value.id})}));Object.assign(dialogueForm,{displayText:'',dialectText:'',speechText:'',dialect:project.value?.dialect||'MANDARIN'})}
async function confirmDialect(line){const dialectText=prompt('真实方言表达',line.dialectText||line.displayText);if(dialectText===null)return;const speechText=prompt('给 TTS 的发音文本',line.speechText||dialectText);if(speechText===null)return;await act('方言与发音已确认',()=>api(`/dialogue-lines/${line.id}/dialect`,{method:'POST',body:JSON.stringify({dialect:line.dialect||project.value?.dialect||'LEIYANG',correction:{approved:true,dialectText,speechText}})}))}
async function assignVoice(line,voiceProfileId){if(!voiceProfileId)return;await act('对白音色已绑定',()=>api(`/resources/dialogue-lines/${line.id}`,{method:'PUT',body:JSON.stringify({...line,voiceProfileId,revision:line.revision})}))}
function connectEvents(){events?.close();if(!projectId.value)return;events=new EventSource(`/api/events?projectId=${projectId.value}`);events.addEventListener('connected',()=>refresh());events.addEventListener('job',e=>{const job=JSON.parse(e.data);const current=workspace.value?.jobs?.find(j=>j.id===job.id);if(current)Object.assign(current,job);clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,300)})}
watch(projectId,async value=>{localStorage.setItem('drama.projectId',value);await refresh();connectEvents()})
onMounted(async()=>{try{system.value=await api('/system');await loadProjects();await refresh();connectEvents()}catch(e){error.value=e.message}})
onBeforeUnmount(()=>{events?.close();clearTimeout(refreshTimer)})
</script>

<template>
<div class="shell">
  <header><div class="brand"><span class="mark">拾</span><div><h1>拾光</h1><p>AI 短剧工作室</p></div></div><nav><button v-for="[id,label] in tabs" :key="id" :disabled="editingStory && id!=='review'" :class="{active:active===id}" @click="active=id">{{label}}</button></nav><div class="header-actions"><select v-model="projectId" :disabled="editingStory"><option value="">选择作品</option><option v-for="p in projects" :value="p.id" :key="p.id">{{p.name}}</option></select><button class="ghost" @click="refresh">刷新</button></div></header>
  <div v-if="system?.simulated" class="demo">当前是本地演示模式：会验证全部流程，但不会调用真实模型，也不代表真实画质。</div>
  <div v-if="error" class="notice error">{{error}} <button @click="error=''">×</button></div><div v-if="toast" class="notice ok">{{toast}}</div>

  <main v-if="active==='create'" class="workspace create-grid">
    <section class="hero"><span class="eyebrow">从一个想法开始</span><h2>把故事做成可拍、可改、可追溯的短剧</h2><p>先确认故事和人物，再进入镜头生产。每个失败镜头都能单独重做。</p></section>
    <section class="panel form-panel"><h3>新作品</h3><label>作品名<input v-model="projectForm.name" placeholder="例如：田埂上的红布"/></label><label>一句话想法<textarea v-model="projectForm.idea" rows="4" placeholder="谁，在什么处境下，遇到了什么变化？"/></label><div class="form-row"><label>集数<input v-model.number="projectForm.episodeCount" type="number" min="1" max="100"/></label><label>单集秒数<input v-model.number="projectForm.targetDuration" type="number" min="10" max="1800"/></label><label>画幅<select v-model="projectForm.ratio"><option>9:16</option><option>16:9</option><option>1:1</option></select></label></div><div class="form-row"><label>视觉风格<input v-model="projectForm.style"/></label><label>镜头节奏<select v-model="projectForm.directorPreset"><option value="balanced">稳定叙事</option><option value="fast">动作完成即切镜</option><option value="emotion">优先观察人物反应</option><option value="graphic">强调轮廓与构图变化</option></select></label><label>口播<select v-model="projectForm.dialect"><option value="MANDARIN">普通话</option><option value="LEIYANG">耒阳方言</option></select></label></div><button class="primary" :disabled="busy||!projectForm.name||!projectForm.idea" @click="createProject">创建作品</button></section>
    <section v-if="project" class="panel project-card"><div><span class="eyebrow">当前作品</span><h3>{{project.name}}</h3><p>{{project.idea}}</p></div><div class="stats"><span><b>{{episodes.length}}</b> 集</span><span><b>{{scenes.length}}</b> 场</span><span><b>{{shots.length}}</b> 镜</span></div><p class="muted">故事核心、分批集纲和单集剧本统一在审查台编辑与确认。</p><button class="primary" @click="active='review'">打开创作审查台</button></section>
    <section v-if="jobs.length||archivedLegacyJobs.length" class="panel jobs"><h3>最近任务</h3><div v-for="job in jobs.slice(0,6)" :key="job.id" class="job"><span>{{job.type}}</span><i :class="job.status.toLowerCase()">{{jobLabel(job.status)}}</i><small>{{job.progress||0}}%</small><p v-if="job.failureReason" class="job-failure">{{job.failureReason}}<span v-if="job.submissionUncertain"> · 请先核对服务商记录，避免重复提交。</span></p><small v-if="providerTrace(job)" class="provider-trace">三方记录：{{providerTrace(job)}}</small></div><p v-if="archivedLegacyJobs.length" class="muted">已归档 {{archivedLegacyJobs.length}} 条旧流程任务，不参与当前生产。</p></section>
  </main>

  <StoryReview v-else-if="active==='review'" :project="project" :workspace="workspace" :busy="busy" @refresh="refresh" @editing="editingStory=$event" @message="(message, isError) => { (isError ? error = message : toast = message) }" />

  <AssetViews v-else-if="active==='assets'" :project="project" :workspace="workspace" :busy="busy" @refresh="refresh" @message="(message, isError) => { (isError ? error = message : toast = message) }" />

  <main v-else-if="active==='director'" class="director">
    <aside class="scene-list"><span class="eyebrow">镜头顺序</span><div v-for="scene in scenes" :key="scene.id" class="scene"><div><b>{{scene.name}}</b><button class="tiny" @click="generate(`/scenes/${scene.id}/plan`,'拆镜任务已开始')">拆镜</button></div><button v-for="shot in shots.filter(s=>s.sceneId===scene.id)" :key="shot.id" :class="['shot-row',{active:selectedShot?.id===shot.id}]" @click="selectedShotId=shot.id"><span>{{String(shot.shotNo||1).padStart(2,'0')}}</span><p>{{shot.purpose}}</p><i>{{shot.editDuration||shot.duration}}s</i></button></div></aside>
    <section class="stage"><div v-if="selectedShot" class="viewer"><template v-if="shotAssets('video-takes').length"><video :key="shotAssets('video-takes').at(-1).id" controls :src="mediaUrl(shotAssets('video-takes').at(-1))" @loadeddata="markPreviewLoaded(shotAssets('video-takes').at(-1).id)" @error="markPreviewFailed(shotAssets('video-takes').at(-1).id)"/><p v-if="previewFailed(shotAssets('video-takes').at(-1).id)" class="preview-error">预览加载失败，请检查链接/网络后重试</p></template><template v-else-if="shotAssets('keyframes').length"><img :key="shotAssets('keyframes').at(-1).id" :src="mediaUrl(shotAssets('keyframes').at(-1))" @load="markPreviewLoaded(shotAssets('keyframes').at(-1).id)" @error="markPreviewFailed(shotAssets('keyframes').at(-1).id)"/><p v-if="previewFailed(shotAssets('keyframes').at(-1).id)" class="preview-error">预览加载失败，请检查链接/网络后重试</p></template><div v-else class="empty-frame"><span>镜头 {{selectedShot.shotNo}}</span><p>分镜或关键帧会显示在这里</p></div></div><div v-else class="empty-frame"><p>先从左侧选择镜头</p></div>
      <div v-if="selectedShot" class="takes"><button v-for="take in shotAssets('video-takes')" :key="take.id">Take {{take.takeNo}} · {{take.providerStatus}}</button></div>
    </section>
    <aside v-if="selectedShot" class="inspector"><span class="pill">{{shotStatusLabel(selectedShot.status)}}</span><h2>{{selectedShot.purpose}}</h2><dl><dt>动作</dt><dd>{{selectedShot.action}}</dd><dt>镜头</dt><dd>{{selectedShot.shotSize}} · {{selectedShot.cameraMovement}}</dd><dt>成片时长</dt><dd>{{selectedShot.editDuration||selectedShot.duration}} 秒</dd><dt>衔接</dt><dd>{{relationLabel(selectedShot.relationToPrevious)}}</dd></dl><details v-if="selectedShot.directorIntent" class="camera-plan"><summary>查看剧情节拍与导演意图</summary><dl><dt>剧情节拍</dt><dd>{{selectedShot.dramaticBeatSnapshot?.beatPurpose||selectedShot.beatId}}</dd><dt>情绪推进</dt><dd>{{selectedShot.dramaticBeatSnapshot?.emotionBefore}} → {{selectedShot.dramaticBeatSnapshot?.emotionAfter}}</dd><dt>导演意图</dt><dd>{{selectedShot.directorIntent}}</dd><dt>镜头理由</dt><dd>{{selectedShot.shotPurpose}}</dd><dt>主要主体</dt><dd>{{selectedShot.subject}}</dd><dt>版本</dt><dd>导演 {{selectedShot.directorPlanVersion}} · 节拍 {{selectedShot.dramaticBeatVersion}} · 镜头 {{selectedShot.shotPlanVersion}}</dd></dl></details><details v-if="selectedShot.blocking" class="camera-plan"><summary>查看人物调度与表演</summary><dl><dt>表演轴线</dt><dd>{{selectedShot.blocking.axis}} · {{selectedShot.blocking.axisSide}}</dd><dt>机位</dt><dd>{{selectedShot.blocking.cameraWorldPosition}}</dd><dt>门窗状态</dt><dd>{{selectedShot.blocking.doorWindowState}}</dd><dt>主要动作</dt><dd>{{selectedShot.performancePlan?.primaryAction}}</dd><dt>微表情</dt><dd>{{selectedShot.performancePlan?.microExpression}}</dd><dt>视线</dt><dd>{{selectedShot.performancePlan?.gaze}}</dd></dl></details><details v-if="selectedShot.cameraPlan" class="camera-plan"><summary>查看完整机位方案</summary><dl><template v-for="[field,label] in cameraFields" :key="field"><dt>{{label}}</dt><dd>{{selectedShot.cameraPlan[field] || '未填写' }}<span v-if="field==='lensMm'"> mm</span></dd></template></dl></details><div class="button-stack"><button @click="generate(`/shots/${selectedShot.id}/storyboard`,'分镜任务已开始')">生成分镜</button><button class="primary" @click="generate(`/shots/${selectedShot.id}/keyframe`,'关键帧任务已开始')">生成关键帧</button></div>
      <div v-for="board in shotAssets('storyboards')" :key="board.id" class="version"><b>分镜 v{{board.version}}</b><img v-if="mediaUrl(board)" class="review-thumb" :src="mediaUrl(board)" @load="markPreviewLoaded(board.id)" @error="markPreviewFailed(board.id)"/><small v-if="previewFailed(board.id)" class="preview-error">预览加载失败，请检查链接/网络后重试</small><span>{{reviewStatusLabel(board.qcStatus)}}</span><button v-if="board.qcStatus!=='PASSED'" class="tiny" :disabled="!canReviewAsset(board)" @click="review('storyboards',board.id,true)">人工检查并通过</button><button v-if="board.qcStatus==='PASSED'&&!board.locked" class="tiny" @click="lock('storyboards',board.id)">采用分镜</button></div>
      <div v-for="frame in shotAssets('keyframes')" :key="frame.id" class="version"><b>关键帧 v{{frame.version}}</b><img v-if="mediaUrl(frame)" class="review-thumb" :src="mediaUrl(frame)" @load="markPreviewLoaded(frame.id)" @error="markPreviewFailed(frame.id)"/><span>{{reviewStatusLabel(frame.qcStatus)}}</span><small v-if="automaticReviewFor(frame.id)">视觉模型：{{automaticRouteLabel(automaticReviewFor(frame.id).routingDecision)}} · {{automaticReviewFor(frame.id).score||0}} 分<span v-if="automaticReviewFor(frame.id).providerRequestId"> · 请求ID：{{automaticReviewFor(frame.id).providerRequestId}}</span></small><small v-if="previewFailed(frame.id)" class="preview-error">预览加载失败，请检查链接/网络后重试</small><button v-if="!frame.locked" class="tiny" :disabled="busy||!mediaUrl(frame)" @click="automaticReview('keyframes',frame.id)">视觉模型质检</button><button v-if="frame.qcStatus!=='PASSED'" class="tiny" :disabled="!canReviewAsset(frame)" @click="review('keyframes',frame.id,true)">人工检查图片并通过</button><button v-if="!frame.locked" class="tiny" @click="review('keyframes',frame.id,false)">退回重做</button><button v-if="frame.qcStatus==='PASSED'&&!frame.locked" class="tiny" @click="lock('keyframes',frame.id)">采用并生成视频</button><button v-if="frame.locked" class="tiny" @click="generate(`/keyframes/${frame.id}/video`,'新 Take 已开始')">再生成一条</button><button class="tiny" @click="regenerateFrame(frame)">按原参数重画</button></div>
      <div v-for="take in shotAssets('video-takes')" :key="take.id" class="version"><b>Take {{take.takeNo}}</b><video v-if="mediaUrl(take)" class="review-thumb" muted controls :src="mediaUrl(take)" @loadeddata="markPreviewLoaded(take.id)" @error="markPreviewFailed(take.id)"/><span>{{reviewStatusLabel(take.qcStatus)}}</span><small v-if="automaticReviewFor(take.id)">视觉模型：{{automaticRouteLabel(automaticReviewFor(take.id).routingDecision)}} · {{automaticReviewFor(take.id).score||0}} 分<span v-if="automaticReviewFor(take.id).providerRequestId"> · 请求ID：{{automaticReviewFor(take.id).providerRequestId}}</span></small><small v-if="previewFailed(take.id)" class="preview-error">预览加载失败，请检查链接/网络后重试</small><details v-if="take.providerStatus==='SUCCEEDED'" class="camera-plan"><summary>逐项核对视频末帧</summary><p>以下为计划状态。请观看末帧逐项核对，有偏差时退回重做，不能直接采用。</p><dl><template v-for="row in endStateRows" :key="row.label"><dt>{{row.label}}</dt><dd>{{row.value}}</dd></template></dl><label><input type="checkbox" v-model="reviewedEndStates[take.id]" :disabled="!canReviewAsset(take)"/>我已核对末帧，与以上状态一致</label></details><button v-if="take.providerStatus==='SUCCEEDED'&&!take.locked" class="tiny" :disabled="busy||!take.archiveUrl" @click="automaticReview('video-takes',take.id)">视觉模型质检视频</button><button v-if="take.providerStatus==='SUCCEEDED'&&take.qcStatus!=='PASSED'" class="tiny" :disabled="!canReviewAsset(take)||!reviewedEndStates[take.id]||!visibleEndState" @click="review('video-takes',take.id,true,visibleEndState)">人工检查视频并通过</button><button v-if="!take.locked" class="tiny" @click="review('video-takes',take.id,false)">退回重做</button><button v-if="take.qcStatus==='PASSED'&&!take.locked" class="tiny" @click="lock('video-takes',take.id)">采用</button><button v-if="take.locked&&shotAssets('audio-clips').some(c=>c.locked&&c.selected)" class="tiny" @click="generate(`/video-takes/${take.id}/lipsync`,'口型同步已开始')">口型同步</button></div>
      <button v-if="selectedShot.status==='NEEDS_REPAIR'" class="small" @click="reviseAndRegenerate">局部修订并重拍</button>
      <h3>对白</h3><div v-for="line in shotAssets('dialogue-lines')" :key="line.id" class="dialogue"><p>{{line.displayText}}</p><small>{{line.speechText||'发音待确认'}}</small><label class="dialogue-voice">已确认音色<select :value="line.voiceProfileId||''" @change="assignVoice(line,$event.target.value)"><option value="">请选择已确认音色</option><option v-for="voice in voices.filter(v=>v.characterId===line.characterId)" :key="voice.id" :value="voice.id">{{voice.name}}</option></select></label><div><button class="tiny" @click="confirmDialect(line)">确认方言</button><button class="tiny" :disabled="!line.speechText||!line.voiceProfileId" @click="generate(`/dialogue-lines/${line.id}/tts`,'配音任务已开始')">配音</button></div><div v-for="clip in shotAssets('audio-clips').filter(c=>c.dialogueLineId===line.id)" :key="clip.id" class="audio-take"><audio controls :src="clip.archiveUrl"/><button v-if="!clip.locked" class="tiny" @click="lock('audio-clips',clip.id)">采用配音</button><span v-else>已采用</span></div></div><label>普通话字幕<textarea v-model="dialogueForm.displayText" rows="2"/></label><button class="small" :disabled="!dialogueForm.displayText" @click="addDialogue">添加对白</button>
      <div v-if="selectedShot.characterIds?.length" class="voice-box"><h3>声音档案</h3><template v-for="actorId in selectedShot.characterIds" :key="actorId"><p>{{characters.find(c=>c.id===actorId)?.name}}：{{voices.find(v=>v.characterId===actorId)?.name||'尚未确认音色'}}</p><template v-if="voiceDrafts[actorId]?.url"><audio controls :src="voiceDrafts[actorId].url"/><button class="tiny" @click="approveVoice(characters.find(c=>c.id===actorId))">试听后确认</button></template><template v-else><label class="upload">上传 MP3/WAV 音色<input type="file" accept="audio/mpeg,audio/wav,.mp3,.wav" @change="uploadVoice(characters.find(c=>c.id===actorId),$event)"/></label></template></template></div>
    </aside><aside v-else class="inspector empty-frame">暂无镜头</aside>
  </main>

  <main v-else class="workspace edit-grid"><aside><span class="eyebrow">合成与导出</span><h2>剪辑台</h2><p>只会使用已质检、已采用且归档完成的素材。</p></aside><section><div v-for="episode in episodes" :key="episode.id" class="panel episode"><div><h3>{{episode.name}}</h3><p>{{episode.summary}}</p><small v-if="soundPlans[episode.id]">声音设计：{{soundPlans[episode.id].ambience?.length||0}} 个环境声，{{soundPlans[episode.id].sfx?.length||0}} 个拟音建议</small><div class="button-row"><button @click="designSound(episode)">生成声音设计</button><label class="upload">导入 BGM<input type="file" accept="audio/*" @change="uploadSound(episode,$event,'BGM')"/></label><label class="upload">导入音效<input type="file" accept="audio/*" @change="uploadSound(episode,$event,'SFX')"/></label></div><small v-if="soundItems[episode.id]?.length">已归档 {{soundItems[episode.id].length}} 条声音素材</small></div><button @click="createTimeline(episode)">生成时间线</button></div><div v-for="timeline in items('timelines')" :key="timeline.id" class="panel timeline"><div class="timeline-head"><div><span class="eyebrow">版本 {{timeline.version}}</span><h3>{{timeline.name}}</h3></div><span class="pill good">{{timeline.locked?'已锁定':timeline.status}}</span></div><div class="tracks"><div><b>视频</b><span v-for="item in items('timeline-items').filter(i=>i.timelineId===timeline.id&&i.track==='VIDEO')" :key="item.id" :style="{width:Math.max(8,item.durationMs/(timeline.durationMs||1)*100)+'%'}"></span></div><div><b>对白</b><span class="audio" v-for="item in items('timeline-items').filter(i=>i.timelineId===timeline.id&&i.track==='DIALOGUE')" :key="item.id" :style="{marginLeft:item.startMs/(timeline.durationMs||1)*100+'%',width:item.durationMs/(timeline.durationMs||1)*100+'%'}"></span></div><div><b>声音</b><span class="sound" v-for="item in items('timeline-items').filter(i=>i.timelineId===timeline.id&&['AMBIENCE','SFX','BGM'].includes(i.track))" :key="item.id" :style="{marginLeft:item.startMs/(timeline.durationMs||1)*100+'%',width:item.durationMs/(timeline.durationMs||1)*100+'%'}"></span></div></div><video v-if="timeline.finalUrl||timeline.previewUrl" controls :src="timeline.finalUrl||timeline.previewUrl"/><div class="button-row"><button v-if="!timeline.locked" @click="lock('timelines',timeline.id)">采用时间线</button><button :disabled="!timeline.locked" @click="generate(`/timelines/${timeline.id}/render`,'预览渲染已开始')">导出预览</button><button class="primary" :disabled="!timeline.locked" @click="act('最终渲染已开始',()=>api(`/timelines/${timeline.id}/render`,{method:'POST',body:JSON.stringify({quality:'FINAL',requestKey:crypto.randomUUID()})}))">导出最终</button></div><a v-if="timeline.finalUrl" :href="timeline.finalUrl" download>下载成片</a></div></section></main>
</div>
</template>

